#!/usr/bin/env python3
"""Generate bank-ui/src/i18n/legacy-ar.ts from the legacy VB6 caption tables.

The VB6 client was already bilingual. globalVaribles.bas / globalVaribles1.bas
declare 114 caption arrays as `frmXxxCaption(n, 2) As String` and fill both
slots — index 0 is Arabic, index 1 is English:

    frmStopChqDetailCaption(5, 0) = "تاريخ الايقاف"
    frmStopChqDetailCaption(5, 1) = "Stop Date"

plus ~300 message arrays in the same shape but one-dimensional:

    errCallHeadOffice(0) = "اتصل بالمركز لتشغيل النظام رقم 1"
    errCallHeadOffice(1) = "Call Head Office to activate static server"

That is the bank's own approved Arabic vocabulary for every screen this app
rebuilds, so it is the source we translate from rather than translating the
English afresh. Re-run after the .bas files change:

    python3 bank-ui/scripts/extract-legacy-captions.py

The two .bas files are Windows-1256 (Arabic ANSI), not UTF-8. Stdlib only.
"""

import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = REPO_ROOT / "docs" / "CSD for CBS-CMS VER 4.0.5"
SOURCES = ["globalVaribles.bas", "globalVaribles1.bas"]
OUT_PATH = REPO_ROOT / "bank-ui" / "src" / "i18n" / "legacy-ar.ts"

ENCODING = "cp1256"

# frmXxxCaption(12, 0) = "..."   — two-dimensional caption arrays
CAPTION = re.compile(r'^\s*([A-Za-z][A-Za-z0-9_]*)\(\s*(\d+)\s*,\s*([01])\s*\)\s*=\s*"(.*)"\s*$')
# errXxx(0) = "..."             — one-dimensional message arrays
MESSAGE = re.compile(r'^\s*((?:err|msg)[A-Za-z0-9_]*)\(\s*([01])\s*\)\s*=\s*"(.*)"\s*$')

ARABIC = re.compile(r"[؀-ۿ]")

# Tatweel / kashida (U+0640) is a purely decorative elongation, and the legacy
# is full of it — "الاســـم الثاني" — because VB6 labels were fixed-width and
# stretching the glyphs was how the form was made to line up. It carries no
# meaning, and the same caption appears both padded and unpadded across forms.
# Dropping it collapses those into one entry and stops the web UI inheriting a
# VB6 layout hack.
TATWEEL = "\u0640"

# A combining mark with no base letter in front of it — three legacy captions
# open a word with a stray kasra or tanween ("\u0650كشف حساب قديم"), which the
# VB6 label rendered as a floating accent. They are typing slips in the source,
# not orthography, and a modern text renderer makes them more obvious than the
# old one did.
ORPHAN_MARK = re.compile(r"(?<![^\W\d_])[\u064b-\u0652\u0670]+")


def clean_arabic(text: str) -> str:
    cleaned = ORPHAN_MARK.sub("", text.replace(TATWEEL, ""))
    return re.sub(r"\s+", " ", cleaned).strip()


def normalise(text: str) -> str:
    """Lookup key: case- and punctuation-insensitive so 'Account No:' finds
    'Account No'. Mirrors normaliseKey() in i18n/index.ts — keep the two in
    step."""
    return re.sub(r"[:*.\u2026]+$", "", re.sub(r"\s+", " ", text).strip()).strip().lower()


def parse() -> dict[tuple[str, int], dict[str, str]]:
    slots: dict[tuple[str, int], dict[str, str]] = defaultdict(dict)
    for name in SOURCES:
        path = SRC_DIR / name
        if not path.exists():
            sys.exit(f"missing legacy source: {path}")
        for raw in path.read_text(encoding=ENCODING).splitlines():
            line = raw.rstrip()
            if line.lstrip().startswith("'"):  # commented-out caption
                continue
            m = CAPTION.match(line)
            if m:
                slots[(m.group(1), int(m.group(2)))][m.group(3)] = m.group(4)
                continue
            m = MESSAGE.match(line)
            if m:
                slots[(m.group(1), 0)][m.group(2)] = m.group(3)
    return slots


def main() -> None:
    slots = parse()

    # English → Counter of Arabic renderings. A handful of English captions are
    # reused across forms with different Arabic; the most frequent wins and the
    # rest are reported so a human can pin an override in ar-extra.ts.
    by_english: dict[str, Counter] = defaultdict(Counter)
    for values in slots.values():
        arabic, english = values.get("0", "").strip(), values.get("1", "").strip()
        if not arabic or not english:
            continue
        # Some slots hold English in BOTH halves (never translated) — skip
        # those rather than emit an identity "translation".
        if not ARABIC.search(arabic):
            continue
        by_english[normalise(english)][clean_arabic(arabic)] += 1

    entries = {}
    conflicts = []
    for key, counter in sorted(by_english.items()):
        ranked = counter.most_common()
        entries[key] = ranked[0][0]
        if len(ranked) > 1:
            conflicts.append((key, ranked))

    lines = [
        "// GENERATED by bank-ui/scripts/extract-legacy-captions.py from the legacy",
        "// VB6 caption tables in docs/CSD for CBS-CMS VER 4.0.5/globalVaribles*.bas.",
        "// Do not edit by hand — add or override entries in ./ar-extra.ts instead.",
        "//",
        "// Keys are normalised English (see normaliseKey in ./index.ts); values are",
        "// the Arabic the legacy client showed for that caption.",
        "",
        "const LEGACY_AR: Record<string, string> = {",
    ]
    for key, arabic in entries.items():
        k = key.replace("\\", "\\\\").replace("'", "\\'")
        v = arabic.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  '{k}': '{v}',")
    lines += ["}", "", "export default LEGACY_AR", ""]
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")

    print(f"{len(entries)} EN→AR entries → {OUT_PATH.relative_to(REPO_ROOT)}")
    if conflicts:
        print(f"{len(conflicts)} English captions had more than one Arabic rendering; "
              f"most frequent kept. First few:")
        for key, ranked in conflicts[:10]:
            print(f"  {key!r}: " + ", ".join(f"{a!r}×{n}" for a, n in ranked))


if __name__ == "__main__":
    main()
