// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const acaptrTL: SchemaTable = {
  name: "acaptrTL",
  description: "Contains the branch/memo level computed interest for applicaiton.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 3 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2, k2: 1 }, description: "This field maintains a 4 digit branch\nnumber, defined by the financial institution,\nwhich is unique for each branch within the\nIMD number." },
    { name: "memoCode", label: "SUB LEDGER MEMO CODE", type: "string", size: 5, keys: { k1: 3, k2: 2 }, description: "Sub Ledger Memo Code (Currency Plus Memo)" },
    { name: "intFlag", label: "INTEREST FLAG", type: "string", size: 1, description: "Maintain INTEREST FLAG" },
    { name: "totCrInt", label: "TOTAL BRANCH CREDIT INTEREST", type: "numeric", size: 16, format: "16,3", description: "Credit Balance INTEREST" },
    { name: "totDrInt", label: "TOTAL BRANCH DEBIT INTEREST", type: "numeric", size: 16, format: "16,3", description: "Debit Balance INTEREST" },
    { name: "FileCount", label: "FILE COUNT", type: "numeric", size: 12, description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "FILE NAME", type: "string", size: 30, description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default acaptrTL
