// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const acd0data: SchemaTable = {
  name: "acd0data",
  description: "This table has the interest income,exoense,received and paid accounts at the memo level",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 3, k3: 1 }, description: "Data Restored date" },
    { name: "currency", label: "CURRENCY/COUNTRY CODE", type: "string", size: 2, keys: { k1: 2, k2: 1, k3: 3 }, description: "This field maintains the currency to which this record relates. The two codes \"00\" and \"01\" always relate to base currency." },
    { name: "ledgerCode", label: "LEDGER CODE", type: "string", size: 3, keys: { k1: 3, k2: 2, k3: 4 }, description: "This field maintains the unique identifier assigned to the ledger for accounting and financial tracking." },
    { name: "recType", label: "RECORD TYPE", type: "string", size: 2, description: "This field maintain Record Type." },
    { name: "intIncomeAccNo1", label: "INTEREST RECEIVED ACCOUNT 1", type: "string", size: 14, description: "If the Interest Received accounts are not\ndefined at memo level then this will be one\nof 6 accounts used. When debit interest is\napplied to a customer account, the opposite\namount is credited to either this or one of\nthe other Interest Received accounts. The\naccount used is determined by the\nINTEREST RECEIVED POINTER’ field on the interest accruing General Ledger\ndetail account.\nSee the \"INTEREST RECEIVED\nPOINTER’ field in the Detail General\nLedger record." },
    { name: "intIncomeAccNo2", label: "INTEREST RECEIVED ACCOUNT 2", type: "string", size: 14, description: "See \"INTEREST RECEIVED ACCOUNT 1\"" },
    { name: "intIncomeAccNo3", label: "INTEREST RECEIVED ACCOUNT 3", type: "string", size: 14, description: "See \"INTEREST RECEIVED ACCOUNT 1\"" },
    { name: "intIncomeAccNo4", label: "INTEREST RECEIVED ACCOUNT 4", type: "string", size: 14, description: "See \"INTEREST RECEIVED ACCOUNT 1\"" },
    { name: "intIncomeAccNo5", label: "INTEREST RECEIVED ACCOUNT 5", type: "string", size: 14, description: "See \"INTEREST RECEIVED ACCOUNT 1\"" },
    { name: "intIncomeAccNo6", label: "INTEREST RECEIVED ACCOUNT 6", type: "string", size: 14, description: "See \"INTEREST RECEIVED ACCOUNT 1\"" },
    { name: "intExpenseAccNo1", label: "INTEREST PAID ACCOUNT 1", type: "string", size: 14, description: "If the Interest Paid accounts are not defined\nat memo level then this will be one of 6\naccounts used. When credit interest is\napplied to a customer account the opposite\namount is debited to either this or one of the\nother Interest Paid accounts. The account\nused is determined by the INTEREST\nPAID POINTER’ on the interest accruing\nGeneral Ledger detail account. See the\n“INTEREST PAID POINTER field in the\nDetail General Ledger record." },
    { name: "intExpenseAccNo2", label: "INTEREST PAID ACCOUNT 2", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT 1" },
    { name: "intExpenseAccNo3", label: "INTEREST PAID ACCOUNT 3", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT 1" },
    { name: "intExpenseAccNo4", label: "INTEREST PAID ACCOUNT 4", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT 1" },
    { name: "intExpenseAccNo5", label: "INTEREST PAID ACCOUNT 5", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT 1" },
    { name: "intExpenseAccNo6", label: "INTEREST PAID ACCOUNT 6", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT 1" },
    { name: "intReceivedAmt1", label: "INTEREST RECEIVED AMOUNT 1", type: "numeric", size: 16, format: "16,3", description: "If the Interest Received AMOUNTs are\ndefined at memo level then this will be one\nof 6 AMOUNTs used. When debit interest is\napplied to a customer account, the opposite\namount is credited to either this or one of\nthe other Interest Received ACCOUNT. The\nAMOUNT used is determined by the\nINTEREST RECEIVED POINTER’ field on the interest accruing General Ledger\ndetail AMOUNT.\nSee the \"INTEREST RECEIVED\nPOINTER’ field in the Detail General\nLedger record." },
    { name: "intReceivedAmt2", label: "INTEREST RECEIVED AMOUNT 2", type: "numeric", size: 16, format: "16,3", description: "See \"INTEREST RECEIVED AMOUNT 1\"" },
    { name: "intReceivedAmt3", label: "INTEREST RECEIVED AMOUNT 3", type: "numeric", size: 16, format: "16,3", description: "See \"INTEREST RECEIVED AMOUNT 1\"" },
    { name: "intReceivedAmt4", label: "INTEREST RECEIVED AMOUNT 4", type: "numeric", size: 16, format: "16,3", description: "See \"INTEREST RECEIVED AMOUNT 1\"" },
    { name: "intReceivedAmt5", label: "INTEREST RECEIVED AMOUNT 5", type: "numeric", size: 16, format: "16,3", description: "See \"INTEREST RECEIVED AMOUNT 1\"" },
    { name: "intReceivedAmt6", label: "INTEREST RECEIVED AMOUNT 6", type: "numeric", size: 16, format: "16,3", description: "See \"INTEREST RECEIVED AMOUNT 1\"" },
    { name: "intPaidAmt1", label: "INTEREST PAID AMOUNT 1", type: "numeric", size: 16, format: "16,3", description: "If the Interest Paid AMOUNTs are not defined\nat memo level then this will be one of 6\nAMOUNTs used. When credit interest is\napplied to a customer account the opposite\namount is debited to either this or one of the\nother Interest Paid account. The AMOUNT\nused is determined by the INTEREST\nPAID POINTER’ on the interest accruing\nGeneral Ledger detail AMOUNT. See the\n“INTEREST PAID POINTER field in the\nDetail General Ledger record." },
    { name: "intPaidAmt2", label: "INTEREST PAID AMOUNT 2", type: "numeric", size: 16, format: "16,3", description: "See INTEREST PAID AMOUNT 1" },
    { name: "intPaidAmt3", label: "INTEREST PAID AMOUNT 3", type: "numeric", size: 16, format: "16,3", description: "See INTEREST PAID AMOUNT 1" },
    { name: "intPaidAmt4", label: "INTEREST PAID AMOUNT 4", type: "numeric", size: 16, format: "16,3", description: "See INTEREST PAID AMOUNT 1" },
    { name: "intPaidAmt5", label: "INTEREST PAID AMOUNT 5", type: "numeric", size: 16, format: "16,3", description: "See INTEREST PAID AMOUNT 1" },
    { name: "intPaidAmt6", label: "INTEREST PAID AMOUNT 6", type: "numeric", size: 16, format: "16,3", description: "See INTEREST PAID ACCOUNT 1" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k3: 2 }, description: "This field maintains a 4 digit branch\nnumber, defined by the financial institution,\nwhich is unique for each branch within the\nIMD number." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default acd0data
