// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const acrcal: SchemaTable = {
  name: "acrcal",
  description: "This table contains the interest that has been accrued at the account level.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 3, k3: 2 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2, k2: 1 }, description: "This field maintains a 4 digit branch\nnumber, defined by the financial institution,\nwhich is unique for each branch within the\nIMD number." },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 3, k2: 2, k3: 1 }, description: "Account number which is formed as below:\nCCMMMNNNNNNNSS\nDIGITS DESCRIPTION\n1-2 Currency Reference (CC).\n3-5 Memorandum Account Reference(MMM).\n6-12 Customer or Ledger Account Reference (NNNNNNN).\n13-14 Sub-account Reference (SS)" },
    { name: "intFlag", label: "INTEREST FLAG", type: "string", size: 1, description: "Maintain INTEREST FLAG" },
    { name: "accruedInt", label: "ACCRUED INTEREST", type: "numeric", size: 16, format: "16,3. Decimal precision is currency dependent", description: "This field maintains the interest which has\naccumulated on the account from the date.\nof the last interest application to the last\naccrual date. Every transaction posted to the\naccount accrues interest to the value date of\nthe transaction, (except transactions to\naccounts accruing interest via the Savings\nmethod)." },
    { name: "payeCr", label: "PAYEE CREDIT AMOUNT", type: "numeric", size: 16, format: "16,3. Decimal precision is currency dependent", description: "This field stores the credited amount assigned to the payee for financial transactions." },
    { name: "payeDr", label: "PAYEE DEBIT AMOUNT", type: "numeric", size: 16, format: "16,3. Decimal precision is currency dependent", description: "This field maintains the debited amount deducted from the payee’s account for financial processing." },
    { name: "intApplication", label: "INTEREST APPLICATION METHOD", type: "string", size: 1, description: "Valid values are:\n0 Capitalise (i.e. credit/debit the amount\ntoffrom the account which accrued the\ninterest).\n1 Pay to another account.\n2 Payby cheque.\n3 Memorandum interest only. (This value\nis calculated for reporting purposes\nonly. Itis not applied to any account).\n4 Capitalise and leave resulting balances\non the account.\n5 Principal to Pay Account. Interest to\nNostro.\n6 Principal to Matching Account. Interest\nto Pay Account." },
    { name: "payeAcc", label: "PAYEE ACCOUNT NUMBER", type: "string", size: 14, description: "This field stores the account number associated with the payee for transactions." },
    { name: "intFrequency", label: "INTEREST APPLICATION FREQUENCY", type: "string", size: 1, description: "This field maintains the defined frequency for interest application (e.g., monthly, quarterly, annually)." },
    { name: "doubtYtdInt", label: "YEAR TO DATE DOUBTFUL INTEREST", type: "numeric", size: 16, format: "16,3. Decimal precision is currency dependent", description: "This field records the total doubtful interest accumulated in the current financial year." },
    { name: "doubtFlag", label: "DOUBTFUL INTEREST FLAG", type: "string", size: 1, description: "This field stores the indicator flag determining whether the recorded interest is categorized as doubtful." },
    { name: "accrualAdjustment", label: "INTEREST ACCRUAL ADJUSTMENT", type: "numeric", size: 16, format: "16,3. Decimal precision is currency dependent", description: "This field maintains any modifications or corrections applied to accrued interest figures." },
    { name: "ytdInNormal", label: "YEAR TO DATE NORMAL INTEREST", type: "numeric", size: 16, format: "16,3. Decimal precision is currency dependent", description: "This field records the regular interest accrued throughout the current financial year." },
    { name: "previousYtd", label: "PREVIOUS YEAR TO DATE INTEREST", type: "numeric", size: 16, format: "16,3. Decimal precision is currency dependent", description: "This field stores the interest accumulated in the previous financial year for comparison and reporting." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default acrcal
