// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const ank0dataBR: SchemaTable = {
  name: "ank0dataBR",
  description: "This table contains range configuration information for bank branches Each entry includes a unique Branch code that identifies a specific branch within a financial institution.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field maintains a 4 digit branch\nnumber, defined by the financial institution,\nwhich is unique for each branch within the\nIMD number." },
    { name: "branchName", label: "BANCH NAME", type: "string", size: 30, description: "This field holds the branch’s name in English." },
    { name: "catagory", label: "BRANCH CATEGORY", type: "string", size: 3, description: "This field stores the classification of the branch" },
    { name: "branchLngInd", label: "BRANCH LANGUAGE INDICATOR", type: "string", size: 1, description: "This field maintains the preferred language setting associated with the branch." },
    { name: "currentRangeBeg", label: "CURRENT STARTING NUMBER", type: "numeric", size: 7, description: "This field stores the starting number of the defined customer range." },
    { name: "currentRangeEnd", label: "CURRENT ENDING NUMBER", type: "numeric", size: 7, description: "This field holds the final number of the customer range." },
    { name: "nextRangeBeg", label: "NEXT RANGE STARTING NUMBER", type: "numeric", size: 7, description: "This field stores the initial number of the defined next cutomer range from ." },
    { name: "nextRangeEnd", label: "NEXT RANGE ENDING NUMBER", type: "numeric", size: 7, description: "This field holds the final number of the next customer range, marking its limit." },
    { name: "lastStarterNo", label: "LAST STARTER NUMBER", type: "numeric", size: 7, description: "This field stores the most recent starter cheque number ." },
    { name: "maximumStarter", label: "MAXIMUM STARTER NUMBER", type: "numeric", size: 3, description: "This field maintains the highest possible starter cheque book can be issued." },
    { name: "transitCode", label: "TRANSIT CODE", type: "string", size: 2, description: "This field stores the identifier of the Transit code of the current Branch." },
    { name: "mainBrCode", label: "MAIN BRANCH CODE", type: "string", size: 4, description: "This field stores the identifier of the main branch overseeing operations." },
    { name: "accruedException", label: "ACCRUED EXCEPTION FLAG", type: "string", size: 1, description: "This field stores the indicator determining whether any accrued exceptions exist for the branch." },
    { name: "pseudoBranch", label: "PSUEDO BRANCH FLAG", type: "string", size: 1, description: "1-realBranch; 0-pseudoBranch" },
    { name: "regionCode", label: "REGION CODE", type: "string", size: 1, description: "This field maintains the geographical region associated with the cardholder.\nValid Values are :\n1-Central\n2-West\n3-East" },
    { name: "branchCategory", label: "BRANCH CATOGARY TYPE", type: "string", size: 1, description: "This field identifies whether the branch is a physical (real) or virtual (pseudo) entity Valid Values are :\n1- realBranch\n0- PseudoBranch\n2-Pseudo branch facing customer" },
    { name: "islamiBranch", label: "ISALMIC BRANCH", type: "string", size: 1, description: "This field identifies whether the branch is a ISALAMIC or not Valid Values are :\n0-No\n1-Yes" },
    { name: "areaCode", label: "AREA CODE", type: "string", size: 2, description: "This field stores the area code of Branch'" },
    { name: "finoneBranch", type: "string", size: 1 },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default ank0dataBR
