// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const ank0dataGW: SchemaTable = {
  name: "ank0dataGW",
  description: "This table defines the configuration settings for various gateway files, such as payroll, pension, and other financial gateways.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "gwNo", label: "GATEWAY NUMBER", type: "string", size: 4, keys: { k1: 2 }, description: "This field maintains the unique identifier assigned to the gateway transaction for processing." },
    { name: "payrollFlag", label: "PAYROLL PROCESSING INDICATOR", type: "string", size: 1, description: "This field records whether the gateway transaction is related to payroll processing." },
    { name: "blockingDays", label: "BLOCKING DAYS PERIOD", type: "string", size: 2, description: "This field stores the number of days during which the gateway transaction remains restricted or blocked." },
    { name: "pensionGwFlag", label: "PENSION GATEWAY INDICATOR", type: "string", size: 1, description: "This field maintains whether the gateway transaction pertains to pension related processes." },
    { name: "suspenseAccNo", label: "SUSPENSE ACCOUNT NUMBER", type: "string", size: 14, description: "This field maintains the specific sub account where the suspense transaction is tracked." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default ank0dataGW
