// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const ard0data: SchemaTable = {
  name: "ard0data",
  description: "This table contains loan repayments details of both due and paid amount in terms of principal, interst, penalty .",
  status: "Table modified",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2, k3: 2 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2, k2: 1 }, description: "This field stores thebranch code where the account belongs." },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 3, k3: 1 }, description: "Account number which is formed as below:\nCCMMMNNNNNNNSS\nDIGITS DESCRIPTION\n1-2 Currency Reference (CC).\n3-5 Memorandum Account Reference(MMM).\n6-12 Customer or Ledger Account Reference (NNNNNNN).\n13-14 Sub-account Reference (SS)" },
    { name: "repaymentDate", label: "SCHEDULED REPAYMENT DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the repayment date for loan repayment" },
    { name: "arrearAccNo", label: "ARREARS ACCOUNT NUMBER", type: "string", size: 14, description: "This field maintains the account where overdue payments and penalties are tracked." },
    { name: "settlementAccNo", label: "SETTLEMENT ACCOUNT NUMBER", type: "string", size: 14, description: "This field records the designated account where repayments are processed." },
    { name: "repaymentAmt", label: "REPAYMENT AMOUNT DUE", type: "numeric", size: 16, format: "16,3", description: "This field maintains the due repayment amount so far" },
    { name: "repaymentAmtPaid", label: "AMOUNT PAID TOWARDS REPAYMENT", type: "numeric", size: 16, format: "16,3", description: "This field records the portion of the repayment amount that has already been settled." },
    { name: "principalAmt", label: "PRINCIPAL AMOUNT DUE", type: "numeric", size: 16, format: "16,3", description: "This field contains the principal amount due so far." },
    { name: "principalAmtPaid", label: "PAID PRINCIPAL AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field stores the portion of the principal loan amount that has been repaid so far." },
    { name: "accruedInt", label: "ACCRUED INTEREST AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field maintains the total interest accumulated on the loan." },
    { name: "accruedIntPaid", label: "PAID ACCRUED INTEREST", type: "numeric", size: 16, format: "16,3", description: "This field records the portion of accrued interest that has been paid." },
    { name: "penaltyAccruedInt", label: "PENALTY ACCURED INTEREST", type: "numeric", size: 16, format: "16,3", description: "This field maintains the calculated penalty interest amount" },
    { name: "penaltyAccruedIntPaid", label: "PAID PENALTY INTEREST", type: "numeric", size: 16, format: "16,3", description: "This field maintains the penalty interest amount that has already been settled." },
    { name: "penaltyIntRate", label: "PENALTY INTEREST RATE", type: "numeric", size: 9, format: "9,6", description: "This field records the interest rate applied to overdue repayments." },
    { name: "penaltyIntAccrualDate", label: "PENALTY INTEREST ACCRUAL DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date when penalty interest started accruing on overdue balances." },
    { name: "repaymentStatus", label: "CURRENT REPAYMENT STATUS", type: "string", size: 2, description: "This field stores the status of the repayment (e.g., pending, completed, overdue)." },
    { name: "repaymentStatusDate", label: "STATUS UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date when the repayment status was last updated." },
    { name: "repaymentSettlementDate", label: "FINAL REPAYMENT SETTLEMENT DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the repayment was fully settled and cleared." },
    { name: "repayBal", label: "REPAYMENT BALANCE", type: "numeric", size: 16, format: "16,3", description: "This field records the balance when the repayment was fully settled and cleared.", note: "Added column on 04/08/2025" },
    { name: "intRate", label: "INTEREST RATE", type: "numeric", size: 9, format: "9,6", description: "This field records the rate of interest", note: "Added column on 04/08/2025" },
    { name: "date", label: "DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field has date with no esidata param to define it", note: "Added column on 04/08/2025" },
    { name: "migrationFlag", label: "MIGRATION STATUS FLAG", type: "string", size: 1, description: "This field stores an indicator specifying whether the repayment record has been migrated from a previous system." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default ard0data
