// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const bcd0data: SchemaTable = {
  name: "bcd0data",
  description: "BM Branch configuration with Clearing contra account .This file contains sort code records which uniquely identify each branch within a bank or financialinstitution.",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "bankSortCode", label: "BANKSHORT CODE NUMBER (KEY)", type: "string", size: 10, keys: { k1: 2 }, description: "This field maintains the branch sort code" },
    { name: "bankName", label: "DESCRIPTION", type: "string", size: 40, description: "This field maintains the name of the bank\n(as it is to be displayed by the posting\nprogram)." },
    { name: "clearContraAcctNum", label: "CLEARING CONTRA ACCOUNT NUMBER", type: "string", size: 14, description: "This field maintains the account number\n(excluding currency digits) of the clearing\naccount for the bank." },
    { name: "isoCountryCode", label: "ISO COUNTRY CODE", type: "string", size: 3, description: "This field maintains the 3 digit country\ncode in which the branch represented by\nthis sort code is located." },
    { name: "isoImdCode", label: "IMD NUMBER OF BANK/BRANCH", type: "string", size: 6, description: "This field maintains the six digit\nInterchange Member Designation allocated\nto the financial institution to which the\nbranch belongs." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field maintains a 4 digit branch\nnumber, defined by the financial institution,\nwhich is unique for each branch within the\nIMD number." },
    { name: "commissionAcctNum", label: "COMMISSION ACCOUNT", type: "string", size: 14, description: "This field maintains the account number\n(with no currency digits) to which all\ncommission postings for this branch are\nmade." },
    { name: "settlementAcctNum", label: "Settlement ACCOUNT", type: "string", size: 14, description: "This field maintains the account number\n(with no currency digits) to which all\nsettlement postings for this branch are\nmade.", note: "Field newly added on 21/10/2025" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default bcd0data
