// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const bmglsum: SchemaTable = {
  name: "bmglsum",
  description: "BThis table contains data related to financial extracts. Each entry outlines the necessary information of currency and Memo wise for generating financial reports.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 3, k3: 3 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2, k2: 2 }, description: "This field maintains the branch code where the accounts belong." },
    { name: "currCode", label: "CURRENCY CODE", type: "string", size: 2, keys: { k1: 3, k2: 1, k3: 1 }, description: "This field records the currency in which the GL balances are maintained." },
    { name: "ledgerCode", label: "LEDGER CODE", type: "string", size: 3, keys: { k1: 4, k3: 2 }, description: "This field stores the unique identifier assigned to the general ledger for financial tracking." },
    { name: "drClearedBal", label: "DEBIT CLEARED BALANCE", type: "numeric", size: 16, description: "This field maintains the total cleared debit balance within the ledger." },
    { name: "crClearedBal", label: "CREDIT CLEARED BALANCE", type: "numeric", size: 16, description: "This field records the total cleared credit balance in the ledger." },
    { name: "drBookBal", label: "DEBIT BOOK BALANCE", type: "numeric", size: 16, description: "This field stores the total debit book balance, reflecting transactions before clearance." },
    { name: "crBookBal", label: "CREDIT BOOK BALANCE", type: "numeric", size: 16, description: "This field maintains the total credit book balance, tracking unprocessed transactions." },
    { name: "noOfAccs", label: "TOTAL NUMBER OF ACCOUNTS", type: "numeric", size: 6, description: "This field records the number of accounts linked to this memo and branch." },
    { name: "transCrClearedBal", label: "TRANSACTION CREDIT CLEARED BALANCE", type: "numeric", size: 16, description: "This field stores the credit cleared balance specifically for transactional entries." },
    { name: "transDrClearedBal", label: "TRANSACTION DEBIT CLEARED BALANCE", type: "numeric", size: 16, description: "This field maintains the debit cleared balance related to transactional entries." },
    { name: "transCrBookBal", label: "TRANSACTION CREDIT BOOK BALANCE", type: "numeric", size: 16, description: "This field records the total credit book balance for unprocessed transaction entries." },
    { name: "transDrBookBal", label: "TRANSACTION DEBIT BOOK BALANCE", type: "numeric", size: 16, description: "This field stores the total debit book balance for unprocessed transaction entries." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
    { name: "NOTE: We select only DR (Detail Recod)" },
  ],
}

export default bmglsum
