// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const brcode: SchemaTable = {
  name: "brcode",
  description: "BM User ID and Branch code mapping.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "brShortCode", label: "BRANCH SHORT CODE", type: "string", size: 2, keys: { k1: 2 }, description: "This field stores the unique identifier code assigned to the customer's bank SHORT branchCODE." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field maintains a 4 digit branch\nnumber, defined by the financial institution,\nwhich is unique for each branch within the\nIMD number." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default brcode
