// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const bsf0data: SchemaTable = {
  name: "bsf0data",
  description: "Monthly Cumulative balances for FINANCE extracts at branch/balance sheet code level.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date", note: "K2,4" },
    { name: "recType", type: "string", size: 2, keys: { k1: 2 }, description: "Values BS, PL and CT", note: "K2,1" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 3 }, description: "This field maintains a 4 digit branch\nnumber" },
    { name: "bsCode", label: "BalanceSheet/ProfitAndLoss/Ledger", type: "string", size: 5, keys: { k1: 4 }, description: "Has Balance sheet code for BS record, Profilt and Loss code for PL record and Ledger code for CT records.", note: "K2,2" },
    { name: "indicator", label: "INDICATOR STATUS", type: "string", size: 1, keys: { k1: 5 }, description: "E and R for Balance sheet and L and R for P&L.", note: "K2,3" },
    { name: "sarBal", label: "CURRENT SAR BALANCE", type: "numeric", size: 16, description: "This field maintains the current SAR balance at branch and bsCode level" },
    { name: "fxBal", label: "CURRENT FX BALANCE", type: "numeric", size: 16, description: "This field maintains the current FX balance at branch and bsCode level" },
    { name: "currDate", label: "CURRENT DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date corresponding to the latest available balance data." },
    { name: "eomSarBal", label: "END OF MONTH SAR BALANCE", type: "numeric", size: 16, description: "This field maintains the end of month SAR balance at branch and bsCode level" },
    { name: "eomFxBal", label: "END OF MONTH FX BALANCE", type: "numeric", size: 16, description: "This field maintains the end of month FX balance at branch and bsCode level" },
    { name: "eomDate", label: "END OF MONTH RECORD DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date on which the end of month balance is finalized." },
    { name: "prevEomSarBal", label: "PREVIOUS MONTH SAR BALANCE", type: "numeric", size: 16, description: "This field maintains the previous month SAR balance at branch and bsCode level" },
    { name: "prevEomFxBal", label: "PREVIOUS MONTH CURRENT FX BALANCE", type: "numeric", size: 16, description: "This field maintains the previous month FX balance at branch and bsCode level" },
    { name: "prevEomDate", label: "PREVIOUS END OF MONTH RECORD DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date of the prior month's balance closure for reference." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default bsf0data
