// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const ctd0data: SchemaTable = {
  name: "ctd0data",
  description: "This table logs all outgoing and incoming credit transfer transactions. Each entry includes transaction reference number, customer ID, beneficiary details , transfer amount, currency, value date, and payment purpose code. Additional fields may capture initiating account number, channel of initiation , intermediary bank details , charges type , and transaction status Audit attributes such as timestamp, initiating user/system, and authorization trail may also be included.",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "creditTransferCode", label: "Credit Transfer Code", type: "date", size: 2, keys: { k1: 2 }, description: "Unique identifier for a specific type of credit transfer or transaction instruction.", note: "Data type converted from Date to String 22/07/2025" },
    { name: "payerAcctNum", label: "Payer Account Number", type: "string", size: 14, description: "The account number of the individual or entity initiating the payment.", note: "Length is changed from 13 to 14 on 09/10/2025" },
    { name: "payerName1", label: "Payer Name Line 1", type: "string", size: 30, description: "Primary name or first line of the payer’s name." },
    { name: "payerName2", label: "Payer Name Line 2", type: "string", size: 30, description: "Additional details or second line of the payer's name" },
    { name: "particulars1", label: "Particulars Line 1", type: "string", size: 25, description: "Custom reference or detail for the transfer, often for internal use.", note: "Data type was Missing added on 16/07/2025" },
    { name: "particulars2", label: "Particulars Line 2", type: "string", size: 25, description: "Additional reference information,", note: "Data type was Missing added on 16/07/2025" },
    { name: "particulars3", label: "Particulars Line 3", type: "string", size: 25, description: "Further elaboration", note: "Data type was Missing added on 16/07/2025" },
    { name: "payeeBankName", label: "Payee Bank Name", type: "string", size: 40, description: "The name of the receiving bank where funds will be sent." },
    { name: "payeeBankcode", label: "Payee Bank Code", type: "string", size: 10, description: "Bank identifier" },
    { name: "payeeAcctNum", label: "Payee Account Number", type: "string", size: 13, description: "The account number of the recipient of the funds." },
    { name: "payeeName1", label: "Payee Name Line 1", type: "numeric", size: 30, description: "Primary name or first line of the recipient’s name.", note: "Data type converted from Date to String 22/07/2025" },
    { name: "payeeName2", label: "Payee Name Line 2", type: "string", size: 30, description: "Additional details or second line of the payee's name" },
    { name: "paymentAmt", label: "Payment Amount", type: "string", size: 14, description: "The amount of money to be transferred, including currency precision." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default ctd0data
