// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const dcd0data: SchemaTable = {
  name: "dcd0data",
  description: "Calander file holds working day, day of week, week of year and day of year.This file contains a record of each working and non-working day in the year.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "date", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2 }, description: "4 YEAR NUMBER\nThis field contains the year number (YY)\npart of the specified date.\n2 MONTHNUMBER\nThis field contains the month number (MM)\npart of the specified date.\n2 DAYNUMBER\nThis field contains the day number (DD)\npart of the specified date." },
    { name: "workingDay", label: "WORKING DAY INDICATOR", type: "string", size: 1, description: "This field indicates whether the date relates\ntoa working day. Valid values arc:\n0 Non-working day.\n1 Working day." },
    { name: "dayOfWeek", label: "DAY OF WEEK NUMBER", type: "string", size: 1, description: "This field maintains the number of the day\nin the week.\nValid values are: 1-7." },
    { name: "weekOfYear", label: "WEEK OF YEAR NUMBER", type: "string", size: 2, description: "This field maintains the number of the week\nin the year.\nValid values are: 1-52." },
    { name: "dayOfYear", label: "JULIAN DAY OF YEAR", type: "numeric", size: 3, description: "This field maintains the number of the day\nin the Julian Calendar year.\nValid values are: 1-365 (366 on aleap\nyear)." },
    { name: "recType", label: "RECORD TYPE", type: "string", size: 2 },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default dcd0data
