// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const isd0data: SchemaTable = {
  name: "isd0data",
  description: "Has the link between ISO Currency code/BM currency code /country code (Picked from BM DD)-\nThis file contains the ISO standard codes for each country. These codes are set up by ACT Kindle and the only field which the user should change is the 'BANKMASTER CURRENCY CODE’ field, so that the Gateway willbe able to relate the Branchpower currency to the Bankmaster currency,",
  status: "Table modified",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "isoNumericCountryCode", label: "COUNTRY CODE NUMBER", type: "numeric", size: 3, keys: { k1: 2 }, description: "This field contains the ISO numeric country\ncode of the country that this record\nrepresents. The codes used are given in the\nISO standard number ISO 3166." },
    { name: "isoCurrCode", label: "CURRENCY CODE NUMBER", type: "string", size: 3, keys: { k1: 3, k2: 1 }, description: "This field contains the ISO numeric\ncurrency code of the country that this\nrecord represents. The codes used are given\nin the 150 document number 1SO 4217." },
    { name: "countryName", label: "COUNTRY NAME", type: "string", size: 30, description: "This field contains the standard name of the country." },
    { name: "currName", label: "CURRENCY DESCRIPTION", type: "string", size: 30, description: "This field contains the name of the currency." },
    { name: "bmCurrCode", label: "BANKMASTER CURRENCY CODE", type: "string", size: 2, description: "This field contains the Bankmaster currency code for this currency, as defined by the XRATE parameter file.\nNOTE: This is the only field that can be updated on this parameter file." },
    { name: "alphaIsoCurrCode", label: "CURRENCY CODE", type: "string", size: 3, description: "This field contains the ISO three character currency code." },
    { name: "twoCharCountryCode", label: "TWO CHARACTER COUNTRY CODE", type: "string", size: 2, description: "This field contains the ISO two character country code." },
    { name: "isoAlphaCountryCode", label: "COUNTRY CODE", type: "string", size: 3, description: "This field contains the ISO three character country code." },
    { name: "noOfDecimal", label: "NUMBER OF DECIMALS", type: "numeric", size: 1, description: "This field contains the number of digits in this currency after the decimal point." },
    { name: "countryDescription", label: "COUNTRY DESCRIPTION", type: "string", size: 40, description: "This field contains the full descriptive name Of the country. It may be different to the ’COUNTRY NAME’ field" },
    { name: "multipleCurrUsed", label: "Multiple Currency Used Flag", type: "string", size: 1, description: "This field contains the Multiple Currency Used Flag", note: "Field newly added on 22/07/2025" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default isd0data
