// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const letter: SchemaTable = {
  name: "letter",
  description: "Details about Letters issued to customers-.\nThis table maintains details of official letters and communications issued to customers by the financial institution. Each entry includes attributes such as letter type , issue date, customer ID, delivery method , and reference number.",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "dateGenerated", label: "DATE & TIME", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2 }, description: "This field holds the date and time of Letter is generated" },
    { name: "letterType", label: "LETTER TYPE", type: "string", size: 4, keys: { k1: 3 }, description: "STMT - Statement\nCARD - ATM Card\nWELC - Welcome\nSAMA - SAMA\nPENS - Pensioner's notification letter\nTDAV - Time Deposit Advice letter" },
    { name: "seqNo", label: "SEQUENENCE NUMBER", type: "numeric", size: 7, keys: { k1: 4 }, description: "This field holds the sequence Number" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field stores the unique identifier of the branch where the letter is initiated or processed." },
    { name: "address1", label: "ADDRESS LINE 1", type: "string", size: 30, description: "This field stores additional address details on which letter is to be sent" },
    { name: "poBox", label: "P.O. BOX NUMBER", type: "string", size: 10, description: "This field maintains the P.O. Box number linked to the customer." },
    { name: "cityName", label: "CITY NAME", type: "string", size: 20, description: "This field stores the name of the customer's city." },
    { name: "zipCode", label: "POSTAL CODE", type: "string", size: 10, description: "This field maintains the postal or zip code for the customer’s address." },
    { name: "returnedDate", label: "RETURNED DATE", type: "date", size: 8, format: "YYYYMMDD", description: "Letter returned date" },
    { name: "registeredUser", label: "REGIDTERED USER", type: "string", size: 10, description: "User who registered the letter" },
    { name: "registeredBranch", label: "REGIDTERED BRANCH", type: "string", size: 4, description: "Branch where registered theletter" },
    { name: "addressType", label: "ADDRESS TYPE", type: "string", size: 1, description: "This field specifies whether the customer's address is Types\nValid Values are :\n0-PO Box\n1-Saudi Post" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 8, description: "This field maintains the unique identification number assigned to the customer." },
    { name: "productId", type: "string", size: 20 },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default letter
