// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const pyd0data: SchemaTable = {
  name: "pyd0data",
  description: "Stopped Cheque file.",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2, k3: 2 }, description: "Data Restored date" },
    { name: "recType", label: "RECORD TYPE", type: "string", size: 2, keys: { k1: 2 }, description: "CH- Stopped Cheque/SP-Stopped Payment" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 3, k2: 1 }, description: "Bankmaster account number" },
    { name: "chequeNo", label: "CHEQUE NUMBER / STOP PAYMENT REF NUMBER", type: "string", size: 8, keys: { k1: 4, k3: 1 }, description: "Has the cheque number for CH records and stop payment reference for SP records.", note: "Changed Data Type from Number to String fron 31/7/2025" },
    { name: "amount", label: "AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field maintains the amount of the transaction. Decimal places are currency dependent." },
    { name: "dateStop", label: "STOP REQUEST DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date on which the cheque stoppage/stop payment was requested." },
    { name: "payeeName", label: "PAYEE NAME", type: "string", size: 25, description: "This field contains the Payee Name" },
    { name: "chequeFrom", label: "CHEQUE NUMBER FROM", type: "string", size: 8, description: "This field contains the unique cheque number that has been requested for stoppage. It is used only for CH records.", note: "Changed Data Type from Number to String fron 31/7/2025" },
    { name: "destroyFlag", label: "CHEQUE DESTRUCTION STATUS", type: "string", size: 1, description: "This field maintains whether the stopped cheque has been physically destroyed or retained. Only for CH records." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default pyd0data
