// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const shd0data: SchemaTable = {
  name: "shd0data",
  description: "Loan repayment data.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "Branch code of the customer" },
    { name: "ledgerCode", label: "LEDGER CODE", type: "string", size: 3, keys: { k1: 2 }, description: "This field stores the unique identifier for the financial ledger associated with the loan account." },
    { name: "finLoanNo", label: "FINONE LOAN NUMBER", type: "string", size: 8, keys: { k1: 3, k2: 1 }, description: "FINONE Loan number" },
    { name: "repaymentDate", label: "LOAN REPAYMENT DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 4 }, description: "This field records the scheduled date for loan repayment." },
    { name: "loanStatus", label: "LOAN STATUS", type: "string", size: 1, description: "This field maintains the current operational status of the loan\n0-Outstanding\n1-Processed on Maturity\n2-Deleted & not reconciled\n3-Refinanced\n4-Early setteled\n5-Modified\n6-Written-off\n7-Topped-up\n8-Resheduled" },
    { name: "currency", label: "LOAN CURRENCY", type: "string", size: 2, description: "This field stores the currency type in which the loan is processed and repaid." },
    { name: "statusDate", label: "STATUS UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field contains the most recent date when the loan status was updated." },
    { name: "loanStartDate", label: "LOAN START DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date on which the loan agreement commenced." },
    { name: "maturityDate", label: "LOAN MATURITY DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the expected date when the loan term concludes." },
    { name: "processDate", label: "LOAN PROCESSING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date on which the loan transaction was processed in the system." },
    { name: "repaymentAmt", label: "LOAN REPAYMENT AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field contains the total monetary value required for repayment on the scheduled date." },
    { name: "fundingRate", label: "LOAN FUNDING INTEREST RATE", type: "numeric", size: 9, format: "9,3", description: "This field records the applied interest rate on the funded loan amount." },
    { name: "fundingIntAmt", label: "FUNDED INTEREST AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field stores the calculated interest amount based on the loan funding rate." },
    { name: "reconStatus", label: "LOAN RECONCILIATION STATUS", type: "string", size: 1, description: "This field maintains whether the loan records have been reconciled and verified for accuracy.\n0-Outstanding\n2-Deleted & not reconciled" },
    { name: "blockedAmt", label: "BLOCK BALANCE (REDEFINED FIELD)", type: "numeric", size: 16, format: "16,3", description: "This field maintains the amount in the\ncleared balance which has not yet been\ncleared. This is used to accrue interest on\nuncleared items.\nDecimal places are currency dependent." },
    { name: "emi", label: "EMI AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field maintains the installmanets amount.\nDecimal places are currency dependent." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default shd0data
