// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const srvfeelog: SchemaTable = {
  name: "srvfeelog",
  description: "This table has the fees collected for Minimum balance, ATM fee, monthly and service fee.",
  status: "Table modified",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2, k2: 1 }, description: "Data Restored date" },
    { name: "feeType", label: "FEE TYPE", type: "string", size: 2, keys: { k2: 2 }, description: "SF- Service Fee\nMI-Minimum balance fee\nMF-Monthly Fee\nAF-ATM Fee" },
    { name: "feeTxnBankingDate", label: "FEE TRANSACTION BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k2: 3 }, description: "Fee Transaction Banking Date", note: "Column Newly Added on 28/07/2025" },
    { name: "serviceBranchCode", label: "SERVICE BRANCH CODE", type: "string", size: 4, keys: { k2: 4 }, description: "This field stores the unique identifier of the branch where the service fee transaction is initiated or processed." },
    { name: "serviceNo", label: "SERVICE NUMBER", type: "string", size: 2, description: "This field maintains the unique reference number assigned to the specific service provided." },
    { name: "branchOrDelivery", label: "BRANCH OR DELIVERY MODE", type: "string", size: 1, description: "This field defines whether the service was conducted at the branch or delivered remotely.0 - Branch; 1- Delivery Channel" },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field records the branch associated with the customer receiving the service." },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 16, keys: { k1: 1 }, description: "This field contains the unique account number linked to the service fee transaction." },
    { name: "normalFeeAmt", label: "STANDARD SERVICE FEE AMOUNT", type: "numeric", size: 10, format: "10,2", description: "This field stores the predefined fee applicable to the requested service.", note: "precision Information Added on 29/07/2025" },
    { name: "chargebleAmt", label: "CHARGEABLE AMOUNT", type: "numeric", size: 10, format: "10,2", description: "This field maintains the amount that is eligible for charging based on service conditions.", note: "precision Information Added on 29/07/2025" },
    { name: "chargedAmt", label: "ACTUAL CHARGED AMOUNT", type: "numeric", size: 10, format: "10,2", description: "This field records the final amount deducted or charged to the customer’s account.", note: "precision Information Added on 29/07/2025" },
    { name: "chargedCategory", label: "CHARGED CATEGORY TYPE", type: "string", size: 2, description: "This field defines the category under which the fee is charged" },
    { name: "chargedType", label: "CHARGE TYPE", type: "string", size: 1, description: "This field stores the classification of the charge applied0-Excluded; 1-Fully charged; 2- Partially charged; 3-NoFund; 4-Manual" },
    { name: "remarks", label: "TRANSACTION REMARKS", type: "string", size: 50, description: "This field maintains any relevant notes or comments related to the service fee processing." },
    { name: "contraAccNo", label: "CONTRA ACCOUNT NUMBER", type: "string", size: 14, description: "This field records the corresponding account used for balancing the service fee transaction." },
    { name: "transAmt", label: "TRANSACTION AMOUNT", type: "numeric", size: 14, description: "This field contains the total amount involved in the service fee process." },
    { name: "orgRefNo", label: "ORIGINAL REFERENCE NUMBER", type: "string", size: 10, description: "This field stores the reference ID linked to the original transaction or request." },
    { name: "thisRunDate", label: "TRANSACTION RUN DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date when the service fee transaction was executed in the system." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default srvfeelog
