// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const staccblk: SchemaTable = {
  name: "staccblk",
  description: "Contains details about the arrear amount blocked for credit card payment",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2 }, description: "Data Restored date" },
    { name: "bmAccNo", label: "BANK ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 1 }, description: "This field stores the unique account number associated with the customer's bank account." },
    { name: "blockedAmt", label: "BLOCKED AMOUNT", type: "string", size: 14, description: "This field maintains the amount that has been blocked or restricted from use in the customer’s account." },
    { name: "blockedBmDate", label: "BLOCKED AMOUNT DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k2: 1 }, description: "This field records the date on which the amount was blocked in the bank account." },
    { name: "requestUserId", label: "REQUESTING USER ID", type: "string", size: 10, description: "This field stores the ID of the user who initiated the blocking request." },
    { name: "requestBranch", label: "REQUESTING BRANCH", type: "string", size: 4, description: "This field identifies the branch from which the blocking request originated." },
    { name: "lastBlockedUserId", label: "LAST BLOCKING USER ID", type: "string", size: 10, description: "This field holds the ID of the user who most recently modified or blocked the amount in the account." },
    { name: "lastBlockedDateTime", label: "LAST BLOCKED DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp of the latest blocking action applied to the account." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default staccblk
