// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const staddrlog: SchemaTable = {
  name: "staddrlog",
  description: "This table captures audit trail entries for any modifications made to customer address information. Each entry includes customer number, type of address changed , previous and updated address values, date and time of the change, and the user or system responsible for the update.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field Maintain in Which Branch code from where customer details are modified" },
    { name: "userId", label: "USER ID", type: "string", size: 10, keys: { k1: 3 }, description: "This field stores the ID of the user who last updated the record." },
    { name: "dateTime", label: "DATE TIME", type: "timestamp", size: 14, format: "YYYYMMDDHHH24MISS", keys: { k1: 4 }, description: "This field stores the DATE TIME of the last updated the record." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the record is new or has been updated." },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 5, k2: 1 }, description: "This field maintains the customer\nnumber which can be used to access the\ncustomer via enquiries." },
    { name: "addressType", label: "ADDRESS TYPE", type: "string", size: 2, keys: { k1: 6, k2: 2 }, description: "Valid Values are:\n00 - Customer main/local address\n01 - Customer abroad address\n02 - Reference address\n03 - Owner local address\n04 - Owner abroad address\n05 - Heirs Address" },
    { name: "addressNo", label: "ADDRESS NUMBER", type: "string", size: 4, keys: { k1: 7, k2: 3 }, description: "This field maintains the unique address number associated with the customer.\nValid values are\n0000 - Customer main/local address -Always used for the 1st account holder\n0001 - 1st business owner / stakeholder / heir -Used when there are additional parties\n0002 - 2nd business owner / stakeholder / heir -Assigned sequentially\n0003 - 3rd associated entity -Continues as needed\n0..n - N-th associated party -Scalable to any number of linked persons" },
    { name: "bmUpdateStatus", label: "BANK MASTER UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "address1", label: "CUSTOMERADDRESS - LINE 1", type: "string", size: 30, description: "This field maintains the first line of the customer's address." },
    { name: "address2", label: "CUSTOMERADDRESS - LINE 2", type: "string", size: 30, description: "This field maintains the second line of the customer's address." },
    { name: "poBox", label: "P.O. BOX NUMBER", type: "string", size: 10, description: "This field maintains the P.O. Box number linked to the customer." },
    { name: "cityName", label: "CITY NAME", type: "string", size: 20, description: "This field stores the name of the customer's city." },
    { name: "zipCode", label: "POSTAL CODE", type: "string", size: 10, description: "This field maintains the postal or zip code for the customer’s address." },
    { name: "country", label: "COUNTRY NAME", type: "string", size: 3, description: "This field stores the name of the country where the customer resides." },
    { name: "telOffAreaCode", label: "OFFICE PHONE AREA CODE", type: "string", size: 4, description: "This field holds the area code for the customer’s office phone number." },
    { name: "telOffNo", label: "OFFICE PHONE NUMBER", type: "string", size: 10, description: "This field maintains the office telephone number of the customer." },
    { name: "telOffExt", label: "OFFICE PHONE EXTENSION", type: "string", size: 4, description: "This field holds the extension number for the customer’s office telephone." },
    { name: "telHomeAreaCode", label: "HOME PHONE AREA CODE", type: "string", size: 4, description: "This field stores the area code for the customer’s home phone number." },
    { name: "telHomeNo", label: "HOME PHONE NUMBER", type: "string", size: 10, description: "This field maintains the home telephone number of the customer." },
    { name: "telHomeExt", label: "HOME PHONE EXTENSION", type: "string", size: 4, description: "This field holds the extension number for the customer’s home telephone." },
    { name: "faxAreaCode", label: "FAX AREA CODE", type: "string", size: 4, description: "This field stores the area code for the customer's fax number." },
    { name: "faxNo", label: "FAX NUMBER", type: "string", size: 10, description: "This field maintains the fax number of the customer." },
    { name: "faxExt", label: "FAX EXTENSION", type: "string", size: 4, description: "This field holds the extension number for the customer’s fax." },
    { name: "mobileNo", label: "MOBILE PHONE NUMBER", type: "string", size: 10, description: "This field maintains the customer’s mobile phone number." },
    { name: "pagerNo", label: "PAGER NUMBER", type: "string", size: 10, description: "This field stores the pager number associated with the customer." },
    { name: "eMail", label: "EMAIL ADDRESS", type: "string", size: 30, description: "This field maintains the customer's email address for communication." },
    { name: "lastUpdateBmDate", label: "LAST UPDATED DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field holds the date of the last update made to the customer’s records." },
    { name: "recordChanged", label: "RECORD CHANGE STATUS", type: "string", size: 1, description: "This field indicates whether the customer address record has been modified. It helps track updates and ensures the most recent information is maintained in the system." },
    { name: "addrType", label: "ADDRESS TYPE", type: "string", size: 1, description: "This field stores the type of address Valid Values are: 0-PO Box;1-Saudi Post" },
    { name: "gprsNo", label: "GPRS NUMBER", type: "string", size: 8, description: "This field maintains the GPRS number associated with the customer. Applicable for Saudi postal address" },
    { name: "unitNo", label: "UNIT NUMBER", type: "string", size: 5, description: "This field stores the unit or apartment number of the customer’s address.Applicable for Saudi postal address" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the ID of the user who last updated the record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATED DATE TIME", type: "timestamp", size: 14, format: "YYYYMMDDHHH24MISS", description: "This field stores the DATE TIME of the last updated the record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default staddrlog
