// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stcaltab: SchemaTable = {
  name: "stcaltab",
  description: "This table provides a cross-reference between Hijri and Gregorian calendar dates.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 1 }, description: "Data Restored date" },
    { name: "gregDate", label: "GREGORIAN DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2 }, description: "This field stores the date in Gregorian calendar format, which is widely used internationally for standard date representation." },
    { name: "hijriDate", label: "HIJRI DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k2: 2 }, description: "This field maintains the date in Hijri (Islamic) calendar format, which is commonly used in Islamic countries for religious and cultural purposes." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stcaltab
