// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stcreftab: SchemaTable = {
  name: "stcreftab",
  description: "This table serves as the authoritative repository for customer representative identifiers used across internal and external systems. Each entry includes the customer ID, Custer type, reference value, source system, effective date, and current status (active/inactive).",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 2 }, description: "This field stores the unique identification number assigned to the customer in the reference system." },
    { name: "referenceNo", label: "REFERENCE NUMBER", type: "string", size: 4, keys: { k1: 3 }, description: "This field maintains the unique reference number assigned to the customer for verification purposes." },
    { name: "referenceReqdFor", label: "REFERENCE REQUIRED FOR", type: "string", size: 10, description: "This field specifies the purpose of the reference request.Reference for\n1 - Blind person\n2 - Veiled woman\n3 - Incompetent person\n4 - Minor\n5 - Minor with special circumstances\n6 - Mentally disabled" },
    { name: "referenceType", label: "REFERENCE TYPE", type: "string", size: 1, description: "This field categorizes the reference For 0-Personal Reference\n1-Legal reporesentative\n2-Foster parents\n3-Guardian" },
    { name: "aFirstName", label: "ARABIC FIRST NAME", type: "string", size: 15, description: "This field holds the customer's first name in Arabic." },
    { name: "aSecondName", label: "ARABIC SECOND NAME", type: "string", size: 15, description: "This field maintains the customer's second name in Arabic." },
    { name: "aThirdName", label: "ARABIC THIRD NAME", type: "string", size: 15, description: "This field stores the customer's third name in Arabic." },
    { name: "aLastName", label: "ARABIC LAST NAME", type: "string", size: 15, description: "This field holds the customer's last name in Arabic." },
    { name: "aShortName", label: "ARABIC SHORT NAME", type: "string", size: 30, description: "This field stores a short form version of the customer's Arabic name." },
    { name: "eFirstName", label: "ENGLISH FIRST NAME", type: "string", size: 15, description: "This field maintains the customer's first name in English." },
    { name: "eSecondName", label: "ENGLISH SECOND NAME", type: "string", size: 15, description: "This field stores the customer's second name in English." },
    { name: "eThirdName", label: "ENGLISH THIRD NAME", type: "string", size: 15, description: "This field holds the customer's third name in English." },
    { name: "eLastName", label: "ENGLISH LAST NAME", type: "string", size: 15, description: "This field records the customer's last name in English." },
    { name: "eShortName", label: "ENGLISH SHORT NAME", type: "string", size: 30, description: "This field maintains the customer's short form English name." },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, description: "This field specifies the type of identification used (e.g., I - Saudi ID ; Q - Iqama ; P - passport)." },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, description: "This field stores the unique identification number associated with the reference record." },
    { name: "activeStatus", label: "REFERENCE ACTIVE STATUS", type: "string", size: 1, description: "This field indicates whether the reference record is currently active or has been disabled." },
    { name: "disabledDate", label: "REFERENCE DISABLE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the reference was deactivated." },
    { name: "lastUpdateBmDate", label: "LAST UPDATED DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date when the reference record was last modified in the banking system." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field stores the unique identifier for the branch handling the reference record." },
    { name: "custOpenSource", label: "CUSTOMER OPEN SOURCE", type: "string", size: 1, description: "This field tracks the origin of the customer record creation .P-customer created through phone otherValue-created through branc" },
    { name: "createdUserId", label: "CREATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who initially created the reference record." },
    { name: "createdDateTime", label: "CREATION DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp of when the reference record was created in the system." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field holds the identifier of the user who last modified the reference record" },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the timestamp of the last modification to the reference record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stcreftab
