// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabBI: SchemaTable = {
  name: "stctltabBI",
  description: "Record Type :BI-Biller ID\nThis table maintains the authoritative list of unique identifiers assigned to registered billers within the financial institution's systems.",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "billerId", label: "BILLER IDENTIFIER", type: "string", size: 4, keys: { k1: 2 }, description: "This field maintains the unique identification number assigned to the biller." },
    { name: "arabicName", label: "BILLER NAME IN ARABIC", type: "string", size: 30, description: "This field stores the biller name in Arabic." },
    { name: "englishName", label: "BILLER NAME IN ENGLISH", type: "string", size: 30, description: "This field maintains the biller name in English." },
    { name: "transType", label: "TRANSACTION TYPE", type: "string", size: 2, description: "This field specifies the type of transactions allowed with the biller (e.g., payments, refunds, adjustments)." },
    { name: "contraAccNo", label: "CONTRA ACCOUNT NUMBER", type: "string", size: 14, description: "This field maintains the linked account number used for biller transactions." },
    { name: "checkDigitValidationOption", label: "CHECK DIGIT VALIDATION OPTION", type: "string", size: 1, description: "This field defines the validation method used for verifying transaction accuracy with the biller." },
    { name: "prepaymentAllowed", label: "PREPAYMENT ALLOWED STATUS", type: "string", size: 1, description: "This field indicates whether customers are permitted to prepay their bills.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "prepaymentTypesAllowed", label: "ALLOWED PREPAYMENT TYPES", type: "string", size: 20, description: "This field lists the prepayment options accepted by the biller 5 Types with 4 characters each" },
    { name: "postpaymentTypesAllowed", label: "ALLOWED POSTPAYMENT TYPES", type: "string", size: 20, description: "This field defines the postpayment methods supported by the biller.5 Types with 4 characters each" },
    { name: "arabicNarrative1", label: "BILLER DESCRIPTION IN ARABIC", type: "string", size: 25, description: "This field provides additional descriptive information about the biller in Arabic." },
    { name: "englishNarrative1", label: "BILLER DESCRIPTION IN ENGLISH", type: "string", size: 25, description: "This field provides additional descriptive information about the biller in English." },
    { name: "cashAccNo", label: "CASH ACCOUNT NUMBER", type: "string", size: 14, description: "This field stores the account number used for handling cash transactions with the biller." },
    { name: "serviceType", label: "SERVICE TYPE", type: "string", size: 4, description: "This field categorizes the services provided by the biller (e.g., utilities, telecom, government services)." },
    { name: "disableBillerIdFlag", label: "BILLER DISABLE STATUS FLAG", type: "string", size: 1, description: "This field indicates whether the biller is currently disabled or inactive.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the biller record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp of the most recent update to the biller record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
    { name: "reversalAllowedFlag", label: "TRANSACTION REVERSAL ALLOWED STATUS", type: "string", size: 1, description: "This field tracks whether reversals for biller related transactions are permitted.", note: "Removed Since it was not present on 31/07/2025" },
  ],
}

export default stctltabBI
