// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabCC: SchemaTable = {
  name: "stctltabCC",
  description: "Record Type :CC\nThis table captures standardized classification codes and descriptions defined by the Saudi Central Bank (SAMA) for regulatory reporting and operational alignment.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "samaMainCategory", label: "SAMA MAIN CATEGORY", type: "string", size: 2, keys: { k1: 2 }, description: "This field stores the primary classification of the customer or business under SAMA (Saudi Arabian Monetary Authority) regulations." },
    { name: "samaSubCategory", label: "SAMA SUB CATEGORY", type: "string", size: 2, keys: { k1: 3 }, description: "This field records the secondary classification of the customer or business under SAMA guidelines." },
    { name: "arabicShortDesc", label: "SHORT DESCRIPTION IN ARABIC", type: "string", size: 30, description: "This field provides a brief description of the category in Arabic." },
    { name: "englishShortDesc", label: "SHORT DESCRIPTION IN ENGLISH", type: "string", size: 30, description: "This field provides a brief description of the category in English." },
    { name: "firstLetterDue", label: "FIRST NOTICE DUE", type: "string", size: 3, description: "This field stores the due date for the first notification or compliance letter." },
    { name: "secondLetterDue", label: "SECOND NOTICE DUE", type: "string", size: 3, description: "This field maintains the due date for the second notification or follow up compliance letter." },
    { name: "thirdLetterDue", label: "THIRD NOTICE DUE", type: "string", size: 3, description: "This field tracks the due date for the third and final compliance notification." },
    { name: "crLicenseMandatory", label: "COMMERCIAL LICENSE REQUIREMENT", type: "string", size: 1, description: "This field specifies whether a commercial registration license is mandatory for this category.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "accStatusValueForFreeze", label: "ACCOUNT STATUS FOR FREEZE", type: "string", size: 1, description: "This field defines the account status that triggers freezing actions under compliance regulations." },
    { name: "accFreezingGracePeriod", label: "ACCOUNT FREEZING GRACE PERIOD", type: "string", size: 3, description: "This field tracks the allowed grace period before freezing the account due to inactivity or compliance requirements." },
    { name: "fundMovementPeriod", label: "FUND MOVEMENT MONITORING PERIOD", type: "string", size: 3, description: "This field stores the time frame within which fund movements are monitored for regulatory compliance." },
    { name: "fundMovementPeriodValidFlag", label: "FUND MOVEMENT VALIDATION FLAG", type: "string", size: 1, description: "This field indicates whether fund movement monitoring is currently valid for this category.\nValid Values are :\n0-Valid\n1-Invalid" },
    { name: "fundMovementApplicableFlag", label: "FUND MOVEMENT APPLICABILITY FLAG", type: "string", size: 1, description: "This field tracks whether fund movement rules apply to accounts under this category.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "reportExpiryOwnerId", label: "OWNER ID FOR EXPIRY REPORTING", type: "string", size: 1, description: "This field maintains the identifier for the owner responsible for expiry related reporting.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "samaApprovalReqd", label: "SAMA APPROVAL REQUIRED", type: "string", size: 1, description: "This field specifies whether transactions under this category require SAMA regulatory approval.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "allowNonSaudiSignatory", label: "NONSAUDI SIGNATORY PERMISSION", type: "string", size: 1, description: "This field tracks whether non Saudi individuals are allowed as signatories for accounts or contracts.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "mandatoryLicNo", label: "MANDATORY LICENSE NUMBER REQUIREMENT", type: "string", size: 1, description: "This field specifies whether a license number is a required field for entities in this category.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "allowOnlyResidentOperators", label: "RESIDENT OPERATORS RESTRICTION", type: "string", size: 1, description: "This field indicates if only resident individuals are allowed to operate accounts under this category.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "accOpeningAllowed", label: "ACCOUNT OPENING PERMISSION", type: "string", size: 1, description: "This field tracks whether new account openings are permitted for customers under this category.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "checkBookAllowed", label: "CHEQUE BOOK ISSUANCE PERMISSION", type: "string", size: 1, description: "This field specifies whether cheque books can be issued under this category.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "secondGracePeriodApplicable", label: "SECOND GRACE PERIOD APPLICABILITY", type: "string", size: 1, description: "This field determines whether a second grace period is applicable before compliance actions are enforced.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "idExpiryActionReqd", label: "ACTION REQUIRED ON ID EXPIRY", type: "string", size: 1, description: "This field tracks whether compliance actions must be taken when a customer’s ID expires.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "atmCardAllowed", label: "ATM CARD ISSUANCE PERMISSION", type: "string", size: 1, description: "This field specifies whether ATM cards can be issued under this category.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "generalCustOpenAllowed", label: "GENERAL CUSTOMER OPENING PERMISSION", type: "string", size: 1, description: "This field tracks whether general customers are allowed to open accounts under this category.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "reportToCompliance", label: "COMPLIANCE REPORTING REQUIRED", type: "string", size: 1, description: "This field defines whether accounts in this category require reporting to compliance departments.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "custUpdActionNotReqd", label: "CUSTOMER UPDATE ACTION NOT REQUIRED", type: "string", size: 1, description: "This field indicates whether updates to customer records are required or not.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "elapsedYears", label: "NUMBER OF YEARS ELAPSED", type: "string", size: 2, description: "This field tracks the elapsed years since the account or entity was registered under the category." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field stores the identifier of the user who last modified this category configuration." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp of the most recent modification of the category configuration record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabCC
