// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabXC: SchemaTable = {
  name: "stctltabXC",
  description: "Record Type :XC\nThis table maintains metadata for Currency Code ISO details",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "currCode", label: "CURRENCY CODE", type: "string", size: 2, keys: { k1: 2 }, description: "01-Saudi Riyal\n13-Austrian Shilling\n14-Moroccan Dirham\n15-Yemen Riyal\n16-Srilanka Rupees\n17-Belgian Francs\n18-Australian Dollar\n19-Canadian Dollar\n20-Malaysian Ringet\n21-Swedish Krona\n22-Pakistan Rupee\n23-Deutsche Mark\n24-Sudan Pound\n25-Netherlands Guilder\n26-Greece Derakhma\n27-Danish Krona\n29-Egyptian Pound\n30-Finnish Mark\n31-French Francs\n32-EUROPEAN CURRENCY UNIT\n33-New Zealand Dollar\n34-Irish Pound\n35-Italian Lira\n36-Indonesian Rupee\n37-South African Rand\n38-Nepal Rupee\n40-Iraqi Dinar\n41-Jordanian Dinar\n43-Japanese Yen\n45-Kuwaiti Dinar\n49-Norway Krona\n51-Lebanese Lira\n53-Qatari Riyal\n54-Arab Emirates Dirham\n58- RUTHENIUM\n59-Turkey Lira\n61-Swiss Francs\n62-Omani Riyal\n63-Serian Lira\n67-U.S. Dollar\n70-Bahraini Dinar\n75-Hong Kong Dollar\n80-Bangladesh\n84-British Pound\n85-Indian Rupees\n86-Spanish Peseta\n87-Leebian Dinar\n88-Algerian Dinar\n89-Singapore Dollar\n90-Thailand Pehita\n91-Cyprus Pound\n92-Tunisian Dinar\n93-Gold\n94-PLATINUM\n95-Silver" },
    { name: "arabicName", label: "CURRENCY NAME IN ARABIC", type: "string", size: 30, description: "Provides the name of the currency in Arabic ." },
    { name: "englishName", label: "CURRENCY NAME IN ENGLISH", type: "string", size: 30, description: "Records the name of the currency in English ." },
    { name: "isoCurrCode", label: "ISO CURRENCY CODE", type: "string", size: 3, description: "Stores the internationally recognized ISO 4217 code for the currency (e.g., USD for US Dollar, SAR for Saudi Riyal)." },
    { name: "decimalPlace", label: "DECIMAL PLACES USED", type: "string", size: 1, description: "Specifies the number of decimal places used for currency precision in foreign exchange transactions." },
    { name: "arabicShortCode", label: "SHORT CURRENCY CODE IN ARABIC", type: "string", size: 6, description: "Maintains the abbreviated version of the currency name in Arabic for documentation purposes." },
    { name: "fxTolerance", label: "FOREIGN EXCHANGE RATE TOLERANCE", type: "string", size: 1, description: "Defines the acceptable fluctuation range allowed in foreign exchange rate calculations." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "Stores the identifier of the user who last modified the title code details.", note: "Filed newly added on 06/08/2025" },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "Tracks the timestamp of the most recent modification made to the foreign exchange record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabXC
