// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabMM: SchemaTable = {
  name: "stctltabMM",
  description: "Record Type :MM\nThis table maintains metadata for all Memo Code",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "ledgerCode", label: "LEDGER CODE", type: "string", size: 3, keys: { k1: 2 }, description: "This field maintains the unique identifier associated with a specific ledger type." },
    { name: "arabicName", label: "LEDGER NAME IN ARABIC", type: "string", size: 30, description: "This field stores the name of the ledger type in Arabic for localization." },
    { name: "englishName", label: "LEDGER NAME IN ENGLISH", type: "string", size: 30, description: "This field records the name of the ledger type in English." },
    { name: "accCreationAllowed", label: "ACCOUNT CREATION PERMISSION", type: "string", size: 1, description: "This field specifies whether account creation is allowed under this ledger type.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "samaBlockingAcc", label: "SAMA BLOCKING ACCOUNT STATUS", type: "string", size: 1, description: "This field tracks whether SAMA (Saudi Arabian Monetary Authority) restrictions apply to accounts under this ledger type.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "obligationMemo", label: "OBLIGATION MEMO STATUS", type: "string", size: 1, description: "This field indicates whether obligation memos are required for accounts under this ledger type.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "tdDepositMemo", label: "TERM DEPOSIT MEMO REQUIREMENT", type: "string", size: 1, description: "This field tracks whether specific memos related to time deposits must be attached to accounts in this ledger.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "fdIntRateTolerance", label: "FIXED DEPOSIT INTEREST RATE TOLERANCE", type: "string", size: 1, description: "This field defines the acceptable range for interest rate variation in fixed deposits." },
    { name: "tdDebitMemo", label: "TERM DEPOSIT DEBIT MEMO REQUIREMENT", type: "string", size: 1, description: "This field indicates whether term deposit debit memos are required for transactions under this ledger type.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "minDepositAmt", label: "MINIMUM DEPOSIT AMOUNT", type: "numeric", size: 10, description: "This field stores the minimum amount required for deposits under this ledger type." },
    { name: "maxDepositPeriod", label: "MAXIMUM DEPOSIT PERIOD", type: "string", size: 1, description: "This field maintains the longest allowable period for deposits under this ledger type." },
    { name: "atmCardToBeIssued", label: "ATM CARD ISSUANCE STATUS", type: "string", size: 1, description: "This field specifies whether ATM cards can be issued under this ledger type." },
    { name: "fdValueDateTolerance", label: "FIXED DEPOSIT VALUE DATE TOLERANCE", type: "string", size: 3, description: "This field tracks the acceptable range of value date variations for fixed deposits." },
    { name: "tdRenewAllowed", label: "TIME DEPOSIT RENEWAL PERMISSION", type: "string", size: 1, description: "This field specifies whether time deposits can be renewed under this ledger type." },
    { name: "ignoreMemoForBrUpd", label: "IGNORE MEMO FOR BRANCH UPDATE STATUS", type: "string", size: 1, description: "This field indicates whether memos should be disregarded when branches update records in this ledger.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "chqBookReqAllowed", label: "CHEQUE BOOK REQUEST PERMISSION", type: "string", size: 1, description: "This field specifies whether cheque books can be requested under this ledger type.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "chqBookCode", label: "CHEQUE BOOK CODE", type: "string", size: 1, description: "This field maintains the unique identifier for cheque books issued under this ledger type." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field stores the identifier of the user who last modified the ledger type details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the most recent update made to the ledger record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabMM
