// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabNA: SchemaTable = {
  name: "stctltabNA",
  description: "Record Type :NA\nThis table maintains metadata for all Country Code and name in English and Arabic",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "countryCode", label: "COUNTRY CODE", type: "string", size: 3, keys: { k1: 2 }, description: "This field holds the unique identifier assigned to a country for classification and reference purposes." },
    { name: "arabicName", label: "COUNTRY NAME IN ARABIC", type: "string", size: 30, description: "This field stores the name of the country in Arabic for localization." },
    { name: "englishName", label: "COUNTRY NAME IN ENGLISH", type: "string", size: 30, description: "This field maintains the name of the country in English." },
    { name: "isoCode", label: "ISO COUNTRY CODE", type: "string", size: 3, description: "This field records the internationally recognized ISO code for the country (e.g., SA for Saudi Arabia, 084 for United States)." },
    { name: "gccCountry", label: "GCC COUNTRY STATUS", type: "string", size: 1, description: "This field specifies whether the country is part of the Gulf Cooperation Council (GCC).\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field stores the identifier of the user who last modified the country details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the most recent modification made to the country record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabNA
