// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabSR: SchemaTable = {
  name: "stctltabSR",
  description: "Record Type :SC\nThis table maintains metadata for Server Configuration",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "systemCode", label: "SYSTEM CODE", type: "string", size: 4, keys: { k1: 2 }, description: "SERV - Server configuration." },
    { name: "arabicShortDesc", label: "SHORT DESCRIPTION IN ARABIC", type: "string", size: 30, description: "Provides a brief description of the system configuration settings in Arabic for localization." },
    { name: "englishShortDesc", label: "SHORT DESCRIPTION IN ENGLISH", type: "string", size: 30, description: "Records a brief description of the system configuration settings in English ." },
    { name: "usrAccBlockingDays", label: "USER ACCOUNT BLOCKING DAYS", type: "string", size: 3, description: "Specifies the number of days before a user account is blocked due to inactivity or security reasons." },
    { name: "enableSadadProfile", label: "ENABLE SADAD PROFILE STATUS", type: "string", size: 1, description: "Indicates whether the SADAD payment profile is activated for system transactions. 1=>Yes ; 0=>No" },
    { name: "maxAgeLimit", label: "MAXIMUM AGE LIMIT", type: "string", size: 3, description: "Defines the upper age limit applied for certain system functionalities or customer eligibility." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "Stores the identifier of the user who last modified the system server configuration details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "Tracks the timestamp of the most recent modification made to the system server configuration record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabSR
