// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stheirlog: SchemaTable = {
  name: "stheirlog",
  description: "Audit on Heir/Proxy details maintenance.\nThis table captures changes made to heir or proxy designations linked to a customer's account or relationship profile. Each entry includes the customer ID, heir/proxy ID, type of relationship , legal heir, authorized representative, nature of update , previous and new values, effective date, timestamp of the change, and the user or system that performed the action.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 6, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch associated with the heir record." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user responsible for creating or updating the heir record." },
    { name: "dateTime", label: "DATE & TIME OF ACTION", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the timestamp marking the heir information entry or update." },
    { name: "newOrUpdate", label: "NEW OR UPDATED STATUS", type: "string", size: 1, description: "This field contains a flag indicating whether the record is newly created or modified." },
    { name: "bmUpdateStatus", label: "BANK MASTER UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 5, k2: 1 }, description: "This field stores the unique identifier of the customer associated with the heir." },
    { name: "heirNo", label: "HEIR NUMBER", type: "string", size: 4, keys: { k1: 6, k2: 2 }, description: "This field maintains the unique identifier assigned to the heir within the system." },
    { name: "heirType", label: "HEIR TYPE", type: "string", size: 1, description: "This field contains the classification of the heir (Valid Values are :\n0 - Heir\n1 - Proxy)" },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field stores the ID of the supervisor responsible for overseeing heir related processes." },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field maintains the branch code associated with the customer's account." },
    { name: "aFirstName", label: "ARABIC FIRST NAME", type: "string", size: 15, description: "This field stores the heir’s first name in Arabic ." },
    { name: "a2ndName", label: "ARABIC SECOND NAME", type: "string", size: 15, description: "This field maintains the heir’s second name in Arabic." },
    { name: "a3rdName", label: "ARABIC THIRD NAME", type: "string", size: 15, description: "This field contains the heir’s third name in Arabic." },
    { name: "aLastName", label: "ARABIC LAST NAME", type: "string", size: 15, description: "This field records the heir’s last name in Arabic for documentation." },
    { name: "aShortName", label: "ARABIC SHORT NAME", type: "string", size: 30, description: "This field stores the abbreviated version of the heir’s name in Arabic." },
    { name: "eFirstName", label: "ENGLISH FIRST NAME", type: "string", size: 15, description: "This field maintains the heir’s first name in English." },
    { name: "e2ndName", label: "ENGLISH SECOND NAME", type: "string", size: 15, description: "This field contains the heir’s second name in English." },
    { name: "e3rdName", label: "ENGLISH THIRD NAME", type: "string", size: 15, description: "This field records the heir’s third name in English." },
    { name: "eLastName", label: "ENGLISH LAST NAME", type: "string", size: 15, description: "This field stores the heir’s last name in English for documentation." },
    { name: "eShortName", label: "ENGLISH SHORT NAME", type: "string", size: 30, description: "This field maintains the heir’s short name for identification purposes." },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, description: "This field contains the type of ID associated with the heir (I - Saudi Id H - Hafiza P - Passport F-Family registration)." },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, description: "This field records the unique identification number assigned to the heir." },
    { name: "heirStatus", label: "HEIR STATUS", type: "string", size: 1, description: "This field stores the current status of the heir (e.g., 0-Invalid ; 1-Valid)." },
    { name: "heirDisableDate", label: "HEIR DISABLE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date when the heir status was disabled or marked inactive." },
    { name: "lastUpdateBmDate", label: "LAST BANK MASTER UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the latest date the BANK MASTER updated the heir information." },
    { name: "recordChanged", label: "RECORD CHANGE STATUS", type: "string", size: 1, description: "This field informs whether modifications have been made to the heir record." },
    { name: "custOpenSource", label: "CUSTOMER RECORD CREATION SOURCE", type: "string", size: 1, description: "This field stores the source through which the heir information was recorded( Valid values P-customer created through phone; OtherVialue-created through branch)" },
    { name: "proxyNo", label: "PROXY NUMBER", type: "string", size: 15, description: "This field maintains the unique identifier for any proxy assigned to the heir." },
    { name: "proxyDateType", label: "PROXY DATE FORMAT TYPE", type: "string", size: 1, description: "This field contains whether the proxy related dates are stored in Hijri or Gregorian format. (0-Hijri ; 1-Gregorian)" },
    { name: "proxyIssueDateH", label: "PROXY ISSUE DATE (HIJRI)", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the issuance date of the proxy in the Hijri calendar." },
    { name: "proxyIssueDateG", label: "PROXY ISSUE DATE (GREGORIAN)", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the issuance date of the proxy in the Gregorian calendar." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field maintains the identifier of the user who last modified the heir record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the most recent update to the heir information." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stheirlog
