// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stidlog: SchemaTable = {
  name: "stidlog",
  description: "Audit on ID details maintenance\nThis table tracks all updates made to customer identification information, ensuring transparency and compliance with KYC regulations. Each entry logs the customer ID, ID type (e.g., national ID, passport, residency permit), old and new ID values, issuing authority, country of issuance, expiration date changes (if any), timestamp of modification, and the user or system that performed the change. Optional fields may include reason codes for modification, source channel (branch, online, etc.), and verification status.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 6, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch associated with ID created /Updated" },
    { name: "userId", label: "USER ID", type: "string", size: 10, keys: { k1: 3 }, description: "This field stores the identifier of the user who created or modified the customer’s identification record." },
    { name: "dateTime", label: "DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field maintains the timestamp for when the identification record was created or modified ." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the customer record is newly created or has been modified. N - New ; U - Update" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k2: 1 }, description: "This field stores the unique identification number assigned to the customer." },
    { name: "bmUpdateStatus", label: "BANK MANAGEMENT UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, keys: { k1: 5, k3: 1 }, description: "This field specifies the type of identification used .Valid Values are :--\nI - Saudi ID\nQ - Iqama\nP - Passport\nH - Hafiza\nF - Family Registration\nC - CR NO\nS - Sama Authorization No\nV - Visa No\nT - Contract\nD - Diplomatic passport no\nL - License number\nM - Home country Id\nA - Approval Document Reference number\nE - Succession deed number" },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, keys: { k1: 6, k3: 2 }, description: "This field holds the unique number assigned to the customer based on the selected identification type." },
    { name: "idCategory", label: "IDENTIFICATION CATEGORY", type: "string", size: 1, description: "This field indicates the classification of the identification Valid Values are\nS-Signatory\nC-Customer\nW-oWner\nR-Reference\nJ-Joint\nH-Heirs" },
    { name: "idDateType", label: "IDENTIFICATION DATE TYPE", type: "string", size: 1, keys: { k1: 7 }, description: "This field specifies whether the identification dates are in Hijri or Gregorian format. 0 - Hijri ; 1 - Gregorian" },
    { name: "idIssuedAt", label: "IDENTIFICATION ISSUANCE LOCATION", type: "string", size: 20, description: "This field stores the location where the customer's identification document was officially issued. It helps in tracking the origin of the ID for verification and regulatory purposes." },
    { name: "idIssueDateH", label: "ISSUE DATE (HIJRI)", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the issuance date of the customer’s identification in Hijri format." },
    { name: "idIssueDateG", label: "ISSUE DATE (GREGORIAN)", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the issuance date of the customer’s identification in Gregorian format." },
    { name: "idExpiryDateH", label: "EXPIRY DATE (HIJRI)", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the expiration date of the customer's identification in Hijri format." },
    { name: "idExpiryDateG", label: "EXPIRY DATE (GREGORIAN)", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the expiration date of the customer's identification in Gregorian format." },
    { name: "lastUpdateBmDate", label: "LAST UPDATED DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the last update made to the customer’s identification information." },
    { name: "idExpiryActionNotReqd", label: "EXPIRY ACTION NOT REQUIRED", type: "string", size: 1, description: "This field indicates whether an action upon expiry is necessary. 0-No ; 1-Yes" },
    { name: "grace1ActionTaken", label: "FIRST GRACE PERIOD ACTION", type: "string", size: 1, description: "This field tracks the action taken during the first grace period after identification expiry.0-Not Taken ; 1 - Taken" },
    { name: "grace1ActionDate", label: "FIRST GRACE PERIOD ACTION DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the first grace period action was taken.Blank when the above flag is 0" },
    { name: "grace2ActionTaken", label: "SECOND GRACE PERIOD ACTION", type: "string", size: 1, description: "This field tracks the action taken during the second grace period after identification expiry.0-Not Taken ; 1 - Taken" },
    { name: "grace2ActionDate", label: "SECOND GRACE PERIOD ACTION DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the second grace period action was taken.Blank when the above flag is 0" },
    { name: "idRefNo", label: "IDENTIFICATION REFERENCE NUMBER", type: "string", size: 4, description: "This field stores the unique reference number linked to the customer's identification document. It helps in tracking and validating the customer's ID for compliance and verification purposes." },
    { name: "recordChanged", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the identification record is newly added or modified." },
    { name: "idRefName", label: "IDENTIFICATION REFERENCE NUMBER", type: "string", size: 30, description: "This field holds a reference number associated with the customer's identification. N - New ; U - Update" },
    { name: "iqamaType", label: "IDENTIFICATION REFERENCE NAME", type: "string", size: 1, description: "This field stores the name associated with the identification reference number." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field holds the identifier of the user who last modified the identification record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp for the last modification of the identification record" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stidlog
