// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stowntab: SchemaTable = {
  name: "stowntab",
  description: "Master file for Account ownership (Owner, Manager, Trustee, cashier)\nThis table serves as the centralized registry of all individuals and roles associated with account ownership and operational authority. Each entry includes account number, customer ID, role type , full name, identification details, role effective and expiry dates, and current status (active/inactive). Additional attributes may include authorization level, relationship to account owner, document references (e.g., legal mandates, power of attorney), and channel-specific access rights.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 2 }, description: "This field stores the unique identification number assigned to the customer." },
    { name: "ownerNo", label: "OWNER NUMBER", type: "string", size: 4, keys: { k1: 3 }, description: "This field maintains the unique identifier associated with the owner." },
    { name: "ownerType", label: "OWNER TYPE", type: "string", size: 1, description: "This field specifies the type of ownership.Valid\nvalues are:\nM-Manager\nT-Trustee\nC-Cashier\nW-Owners" },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, keys: { k2: 1 }, description: "This field indicates the type of identification used for the owner .alid\nvalues are:\nI - Saudi Id\nQ - Iqama\nC - CR Number\nF - Family Regn no\nH - Hafiza" },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, keys: { k2: 2 }, description: "This field holds the unique identification number assigned to the owner based on the selected identification type." },
    { name: "parentCompanyName", label: "PARENT COMPANY NAME", type: "string", size: 30, description: "This field stores the name of the parent company associated with the owner" },
    { name: "shareHoldingPerc", label: "SHAREHOLDING PERCENTAGE", type: "string", size: 3, description: "This field maintains the percentage of ownership the individual or entity holds within a business or organization." },
    { name: "aFirstName", label: "ARABIC FIRST NAME", type: "string", size: 15, description: "This field stores the first name of the owner in Arabic." },
    { name: "aSecondName", label: "ARABIC SECOND NAME", type: "string", size: 15, description: "This field stores the second name of the owner in Arabic." },
    { name: "aThirdName", label: "ARABIC THIRD NAME", type: "string", size: 15, description: "This field stores the third name of the owner in Arabic." },
    { name: "aLastName", label: "ARABIC LAST NAME", type: "string", size: 15, description: "This field stores the last name of the owner in Arabic." },
    { name: "aShortName", label: "ARABIC SHORT NAME", type: "string", size: 30, description: "This field holds a short form version of the owner's name in Arabic" },
    { name: "eFirstName", label: "ENGLISH FIRST NAME", type: "string", size: 15, description: "This field stores the first name of the owner in English." },
    { name: "eSecondName", label: "ENGLISH SECOND NAME", type: "string", size: 15, description: "This field stores the second name of the owner in English." },
    { name: "eThirdName", label: "ENGLISH THIRD NAME", type: "string", size: 15, description: "This field stores the third name of the owner in English." },
    { name: "eLastName", label: "ENGLISH LAST NAME", type: "string", size: 15, description: "This field stores the last name of the owner in English." },
    { name: "eShortName", label: "ENGLISH SHORT NAME", type: "string", size: 30, description: "This field maintains the shortened form of the owner's name in English" },
    { name: "ownerEnabled", label: "OWNER STATUS", type: "string", size: 1, description: "This field indicates whether the owner's record is active or disabled in the system." },
    { name: "lastUpdateBmDate", label: "LAST UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date when the owner information was last updated in the system." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field maintains the identifier for the branch associated with the owner’s record." },
    { name: "cbsOwnerCifNo", label: "CORE BANKING OWNER CIF NUMBER", type: "string", size: 8, description: "This field holds the unique CIF (Customer Information File) number of the owner within the core banking system." },
    { name: "createdUserId", label: "CREATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who created the owner’s record." },
    { name: "createdDateTime", label: "CREATION DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHHH24MISS", description: "This field maintains the timestamp for when the owner’s record was created." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field holds the identifier of the user who last modified the owner’s record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHHH24MISS", description: "This field maintains the timestamp for the last modification of the owner’s record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stowntab
