// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stownlog: SchemaTable = {
  name: "stownlog",
  description: "Activities on account ownership maintenance\nThis table logs all operational activities related to the assignment, modification, or transfer of account ownership. Each entry includes account number, existing and updated owner customer IDs, type of change, timestamps of request and completion, initiating user or system, and source channel Optional fields may include document references , approval status, and audit trail linkage.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 6, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field maintains the identifier for the branch associated with the owner’s record is Created or modified." },
    { name: "userId", label: "USER ID", type: "string", size: 10, keys: { k1: 3 }, description: "This field stores the identifier of the user who created or modified the customer’s identification record." },
    { name: "dateTime", label: "DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field maintains the timestamp for when the identification record was created or modified ." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the customer record is newly created or has been modified. N - New ; U - Update" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 5, k2: 1 }, description: "This field stores the unique identification number assigned to the customer." },
    { name: "ownerNo", label: "OWNER NUMBER", type: "string", size: 4, keys: { k1: 6, k2: 2 }, description: "This field maintains the unique identifier associated with the owner." },
    { name: "ownerType", label: "OWNER TYPE", type: "string", description: "This field specifies the type of ownership.Valid\nvalues are:\nM-Manager\nT-Trustee\nC-Cashier\nW-Owners" },
    { name: "bmUpdateStatus", label: "BANK MANAGEMENT UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field stores the ID of the supervisor responsible for reviewing the card request or update." },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field maintains the branch code associated with the customer’s account." },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, description: "This field indicates the type of identification used for the owner .alid\nvalues are:\nI - Saudi Id\nQ - Iqama\nC - CR Number\nF - Family Regn no\nH - Hafiza" },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, description: "This field holds the unique identification number assigned to the owner based on the selected identification type." },
    { name: "parentCompanyName", label: "PARENT COMPANY NAME", type: "string", size: 30, description: "This field stores the name of the parent company associated with the owner" },
    { name: "shareHoldingPerc", label: "SHAREHOLDING PERCENTAGE", type: "string", size: 3, description: "This field maintains the percentage of ownership the individual or entity holds within a business or organization." },
    { name: "aFirstName", label: "ARABIC FIRST NAME", type: "string", size: 15, description: "This field stores the first name of the owner in Arabic." },
    { name: "a2ndName", label: "ARABIC SECOND NAME", type: "string", size: 15, description: "This field stores the second name of the owner in Arabic." },
    { name: "a3rdName", label: "ARABIC THIRD NAME", type: "string", size: 15, description: "This field stores the third name of the owner in Arabic." },
    { name: "aLastName", label: "ARABIC LAST NAME", type: "string", size: 15, description: "This field stores the last name of the owner in Arabic." },
    { name: "aShortName", label: "ARABIC SHORT NAME", type: "string", size: 30, description: "This field holds a short form version of the owner's name in Arabic" },
    { name: "eFirstName", label: "ENGLISH FIRST NAME", type: "string", size: 15, description: "This field stores the first name of the owner in English." },
    { name: "e2ndName", label: "ENGLISH SECOND NAME", type: "string", size: 15, description: "This field stores the second name of the owner in English." },
    { name: "e3rdName", label: "ENGLISH THIRD NAME", type: "string", size: 15, description: "This field stores the third name of the owner in English." },
    { name: "eLastName", label: "ENGLISH LAST NAME", type: "string", size: 15, description: "This field stores the last name of the owner in English." },
    { name: "eShortName", label: "ENGLISH SHORT NAME", type: "string", size: 30, description: "This field maintains the shortened form of the owner's name in English" },
    { name: "ownerEnabled", label: "OWNER STATUS", type: "string", size: 1, description: "This field indicates whether the owner's record is active or disabled in the system." },
    { name: "lastUpdateBmDate", label: "LAST UPDATE DATE", type: "string", size: 8, format: "YYYYMMDD", description: "This field stores the date when the owner information was last updated in the system." },
    { name: "recordChanged", label: "RECORD CHANGE STATUS", type: "string", size: 1, description: "This field indicates whether the customer address record has been modified. It helps track updates and ensures the most recent information is maintained in the system." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field holds the identifier of the user who last modified the owner’s record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp for the last modification of the owner’s record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stownlog
