// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stsamaacc: SchemaTable = {
  name: "stsamaacc",
  description: "SAMA account status change\nThis table documents status modifications applied to customer accounts in accordance with Saudi Central Bank (SAMA) regulations. Each entry includes the customer ID, account number, previous status (e.g., active, frozen, dormant), updated status, reason code (such as regulatory hold, legal instruction, fraud investigation), timestamp of status change, initiating authority (e.g., compliance department, legal team), and SAMA-related reference number or directive, if applicable. Optional fields may include notification status to the customer, expiry date for temporary holds, and associated risk classifications.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch where the Sadad is created/modified." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user who created/updated the account." },
    { name: "dateTime", label: "TRANSACTION DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the timestamp when the SAMA account record was created or modified." },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k2: 1 }, description: "This field contains the unique identifier assigned to the customer’s SAMA account." },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field stores the ID of the supervisor overseeing the SAMA account status change or update." },
    { name: "accStatus", label: "ACCOUNT STATUS", type: "string", size: 2, description: "This field maintains the current operational status of the SAMA account" },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field records the branch code associated with the customer linked to the SAMA account." },
    { name: "fromStatus", label: "PREVIOUS ACCOUNT STATUS", type: "string", size: 2, description: "This field stores the prior status of the SAMA account before any change was applied." },
    { name: "toStatus", label: "UPDATED ACCOUNT STATUS", type: "string", size: 2, description: "This field maintains the new status of the SAMA account after modification." },
    { name: "accStatusChangeReason", label: "ACCOUNT STATUS CHANGE REASON", type: "string", size: 30, description: "This field contains the justification or reason for the modification of the SAMA account status." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the ID of the user who last updated the record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATED DATE TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the DATE TIME of the last updated the record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stsamaacc
