// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stseclog: SchemaTable = {
  name: "stseclog",
  description: "Details about user login, logout, lock, unlock, etc\nThis table maintains a comprehensive trail of user authentication and access management activities across systems. Each entry includes user ID, login timestamp, logout timestamp, . It also captures access events such as account lock , account unlock password changes, failed login attempts, and session timeout flags.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "dateTime", label: "TRANSACTION DATE & TIME", type: "string", size: 14, keys: { k1: 2 }, description: "This field records the timestamp when any action is happened from user end e.g. Login to system/ password cahnge/etc" },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user who created/updated the account." },
    { name: "actionType", label: "ACTION TYPE", type: "string", size: 1, keys: { k1: 4 }, description: "This field stores the classification of the action performed by the supervisor\n0 - Logon\n1 - Logout\n2 - Invalid Password\n3 - Password change\n4 - User Locked\n5 - Password reset\n6 - User closed\n7 - User Added\n8 - User Deactivated\n9 - Password Expired" },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field maintains the unique ID assigned to the supervisor responsible for system authentication or transaction verification." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field records the branch associated with the supervisor login activity." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stseclog
