// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stsigntab: SchemaTable = {
  name: "stsigntab",
  description: "Master file for Account Signatories\nThis table serves as the official repository of all individuals authorized to sign or operate customer accounts, particularly for corporate, joint, and institutional clients. Each entry includes account number, signatory ID, full name, identification details, assigned role , signing mandate , effective and expiry dates, and activation status. Optional fields may include associated resolution documents, authority level , role hierarchy, digital signature references, and relationship to the account holder or entity.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 2, k2: 1 }, description: "This field stores the unique identifier of the account linked to the signatory record." },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, description: "This field stores the unique identifier of the Customer linked to signatory record" },
    { name: "signatoryNo", label: "SIGNATORY NUMBER", type: "string", size: 4, keys: { k1: 3, k2: 2 }, description: "This field maintains the unique identifier assigned to the signatory within the account structure." },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, keys: { k3: 1 }, description: "This field maintains the category of ID associated with the signatory" },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, keys: { k3: 2 }, description: "This field records the unique identification number assigned to the signatory." },
    { name: "aFirstName", label: "ARABIC FIRST NAME", type: "string", size: 15, description: "This field stores the signatory’s first name in Arabic ." },
    { name: "aSecondName", label: "ARABIC SECOND NAME", type: "string", size: 15, description: "This field maintains the signatory’s second name in Arabic." },
    { name: "aThirdName", label: "ARABIC THIRD NAME", type: "string", size: 15, description: "This field contains the signatory’s third name in Arabic." },
    { name: "aLastName", label: "ARABIC LAST NAME", type: "string", size: 15, description: "This field records the signatory’s last name in Arabic for documentation." },
    { name: "aShortName", label: "ARABIC SHORT NAME", type: "string", size: 30, description: "This field stores the abbreviated version of the signatory’s name in Arabic." },
    { name: "eFirstName", label: "ENGLISH FIRST NAME", type: "string", size: 15, description: "This field maintains the signatory’s first name in English." },
    { name: "eSecondName", label: "ENGLISH SECOND NAME", type: "string", size: 15, description: "This field contains the signatory’s second name in English." },
    { name: "eThirdName", label: "ENGLISH THIRD NAME", type: "string", size: 15, description: "This field records the signatory’s third name in English." },
    { name: "eLastName", label: "ENGLISH LAST NAME", type: "string", size: 15, description: "This field stores the signatory’s last name in English for documentation." },
    { name: "eShortName", label: "ENGLISH SHORT NAME", type: "string", size: 30, description: "This field maintains the abbreviated version of the signatory’s English name." },
    { name: "diplomaticPpNo", label: "DIPLOMATIC PASSPORT NUMBER", type: "string", size: 15, description: "This field stores the diplomatic passport number associated with the signatory, if applicable." },
    { name: "reason", label: "REASON FOR SIGNATORY DESIGNATION", type: "string", size: 25, description: "This field maintains the justification or purpose for assigning the signatory role." },
    { name: "activeStatus", label: "SIGNATORY ACTIVE STATUS", type: "string", size: 1, description: "This field records whether the signatory is currently active or inactive in the account. 0-Inactive ; 1-Active" },
    { name: "signatureActionDate", label: "SIGNATORY ACTION DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date on which the signatory action was confirmed or modified." },
    { name: "lastUpdateBmDate", label: "LAST BRANCH MASTER UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the latest date the BANK MASTER updated the signatory information." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field contains the code identifying the branch associated with the customer's account." },
    { name: "overrideOtherExpatSign", label: "OVERRIDE FOR OTHER EXPAT SIGNATORY STATUS", type: "string", size: 1, description: "This field maintains whether an override permission has been granted for expatriate signatories. 1-YES ; 0-NO" },
    { name: "createdUserId", label: "USER IDENTIFIER", type: "string", size: 10, description: "This field maintains the ID of the user who created the account." },
    { name: "createdDateTime", label: "DATE AND TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the date and time of creation" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the ID of the user who last updated the record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATED DATE TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the DATE TIME of the last updated the record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stsigntab
