// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stsodlog: SchemaTable = {
  name: "stsodlog",
  description: "Standing Order setup log.\nThis table captures the creation and configuration of standing orders (SODs) initiated directly within the bank's master system, bypassing customer-facing channels. Each entry includes standing order ID, originating branch or department, customer ID, debit account number, beneficiary details, amount, frequency , start and end dates, and purpose code.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch where the address is created/modified." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user who created/updated the account." },
    { name: "dateTime", label: "DATE AND TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the date and time when creation or upate initiated." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the record is new or has been updated. N - New ; U - Update" },
    { name: "bmUpdateStatus", label: "BANK MASTER UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered;\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field holds the ID of the supervisor responsible for reviewing customer updates." },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 5, k2: 1 }, description: "This field contains the account number to which this record relates." },
    { name: "sodNo", label: "Standing Order Number", type: "string", size: 6, keys: { k1: 6, k2: 2 }, description: "This field contains the Standing Order Number" },
    { name: "paymentType", label: "PAYMENT TYPE", type: "string", size: 1, description: "Valid values are:\n0 - Pay Until further notice\n1 - Pay until specified total has been paid\n2 - Pay until specified date has been reached\n3 - Pay until specified number of payments have been made\n4 - Payment stopped\n5 - Final payment made" },
    { name: "paymentMode", label: "PAYMENT MODE", type: "string", size: 1, description: "Valid values are:\n0 Customers beneficiary.\nPay from/to account at our bank.\n1 Customer is not beneficiary.\nPay from/to account at our bank.\n2 Credit transfer.\nPay to account at another bank.\n3 Payby cheque.\n4 Credit transfer.\nPay account specified in Payee's account number.\n5 Pay by cheque.\nPay account specified in Payee's account number." },
    { name: "firstPaymentDate", label: "DATE OF FIRST PAYMENT", type: "date", size: 8, format: "YYYYMMDD", description: "This field contains the date on which the\nfirst payment will be made" },
    { name: "finalPaymentDate", label: "DATE OF FINAL PAYMENT", type: "date", size: 8, format: "YYYYMMDD", description: "This field contains the date on which the\nfinal payment will be made.This field is only relevant if the\nPAYMENT TYPE field is set to \"2\"." },
    { name: "paymentsToBeMade", label: "NUMBER OF PAYMENTS TO BE MADE", type: "string", size: 3, description: "This field is relevant if the PAYMENT TYPE set to be '3'.This field maintain to total number of payment which are to be made" },
    { name: "paymentsMade", label: "NUMBER OF PAYMENTS MADE", type: "string", size: 3, description: "This field maintain total number of payment which are to be made" },
    { name: "paymentAmt", label: "AMOUNT OF EACH PAYMENT", type: "numeric", size: 14, description: "This field maintains the amount is tobe paid with each paymnet.Valid Values are + to - 99999999999999\nDecimal places are currency dependent." },
    { name: "totalToPay", label: "TOTAL TO PAY", type: "numeric", size: 14, description: "This field maintains the total amount is tobe paid with each paymnet.This field is relevant if the PAYMENT TYPE set to be '1'.\nDecimal places are currency dependent." },
    { name: "totalPaidToDate", label: "TOTAL PAID TO DATE", type: "numeric", size: 14, description: "This field maintains the total amount paid to date" },
    { name: "paymentFrequency", type: "string", size: 1, description: "Valid Values are : D - Daily\nW - Weekly\nM - Monthly\nQ - Quarterly\nH - Half yearly\nY - Yearly" },
    { name: "nextPaymentDate", label: "DATE OF NEXT PAYMENT", type: "date", size: 8, format: "YYYYMMDD", description: "This field contains the date on which the\nnext payment will be made" },
    { name: "limitInExcessFlag", label: "LIMIT IN EXCESS FLAG", type: "string", size: 1, description: "This field indicates the action to be taken in\nthe event of an account limit being\nexceeded. Valid values are:\n0 Pay.\n1 Donot pay in limit excess situation.\n2 Manual run. (Allows payment in limit\n‘excess situation)." },
    { name: "payAccNo", label: "PAYEE’S ACCOUNT NUMBER", type: "string", size: 14, description: "This field maintains the number of the\npayee’s account. The payee is the person to whom the\nstanding order amount will be credited." },
    { name: "commissionFlag", label: "COMMISSION CHARGESFLAG", type: "string", size: 1, description: "Valid values are:\n0 No commission to be charged.\n1 Commission to be charged." },
    { name: "orderType", label: "STANDING ORDER TYPE", type: "string", size: 1, description: "Valid values are: 0 Specific standing order.\n1 Automatic funds transfer FROM\nstanding order account.\n2 Automatic funds transfer TO standing\norder account." },
    { name: "processNextDayFlag", label: "PROCESS NEXT DAY FLAG", type: "string", size: 1, description: "Valid values are:\n0 Process todzy, during today's\nend-of-day routine.\n1 Process next day, during next day's\nstart-of-day routine. (This means an\nentry is made on the Tag file)." },
    { name: "listOnlyFlag", label: "LISTONLYFLAG", type: "string", size: 1, description: "Valid values are:\n0 Process normally and update.\n1 Only list standing order. Do not update." },
    { name: "thresholdAmt", label: "TRANSFER LIMIT FOR AUTO", type: "numeric", size: 10, description: "This limit is checked against the balance of\nthe standing order account.\nAny excess if the \"STANDING ORDER\nTYPE’ field is set to \"1\") will be transferred\nto the other account (specified in the\n\"PAYEE'S ACCOUNT NUMBER’ field).\nAny shortfall (if the *STANDING ORDER\nTYPE field is set to \"2\") will be transferred\nfrom the other account (specified in the\n*PAYEE’S ACCOUNT NUMBER’ field)." },
    { name: "drNarrative1", label: "DEBIT NARRATIVE - LINE 1", type: "string", size: 20, description: "This field contains the first line of\nnarrative used for debit standing order transactions" },
    { name: "drNarrative2", label: "DEBIT NARRATIVE - LINE 2", type: "string", size: 20, description: "This field contains the second line of\nnarrative used for debit standing order transactions" },
    { name: "crNarrative1", label: "CREDIT NARRATIVE - LINE 1", type: "string", size: 20, description: "This field contains the first line of\nnarrative used for credit standing order transactions" },
    { name: "crNarrative2", label: "CREDIT NARRATIVE - LINE 2", type: "string", size: 20, description: "This field contains the second line of\nnarrative used for credit standing order transactions" },
    { name: "transactionDateFlag", label: "TRANSACTION DATE FLAG", type: "string", size: 1, description: "Valid values are:\n0 Userundate.\n1 Use due date." },
    { name: "lastProcessedDate", label: "DATE OF LAST PROCESSING", type: "date", size: 8, format: "YYYYMMDD" },
    { name: "sodBranchCode", label: "SOD BRANCH CODE", type: "string", size: 4, description: "The branch code to which the standing\norder is applicable.This field is only\nrelevant for sites with a Centralised\nMulti-branch database" },
    { name: "supervisorComments", label: "SUPERVISOR COMMENTS", type: "string", size: 200, description: "This field records any remarks or observations provided by the supervisor related to the cheque stoppage request." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the transaction record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "string", size: 14, description: "This field records the timestamp of the most recent modification made to the SIGN transaction." },
    { name: "lastUpdateBmDate", label: "LAST UPDATED DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field holds the date of the last update made to the customer’s records." },
    { name: "remarks", label: "REMARKS", type: "string", size: 25, description: "REMARKS" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stsodlog
