// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const thd0data1: SchemaTable = {
  name: "thd0data1",
  description: "Transaction history - Record Type 2 and 3\nThe Transaction History file maintains a record of all transactions that have been entered since installation of Bank master.. At least one record is held for each posting which occurs - in the case of postings containing narrative to hold the information.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "Data Restored date" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 1 }, description: "This field contains the account number to which this record relates." },
    { name: "transCounter", label: "TRANSACTION COUNTER", type: "string", size: 5, keys: { k1: 3 }, description: "The transaction counter is used to locate the\nrecord within the file.", note: "Field newly added on 28/05/2025" },
    { name: "postDate", label: "POSTING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2 }, description: "This field maintains the posting date as\nentered with the transaction at time of\nposting." },
    { name: "valueDate", label: "VALUE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date on which the\nransaction took effect" },
    { name: "transType", label: "TRANSACTION TYPE", type: "string", size: 2, description: "This field maintains the type of transaction,\nas defined on the TTABLE parameter file" },
    { name: "statmentFlag", label: "STATEMENT FLAG", type: "string", size: 1, description: "This field indicates whether the transaction\nis to be included on statements.\nValid values are:\n0 Print on statement.\n1 Do not print on statement." },
    { name: "transAmt", label: "TRANSACTION AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field maintains the amount of the\ntransaction.\nDecimal places are currency dependent." },
    { name: "accruedInt", label: "ACCRUED INTEREST", type: "numeric", size: 16, format: "16,3", description: "This field maintains the interest accrued by\nthe transaction." },
    { name: "transRef", label: "TRANSACTION REFERENCE", type: "string", size: 10, description: "This field maintains the reference which\naccompanied the transaction on posting.\nFor Foreign Exchange records, ths field\nholds the \"BASE CURRENCY EQUIVALENT’ amount." },
    { name: "narrative1", label: "NARRATIVE - LINE 1", type: "string", size: 25, description: "This field maintains the first line of the\nnarrative input at time of posting.\nFor Foreign Exchange records, the position\noccupied on the record byThis field is\nredefined by the \"FOREIGN EXCHANGE\nDEAL REFERENCE’ field." },
    { name: "fxIndicator", label: "FOREIGN EXCHANGE INDICATOR", type: "string", size: 1, description: "This field indicates whether the transaction\n‘was a foreign exchange transaction. Valid\nvalues are:\n0 No.\n1 Yes Foreign Exchange transaction.\n2 Yes- Foreign Exchange Profit and\nLoss Revaluation transaction.\n3 Multi Currency from BNK0OI Auto\nForeign Exchange Position posting." },
    { name: "transServiceFee", label: "SERVICE FEE THIS TRANSACTION", type: "numeric", size: 16, format: "16,3", description: "This field contains the service fee accrued.\nItis only used if the *SERVIS FEE field on\nthe TTABLE parameter file was set to \"1\".\nNote:This field holds the gross interest\napplication amount when the\n\"TRANSACTION INDICATOR’ field is\nsetto \"I\". Decimal places are currency\ndependent." },
    { name: "userId", label: "A USER LD.", type: "string", size: 3, description: "This field maintains the LD. of the teller\nwho posted the transaction." },
    { name: "supervisorId", label: "SUPERVISOR ID.", type: "string", size: 3, description: "(IF ANY)\nIf a supervisor's password was required\nduring the transaction, the supervisor LD.\nwill be stamped here." },
    { name: "transactionInd", label: "TRANSACTION INDICATOR", type: "string", size: 1, description: "Valid values are:\nI Interest appliction,\nB Blocking transaction.\nS Special repayment (Leasing only).\nE Effective rate change (BNK151 stamps\nit at end of day for tiered rate changes)." },
    { name: "transAmtCD", label: "TRANSACTION AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field contains:\n1. The nominal transaction amount for\nBills, C.D.’s and Securities.\n2. The adjustment amount calculated by\nthe Interest Recalculation program\n(BNK145)." },
    { name: "narrative2", label: "NARRATIVE - LINE 2", type: "string", size: 25, description: "This field is auto stamped with\n\"XXX XXXXXX', where XXX. XXXXXX\nis the new rate." },
    { name: "narrative3", label: "NARRATIVE - LINE 3", type: "string", size: 25, description: "This field contains the third line of narrative\ninput at time of posting." },
    { name: "newCrIntRate", label: "NEW CREDIT INTEREST RATE", type: "numeric", size: 9, format: "9,5", description: "Valid values are: 0 -999.999999." },
    { name: "newDrIntRate", label: "NEW DEBIT INTEREST RATE", type: "numeric", size: 9, format: "9,5", description: "Valid values are: 0 -999.999999." },
    { name: "activeRateFlag", label: "ACTIVERATEFLAG", type: "string", size: 1, description: "Valid values are:\n0 Debit.\n1 Credit" },
    { name: "newBaseCode", label: "NEWBASE CODE", type: "string", size: 2, description: "NEWBASE CODE" },
    { name: "marginOverBase", label: "MARGIN OVER BASE RATE", type: "numeric", size: 9, format: "9,5", description: "MARGIN OVER BASE RATE" },
    { name: "drCrBase", label: "DEBIT/CREDIT BASE CODE", type: "string", size: 1, description: "0 Debit base code.\n1 Credit base code." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default thd0data1
