// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const aad0data: SchemaTable = {
  name: "aad0data",
  description: "ALCO Account Details file.This table maintains the detailed account-level data required for ALCO reporting, monitoring, and strategic balance sheet management. Each record includes the account number, account name, customer ID, product type, interest rate type, rate value, currency, maturity date, repricing frequency, and balance information. It also captures risk classification, funding source, branch code, and account status.",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "FinoneAlcoAccNo", label: "FINONE ALCO ACCOUNT NO", type: "string", size: 13, keys: { k1: 2, k2: 1 }, description: "Memo(5) + Finone Loan no(8)", note: "Version 1.0 column name renamed old name was accno 16/07/2025" },
    { name: "intRevPeriod", label: "INTEREST REVIEW PERIOD FOR ACCOUNT", type: "string", size: 1, description: "Interest Review period for account\nD - day\nW - week\nM - month\nY - year" },
    { name: "intRevFreq", label: "FREQUENCY OF FUNDING INTEREST REVIEW.", type: "string", size: 2, description: "This is used in conjunctionwith the interest review period (above). E.g. if int review period = 'M' and int review frequency = '2', the account is due for interest review every two months. Note: if the review period is set to 'Y', the value of the frequency field is ignored (i.e. it is always taken to be 1)" },
    { name: "crmarginFundRate", label: "CREDIT MARGIN FUND RATE", type: "numeric", size: 14, format: "14,8", description: "Margin which is added to CR funding rate to arrive at the actual funding rate for the account. May be +/-." },
    { name: "drmarginFundRate", label: "DEBIT MARGIN FUND RATE", type: "numeric", size: 14, format: "14,8", description: "Margin which is added to DR funding rate to arrive at the actual funding rate for the account. May be +/-." },
    { name: "crmarginIntRev", label: "CREDIT MARGIN INTREST REVIEW", type: "numeric", size: 14, format: "14,8", description: "Margin which is used for interest reviews when a new CR funding rate is to be calculated. May be +/-." },
    { name: "drmarginIntRev", label: "DEBIT MARGIN INTREST REVIEW", type: "numeric", size: 14, format: "14,8", description: "Margin which is used for interest reviews when a new DR funding rate is to be calculated. May be +/-." },
    { name: "startDate", label: "START DATE", type: "date", size: 8, format: "YYYYMMDD", description: "Account start date which the ALCO program uses for funding\ninterest calculation for single and multi maturities. This field\nis maintained by the ALCO process." },
    { name: "maturityDate", label: "MATURITY DATE", type: "date", size: 8, format: "YYYYMMDD", description: "Current maturity date of the account. For fixtures with one\nmaturity, this field holds the GL maturity date. For fixtures\nwith multi-maturities (commercial loans), this field holds the\nfinal repayment date." },
    { name: "crMaturityAmt", label: "TOTAL CREDIT MATURITY AMOUNT", type: "numeric", size: 16, format: "16,3", description: "Total calculated CR month to date funding amount for the account" },
    { name: "drMaturityAmt", label: "TOTAL DEBITMATURITY AMOUNT", type: "numeric", size: 16, format: "16,3", description: "Total calculated DR month to date funding amount for the account" },
    { name: "maturityBal", label: "MATURITY BALANCE", type: "numeric", size: 16, format: "16,3", description: "Report Balance on the account" },
    { name: "crIntRate", label: "CREDIT INTEREST RATE/YIELD RATE", type: "numeric", size: 9, format: "9,5", description: "For accounts accruing interest via the\nNormal or Savings methods, ths field holds\nthe credit interest rate on the account,\nFor accounts accruing interest via the\nDiscount, Security or Certificates of\nDeposit methods,This field is the yield rate\non the account, The yield rate is\nmemorandum for the Discount or Security\nmethod, but is part of the interest\ncalculation formula for the Certificates of\nDeposit method.\nValid values are: 0- 999.999999" },
    { name: "drIntRate", label: "DEBIT INTEREST RATE/COUPON RATE/DISCOUNT RATE", type: "numeric", size: 9, format: "9,5", description: "For accounts accruing interest via the\nNormal or Savings methods,This field holds\nthe debit interest rate on the account.\nFor accounts accruing interest via the\nSecurity or Certificates of Deposit methods,\nthis field holds the coupon rate on the\naccount.\nFor accounts accruing interest via the\nDiscount method,This field holds the\ndiscount rate on the account.\nValid values are: 0 -999.999999" },
    { name: "crFundAmt", label: "CREDIT FUNDING AMOUN", type: "numeric", size: 16, format: "16,3", description: "Credit funding amount for the day" },
    { name: "drFundAmt", label: "DEBIT FUNDING AMOUN", type: "numeric", size: 16, format: "16,3", description: "Debit funding amount for the day" },
    { name: "processDate", label: "PROCESSING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date on which the transaction was processed in the system." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field maintains a 4 digit branch\nnumber, defined by the financial institution,\nwhich is unique for each branch within the\nIMD number." },
    { name: "maturityAmtNonPrf", label: "MATURITY AMOUNT NON PERFORMING", type: "numeric", size: 16, format: "16,3", description: "Total MTD DR funding Interest amount (NON-PERFORMING)" },
    { name: "status", type: "string", size: 1, description: "Account Status\nvalue '0' = normal, value '1' bad debtor." },
    { name: "statusDate", label: "ACCOUNT STATUS DATE", type: "date", size: 8, format: "YYYYMMDD", description: "Account Status Date" },
    { name: "maturityIntRate", label: "MATURITY INTEREST RATE", type: "numeric", size: 14, format: "14,8", description: "This field stores the interest rate applied at the maturity of a deposit or loan. It determines the final interest earnings or charges at the end of the term." },
    { name: "renewType", label: "RENEWAL TYPE", type: "string", size: 1, description: "This field maintains the classification of renewal options available for the term deposit or loan (e.g., automatic renewal, manual renewal)." },
    { name: "renewPrd", label: "RENEWAL PERIOD", type: "string", size: 2, description: "This field records the specified duration for renewal, defining the next term applicable after maturity." },
    { name: "reviewDate", label: "REVIEW DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the scheduled date for evaluating or reassessing the terms of the financial agreement, including interest rates or renewal conditions." },
    { name: "drInterestPYTD", label: "DEBIT INTEREST PAID YEAR TO DATE", type: "numeric", size: 16, format: "16,3", description: "This field stores the total amount of debit interest paid by the customer from the start of the financial year to the present date. It helps track cumulative interest expenses incurred within the current year for reporting and analysis purposes." },
    { name: "drInterestCYTD", label: "DEBIT INTEREST CHARGED YEAR TO DATE", type: "numeric", size: 16, format: "16,3", description: "This field stores the total amount of debit interest charged to the customer for the current financial year, helping track cumulative loan expenses." },
    { name: "crInterestPYTD", label: "CREDIT INTEREST RECEIVED PRIOR YEAR TO DATE", type: "numeric", size: 16, format: "16,3", description: "This field maintains the total amount of credit interest accrued in the previous financial year." },
    { name: "newRvPrd", label: "NEW REVIEW PERIOD", type: "string", size: 1, description: "This field records the revised period for loan or interest rate review, defining when the next evaluation takes place." },
    { name: "newRvFreq", label: "NEW REVIEW FREQUENCY", type: "string", size: 2, description: "This field stores the updated frequency for loan reassessment (e.g., monthly, quarterly, annually)." },
    { name: "penIntRate", label: "PENALTY INTEREST RATE", type: "numeric", size: 14, format: "14,8", description: "This field maintains the interest rate applied on overdue loan payments or penalties." },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, description: "This field records the unique identifier associated with the customer holding the loan." },
    { name: "loanBlockBal", label: "BLOCKED LOAN BALANCE", type: "numeric", size: 16, format: "16,3", description: "This field stores any restricted loan balance that is temporarily unavailable for transactions due to specific conditions." },
    { name: "settlementAccNo", label: "SETTLEMENT ACCOUNT NUMBER", type: "string", size: 14, keys: { k3: 1 }, description: "This field maintains the designated account for settling loan related payments and transactions." },
    { name: "FileCount", label: "FILE COUNT", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "FILE NAME", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default aad0data
