// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const acaptrTR: SchemaTable = {
  name: "acaptrTR",
  description: "Contains detailed breakdown of all interest application transactions at the individual account level.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 3, k3: 1 }, description: "Data Restored date" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 3, k2: 2 }, description: "Account number which is formed as below:\nCCMMMNNNNNNNSS\nDIGITS DESCRIPTION\n1-2 Currency Reference (CC).\n3-5 Memorandum Account Reference(MMM).\n6-12 Customer or Ledger Account Reference (NNNNNNN).\n13-14 Sub-account Reference (SS)" },
    { name: "refNo", label: "REFERENCE NUMBER", type: "string", size: 10 },
    { name: "transType", label: "TRANSACTION TYPE", type: "string", size: 2, keys: { k1: 2, k2: 1, k3: 2 }, description: "This field indicates the type of transaction\ninvolved as defined by the TTABLE\nparameter file.\n(See the Central Bankmaster - Control file\nData Dictionary for transaction type\ndefinitions)." },
    { name: "transAmt", label: "AMOUNT TRANSACTION", type: "numeric", size: 16, format: "16,3", description: "This field maintains the Transaction Amount\nDecimal places are currency dependent." },
    { name: "contraAccNo", label: "CONTRA ACCOUNT NUMBER", type: "string", size: 14, keys: { k3: 3 }, description: "This field maintains the contra account\nnumber used at time of posting\nIn the case of more than one contra being\ninput, this is the number of the first contra,\nIf this is a conta posting then the contra\naccount number holds the account number\nof the main posting." },
    { name: "processFlag", label: "PREOCESS FLAG", type: "string", size: 1, description: "This field maintain for current PREOCESS FLAG" },
    { name: "FileCount", label: "FILE COUNT", type: "numeric", size: 12, description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "FILE NAME", type: "string", size: 30, description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default acaptrTR
