// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const amd0data: SchemaTable = {
  name: "amd0data",
  description: "This table contains a record of all unmatured accounts with a maturity date on or before the Bank Diary\nprogram run date.The file is used to ensure that the Diary records are processed in account number within branch order.This file is only relevant to a centralised multi-branch database.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "valueDate", label: "VALUE DATE (PART OF KEY)", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2 }, description: "This field maintains the date on which the\nitem will be processed and take effect.\nThe date is in the format YYYYMMDD." },
    { name: "branchCode", label: "BRANCH CODE (PART OF KEY)", type: "string", size: 4, keys: { k1: 3 }, description: "This field maintains a 4 digit branch\nnumber, defined by the financial institution,\nwhich is unique for each branch within the\nIMD number." },
    { name: "acctNum", label: "ACCOUNT NUMBER (PART OF KEY)", type: "string", size: 14, keys: { k1: 4 }, description: "This field maintains the number of the\naccount which is due to mature." },
    { name: "refCode", label: "REFERENCE CODE FOR LOAN REPAYMENTS", type: "string", size: 4, description: "This field maintains a reference code which\nis used for page skipping and control in the\ndiary processing report.\nThe code is in the format AA BB (where.\nAA=Department and BB=Category)." },
    { name: "recType", label: "RECORD TYPE", type: "string", size: 2, description: "This field is set to \"02\" for Maturity\nrecords, in accordance with the Bank Diary\nfile." },
    { name: "transType", label: "TRANSACTION TYPE", type: "string", size: 2, description: "This field indicates the type of transaction\ninvolved as defined by the TTABLE\nparameter file.\n(See the Central Bankmaster - Control file\nData Dictionary for transaction type\ndefinitions)." },
    { name: "reference", label: "REFERENCE", type: "string", size: 10, description: "This field maintains the reference number\nthat was input or automatically generated at\ntime of posting. It may be a cheque number,\ndraft number, deal number or other\nreference depending on the transaction type\ninvolved.\nFor foreign exchange deals, the numbers\nmay be automatically assigned, if desired,\nbutit is recommended thal they be input as\ndetailed on the dealing ticket so that use.\n‘may be made of the Deal Number Gap\nReport.\n‘When in use, the Deal Number Gap Report\nshould be checked to ensure that ALL gaps\nin the numbering sequence can be\naccounted for." },
    { name: "principleLoanAmt", label: "AMOUNT - PRINCIPAL FOR LOANS", type: "numeric", size: 14, description: "This field maintains the principal amount\nfor commercial loan repayment records\n(05).\nDecimal places are currency dependent." },
    { name: "processedFlag", label: "PROCESSEDFLAG", type: "string", size: 1, description: "This field is set to \"1\" when the diary item\nhas been processed by the Diary Processing\n‘program (BNK040). When the diary\n‘process is next run it will delete all items\nwith the maturities processed flag set to \"1\".\nValid values are:\n0 Not yet processed.\n1 Processed - may be deleted." },
    { name: "FileCount", type: "numeric", size: 12, format: "present in last record only" },
    { name: "FileName", type: "string", size: 30, format: "present in last record only" },
  ],
}

export default amd0data
