// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const ank0dataXC: SchemaTable = {
  name: "ank0dataXC",
  description: "This table defines the configuration of currency code and account fee record system",
  status: "New Table",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "currCode", label: "CURRENCYCODE", type: "string", size: 4, keys: { k1: 2, k2: 1 }, description: "This field maintains the currency to which this record relates. The two codes \"00\" and \"01\" always relate to base currency." },
    { name: "currDesc", label: "CURRENCY SYMBOL", type: "string", size: 30, description: "This field maintains the 30 character name associated with this currency." },
    { name: "fixRate", label: "FIX RATE", type: "numeric", size: 10, format: "6,8", description: "This field records fixed exchange rate set by the bank" },
    { name: "exchangeRateExt", label: "EXCHANGE RATE", type: "numeric", size: 10, format: "6,8", description: "This field records the exchange rate applied to the transaction if foreign currency is involved." },
    { name: "dormantFee", label: "DORMANT FEE", type: "numeric", size: 10, description: "This field store fee charged for inactive or dormant accounts." },
    { name: "minimumBal", label: "MINIMUM BALANCE", type: "numeric", size: 10, description: "Minimum balance required to avoid fees or maintain account status." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default ank0dataXC
