// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const bmdft01: SchemaTable = {
  name: "bmdft01",
  description: "This table contains details of settled and unsettled drafts . Each record includes key details such as draft number, transaction date, amount, and draft status.",
  status: "Table modified",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "recType", label: "RECORD TYPE", type: "string", size: 2, keys: { k1: 2, k2: 1 }, description: "TF-Transfer or DF-Draft or DR-Draft Range" },
    { name: "draftNum", label: "DRAFT REFERENCE", type: "string", size: 10, keys: { k1: 3, k2: 2 }, description: "This field maintains the reference Number for DRAFT.", note: "Version 1.0 Is was Number changed to String on 03/07/2025" },
    { name: "acctNum", label: "DEBIT ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 4, k3: 1 }, description: "Account number which is formed as below:\nCCMMMNNNNNNNSS\nDIGITS DESCRIPTION\n1-2 Currency Reference (CC).\n3-5 Memorandum Account Reference(MMM).\n6-12 Customer or Ledger Account Reference (NNNNNNN).\n13-14 Sub-account Reference (SS)" },
    { name: "draftStatus", label: "PAYMENT STATUS", type: "string", size: 1, description: "This field maintains the finalized status of the fund transfer (e.g., completed, pending, failed)." },
    { name: "draftAmt", label: "TOTAL AMOUNT", type: "numeric", size: 14, description: "This field records the complete amount being transferred, inclusive of fees if applicable." },
    { name: "issueDate", label: "ISSUE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "maintains the issuance date transfer or draft" },
    { name: "issueUserId", label: "ISSUE USER ID", type: "string", size: 3, description: "This field contains details Bank user id who issued the DRAFT" },
    { name: "issueTransType", label: "ISSUE TRANSACTION TYPE", type: "string", size: 2, description: "This field stores the classification of the transaction when the draft is issued (e.g., payment, remittance)." },
    { name: "description", label: "TRANSACTION DESCRIPTION", type: "string", size: 25, description: "This field maintains detailed information regarding the draft transaction, including purpose and associated details." },
    { name: "settledDate", label: "SETTLEMENT DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the draft transaction was fully settled." },
    { name: "settleduserId", label: "SETTLED BY USER IDENTIFIER", type: "string", size: 3, description: "This field stores the unique ID of the user responsible for settling the draft transaction." },
    { name: "settledTransType", label: "SETTLED TRANSACTION TYPE", type: "string", size: 2, description: "This field maintains the final classification of the transaction upon settlement." },
    { name: "Reamrks", label: "REMARKS", type: "string", size: 10, description: "This field maintains the Remarks it contain some Valis data" },
    { name: "issedTransCount", label: "ISSUE TRANSACTION COUNT", type: "numeric", size: 5, description: "This field maintains the Transaction count of issued data", note: "Field newly added on 16/07/2025" },
    { name: "settledTransCount", label: "SETTLED TRANSACTION COUNT", type: "numeric", size: 5, description: "This field maintains theTransaction count of settled data", note: "Field newly added on 16/07/2025" },
    { name: "settledAmt", label: "SETTLED AMOUNT", type: "numeric", size: 14, description: "This field maintains the final amount settled for the draft transaction." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default bmdft01
