// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const ccblklog: SchemaTable = {
  name: "ccblklog",
  description: "Log of Account and Credit card blocking has data onwards from 2005.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2, k3: 2 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "The branch initiated the card blocking" },
    { name: "userId", label: "USER IDENTIFICATION", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the user ID who initiated the card block request." },
    { name: "dateTime", label: "DATE & TIME OF BLOCK REQUEST", type: "string", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the timestamp when the card blocking action was initiated." },
    { name: "pendingStatus", label: "PENDING BLOCK STATUS", type: "string", size: 1, description: "This field stores the current pending status of the card blocking request, indicating if further actions are required.\n1-Pending with supervisor\n2-Pending with CSO\n3-Rejected\n9-completed" },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFICATION", type: "string", size: 10, description: "This field maintains the unique ID of the supervisor reviewing or approving the card block request." },
    { name: "cardNo", label: "CARD NUMBER", type: "string", size: 16, keys: { k2: 1 }, description: "This field records the unique number of the blocked card" },
    { name: "bmAccNo", label: "BANK MASTER ACCOUNT NUMBER", type: "string", size: 14, keys: { k3: 1 }, description: "This field stores the account number linked to the blocked card." },
    { name: "action", label: "BLOCKING ACTION TYPE", type: "string", size: 1, description: "This field maintains the specific blocking action taken\nN-New blocking\nA-Amend\nD-Deleted" },
    { name: "blockedAmt", label: "BLOCKED AMOUNT", type: "numeric", size: 14, description: "This field records the amount that has been restricted or frozen as part of the card blocking process." },
    { name: "oldBlockAmt", label: "PREVIOUS BLOCKED AMOUNT", type: "numeric", size: 14, description: "This field stores the earlier amount that was blocked, if applicable, for historical tracking." },
    { name: "supervisorComments", label: "SUPERVISOR COMMENTS", type: "string", size: 200, description: "This field maintains any notes or instructions provided by the supervisor regarding the card block status." },
    { name: "nameOnTheCard", label: "CARDHOLDER NAME", type: "string", size: 26, description: "This field records the name of the cardholder as printed on the card for verification." },
    { name: "cardInternalStatus", label: "INTERNAL CARD STATUS", type: "string", size: 1, description: "This field stores the internal card status of the card within the FDI system." },
    { name: "cardExternalStatus", label: "EXTERNAL CARD STATUS", type: "string", size: 1, description: "This field maintains the card’s external status maintained in FDI system." },
    { name: "cardOrAcct", label: "CARD OR ACCOUNT INDICATOR", type: "string", size: 1, description: "This field records whether the block applies specifically to the card or the linked account.C-Credit card\nA-Account" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER", type: "string", size: 10, description: "This field stores the user ID responsible for making the latest updates to the blocking record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE TIMESTAMP", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the exact date and time when the card block status was last modified." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default ccblklog
