// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const ccpayhist: SchemaTable = {
  name: "ccpayhist",
  description: "Holds Credit Card payments from 2004.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 1 }, description: "Data Restored date" },
    { name: "dateTime", label: "DATE & TIME", type: "string", size: 14, description: "date and Time of transcaction" },
    { name: "uniqNo", label: "UNIQUE NUMBER", type: "string", size: 8, description: "This field contain unique sequence number" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k2: 2 }, description: "Account number which is formed as below:\nCCMMMNNNNNNNSS\nDIGITS DESCRIPTION\n1-2 Currency Reference (CC).\n3-5 Memorandum Account Reference(MMM).\n6-12 Customer or Ledger Account Reference (NNNNNNN).\n13-14 Sub-account Reference (SS)" },
    { name: "cardNo", label: "CARD NUMBER", type: "string", size: 16, keys: { k1: 2 }, description: "This field stores the unique card number used for processing transactions." },
    { name: "bmRef", label: "BANK MASTER REFERENCE NUMBER", type: "string", size: 10, description: "This field maintains the reference number assigned by the branch master for tracking purposes." },
    { name: "transAmt", label: "TRANSACTION AMOUNT", type: "numeric", size: 14, description: "This field records the monetary value of the transaction conducted using the card." },
    { name: "valueDate", label: "VALUE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the effective transaction date used for financial processing." },
    { name: "postDate", label: "TRANSACTION POSTING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date on which the transaction was posted to the account." },
    { name: "bmDate", label: "BUSINESS DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the Busines date when the transaction was occurred" },
    { name: "revFlag", label: "REVERSAL FLAG INDICATOR", type: "string", size: 1, description: "This field stores whether the transaction is flagged for reversal due to discrepancies or corrections." },
    { name: "status", label: "TRANSACTION STATUS", type: "string", size: 1, description: "This field maintains the current processing status of the transaction" },
    { name: "errCode", label: "ERROR CODE IDENTIFIER", type: "string", size: 4, description: "This field stores any system generated error codes linked to the transaction for troubleshooting purposes." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default ccpayhist
