// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const cnd0dataNR: SchemaTable = {
  name: "cnd0dataNR",
  description: "RecType NR : Narrative description for Narrative code.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "narrativeCode", label: "NARRATIVE CODE", type: "string", size: 4, keys: { k1: 2, k2: 1 }, description: "This field contains Narrative Code" },
    { name: "arabicNarrative", label: "NARRATIVE ARABIC", type: "string", size: 25, description: "This field contains ENGLISH Arabic Description" },
    { name: "englishNarrative", label: "NARRATIVE ENGLISH", type: "string", size: 25, description: "This field contains ENGLISH NATTIVE Description" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default cnd0dataNR
