// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const cnd0dataMR: SchemaTable = {
  name: "cnd0dataMR",
  description: "RecType MR : Margin Rates.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "currCode", label: "CURRENCY CODE", type: "string", size: 2, keys: { k1: 2, k2: 1 }, description: "This field maintains the currency code" },
    { name: "serialNo", label: "SERIAL NUMBER", type: "string", size: 1, keys: { k1: 3 }, description: "This field maintains SERIAL NUMBER" },
    { name: "depositAmt", label: "DEPOSIT AMOUNT", type: "numeric", size: 14, format: "16,3 decimal place currency depdendent", description: "This field maintains the monetary value deposited in the deposit account." },
    { name: "defMargin", label: "DEF MARGIN", type: "numeric", size: 9, format: "9,6", description: "This field maintains the default margin" },
    { name: "minMargin", label: "MINIMUM MARGIN", type: "numeric", size: 9, format: "9,6", description: "This field maintains the minimum margin" },
    { name: "maxMargin", label: "MAXIMUM MARGIN", type: "numeric", size: 9, format: "9,6", description: "This field maintains the maximum margin" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default cnd0dataMR
