// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const cnd0dataBR: SchemaTable = {
  name: "cnd0dataBR",
  description: "RecType BR : Maintains the Currency Base Rates and limits",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 3 }, description: "Data Restored date" },
    { name: "currCode", label: "CURRENCY/COUNTRY CODE", type: "string", size: 2, keys: { k1: 2, k2: 1 }, description: "This field maintains the currency to which this record relates. The two codes \"00\" and \"01\" always relate to base currency." },
    { name: "baseCode", label: "BASE CODE", type: "string", size: 2, keys: { k1: 3, k2: 2 }, description: "This field maintain BASE CODE" },
    { name: "baseRate", label: "BASE RATE", type: "numeric", size: 9, format: "9,6", description: "This field maintains the margin which is BASE RATE" },
    { name: "changeFlag", label: "CHANGE INDICATOR FLAG", type: "string", size: 1, description: "Change flag indicator" },
    { name: "tiredFlag", label: "TIERED FLAG", type: "string", size: 1, description: "Tired flag" },
    { name: "calcType", label: "CALCULATION TYPE", type: "string", size: 1, description: "Calculation type" },
    { name: "rate1", label: "RATE 1", type: "string", size: 9, format: "9,6", description: "This field maintains the base interest rate code1." },
    { name: "limit1", label: "LIMIT 1", type: "numeric", size: 12, format: "12,0", description: "Limit for rate code 1" },
    { name: "rate2", label: "RATE 2", type: "numeric", size: 9, format: "9,6", description: "This field maintains the base interest rate code 2." },
    { name: "limit2", label: "LIMIT 2", type: "numeric", size: 12, format: "12,0", description: "Limit for rate code 2" },
    { name: "rate3", label: "RATE 3", type: "numeric", size: 9, format: "9,6", description: "This field maintains the base interest rate code 3." },
    { name: "limit3", label: "LIMIT 3", type: "numeric", size: 12, format: "12,0", description: "Limit for rate code 3" },
    { name: "rate4", label: "RATE 4", type: "numeric", size: 9, format: "9,6", description: "This field maintains the base interest rate code 4." },
    { name: "limit4", label: "LIMIT 4", type: "numeric", size: 12, format: "12,0", description: "Limit for rate code 4" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default cnd0dataBR
