// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const cnd0dataC0: SchemaTable = {
  name: "cnd0dataC0",
  description: "RecType C0: Maintain configuration Date and fees.",
  status: "New Table",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 3 }, description: "Data Restored date" },
    { name: "reportBalanceDate", label: "REPORT BALANCE DATE", type: "string", size: 2, keys: { k1: 2, k2: 1 }, description: "The date used to generate a snapshot of account balances for reporting purposes. Often aligns with month-end or quarter-end." },
    { name: "lastStatementDate", label: "LAST STATEMENT DATE", type: "string", size: 2, description: "The date of the most recent account statement issued to the customer or institution." },
    { name: "lastInterestDate", label: "LAST INTEREST DATE", type: "numeric", size: 9, format: "9,6", description: "The last date on which interest was calculated or posted to the account." },
    { name: "taxLimit", label: "TAX LIMIT", type: "string", size: 1, description: "A threshold value used for tax calculations, such as exemption limits or taxable caps." },
    { name: "lastExtractionDate", label: "LAST EXTRACTION DATE", type: "string", size: 1, description: "The most recent date on which data was extracted from the system for reporting or analysis." },
    { name: "lastFxRevalDate", label: "LAST FOREIGN EXCHANGE REVALUATION DATE", type: "string", size: 1, description: "The last date on which foreign currency balances were revalued based on updated exchange rates." },
    { name: "ns33Limit", label: "NS33 LIMIT", type: "string", size: 9, format: "9,6" },
    { name: "nextDetailNo", label: "NEXT DETAIL NUMBER", type: "numeric", size: 12, format: "12,0", description: "The next available identifier or sequence number for detailed transaction entries." },
    { name: "serviceCharge", label: "SERVICE CHARGE", type: "numeric", size: 9, format: "9,6", description: "A fee applied for account maintenance or specific banking services." },
    { name: "servicePer", label: "SERVICE PERCENTAGE", type: "numeric", size: 12, format: "12,0", description: "Represents the percentage rate applied for service-related charges." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default cnd0dataC0
