// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const cnd0dataXC: SchemaTable = {
  name: "cnd0dataXC",
  description: "RecType XC : Currency details like decimal place, Exchange Rate, drBaseDays/CrBaseDays.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "CurrnecyCode", label: "CURRENCYCODE", type: "string", size: 2, keys: { k1: 2, k2: 1 }, description: "This field maintains the currency to which this record relates. The two codes \"00\" and \"01\" always relate to base currency." },
    { name: "shortCode", label: "CURRENCY SHORT CODE", type: "string", size: 3, description: "This field maintains the 3 character alpha currency code. For example: USD United States Dollar.\nIEP Irish Punt. GBP Sterling." },
    { name: "curName", label: "CURRENCY SYMBOL", type: "string", size: 30, description: "This field maintains the 30 character name associated with this currency." },
    { name: "noOfDays", label: "NUMBER OF DAYS IN YEAR FOR INTEREST CALCULATION", type: "numeric", size: 3, description: "This field contains the number of days in the year which will be used by interest accrual and application for this currency. It will be set to either 360 or 365." },
    { name: "MDFlag", label: "MULTIPLYDIVIDEFLAG", type: "string", size: 1, description: "This field indicates whether the purchase currency will be multiplied or divided by the exchange rate when calculating base currency equivalents. Valid values are:\nM Multiply.\nD Divide." },
    { name: "exchangeRateExt", label: "EXCHANGE RATE", type: "numeric", size: 11, format: "6,8", description: "This field records the exchange rate applied to the transaction if foreign currency is involved." },
    { name: "chequeAc", label: "CHEQUE ACCOUNT", type: "string", size: 14, description: "Account number used in cheque related transactions." },
    { name: "BOEFlag", label: "Bank OF England Flag", type: "string", size: 1, description: "Not used" },
    { name: "telexLook", label: "TELEX LOOKUP INDICATOR", type: "string", size: 2, description: "This field stores the reference used for identifying telex related exchange rate transactions, ensuring accurate communication and processing." },
    { name: "transLimit", label: "TRANSACTION LIMIT FOR EXCHANGE", type: "string", size: 2 },
    { name: "decimalPlace", label: "NUMBER OF DECIMAL PLACES ALLOWED", type: "numeric", size: 1, description: "This field maintains the number of decimal places defined for this currency.\nValid values are: 0-3." },
    { name: "suspenseAc", label: "SUSPENSE ACCOUNT", type: "string", size: 14, description: "Suspense account for this currency" },
    { name: "lDAdj", label: "LIQUIDITY ADJUSTMENT", type: "string", size: 12 },
    { name: "fxPosAdj", label: "FOREIGN EXCHANGE POSITION ADJUSTMENT", type: "string", size: 12, description: "This field maintains the adjustment made to the financial position based on fluctuations in foreign exchange markets." },
    { name: "fxBEAdj", label: "FOREIGN EXCHANGE BASE EQUIVALENT ADJUSTMENT", type: "string", size: 12, description: "This field records the modification applied to base currency equivalents due to exchange rate variations." },
    { name: "constant", label: "CONSTANT VALUE", type: "string", size: 4, description: "This field stores predefined constant values used in exchange rate calculations for stability and reference." },
    { name: "rndDrAmt", label: "ROUNDED DEBIT AMOUNT ADJUSTMENT", type: "string", size: 1, description: "This field maintains the rounding adjustment applied to debit amounts" },
    { name: "rndCrAmt", label: "ROUNDED CREDIT AMOUNT ADJUSTMENT", type: "string", size: 1, description: "This field records the rounding adjustment applied to credit amounts" },
    { name: "drBaseDays", label: "DEBIT BASE DAYS", type: "numeric", size: 3, description: "This field contain debit base days" },
    { name: "crBaseDays", label: "CREDIT BASE DAYS", type: "numeric", size: 3, description: "This field contain credit base days" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default cnd0dataXC
