// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const cnd0dataBD: SchemaTable = {
  name: "cnd0dataBD",
  description: "RecType BD : Branch info like name, city, satement day.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "BranchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2, k2: 1 }, description: "This field maintains the branch code where the accounts belong." },
    { name: "engBrName", label: "ENGLISH BRANCH NAME", type: "string", size: 30, description: "This field stores the branch name in English for identification and reporting purposes." },
    { name: "engBrCity", label: "ENGLISH BRANCH CITY", type: "string", size: 28, description: "This field maintains the city location of the branch in English for geographical reference." },
    { name: "someData", label: "ADDITIONAL BRANCH DATA", type: "string", size: 2, description: "This field records miscellaneous data related to branch operations or system configurations." },
    { name: "arabBrName", label: "ARABIC BRANCH NAME", type: "string", size: 30, description: "This field stores the branch name in Arabic for localization and documentation." },
    { name: "arabBrCity", label: "ARABIC BRANCH CITY", type: "string", size: 30, description: "This field maintains the city location of the branch in Arabic for regional accuracy." },
    { name: "alcoFlag", label: "ALLOWABLE CODE FLAG", type: "string", size: 1, description: "This field records a flag indicating whether specific operational codes are permitted for branch transactions." },
    { name: "stmtDay1", label: "STATEMENT PROCESSING DAY 1", type: "string", size: 2, description: "This field stores the first designated day for generating financial statements." },
    { name: "stmtDay2", label: "STATEMENT PROCESSING DAY 2", type: "string", size: 2, description: "This field maintains the second scheduled day for statement processing." },
    { name: "stmtDay3", label: "STATEMENT PROCESSING DAY 3", type: "string", size: 2, description: "This field records the third scheduled day for financial statement creation." },
    { name: "stmtDay4", label: "STATEMENT PROCESSING DAY 4", type: "string", size: 2, description: "This field stores the fourth allocated day for statement generation." },
    { name: "stmtDay5", label: "STATEMENT PROCESSING DAY 5", type: "string", size: 2, description: "This field maintains the fifth scheduled day for financial reporting." },
    { name: "stmtDay6", label: "STATEMENT PROCESSING DAY 6", type: "string", size: 2, description: "This field records the sixth designated day for transaction statement processing." },
    { name: "stmtDay7", label: "STATEMENT PROCESSING DAY 7", type: "string", size: 2, description: "This field stores the seventh scheduled day for branch statement execution." },
    { name: "stmtDay8", label: "STATEMENT PROCESSING DAY 8", type: "string", size: 2, description: "This field maintains the eighth day marked for financial documentation." },
    { name: "stmtDay9", label: "STATEMENT PROCESSING DAY 9", type: "string", size: 2, description: "This field records the ninth allocated day for statement processing operations." },
    { name: "stmtDayAToZ", label: "STATEMENT PROCESSING FOR SPECIAL DAYS (A TO Z)", type: "string", size: 52, description: "This field stores additional special case statement processing days beyond the usual sequence." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default cnd0dataBD
