// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const iad0data: SchemaTable = {
  name: "iad0data",
  description: "Interest accrual related accounts configuration.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field contains the branch number to which an account, that is having interest applied, must belong before the income/expense accounts defined by this\nrecord will be used." },
    { name: "currency", label: "CURRENCY", type: "string", size: 2, keys: { k1: 3 }, description: "Currency Reference (CC)" },
    { name: "ledgerCode", label: "LEGDER CODE", type: "string", size: 3, keys: { k1: 4 }, description: "Memorandum Account Reference(MMM)" },
    { name: "intReceivedAccNo1", label: "INTEREST RECEIVED ACCOUNT 1", type: "string", size: 14, description: "This is one of six interest received account numbers, These income accounts are used to record the interest received by the branch\nwhen debit interest is being applied to a customer's account, The value in the \"IN RECD NO' field on the GLAMD parameter\nfile, for the account to which interest is being applied, will determine which of the Six Interest Received accounts is to be used." },
    { name: "intReceivedAccNo2", label: "INTEREST RECEIVED ACCOUNT 2", type: "string", size: 14, description: "See INTEREST RECEIVED ACCOUNT1" },
    { name: "intReceivedAccNo3", label: "INTEREST RECEIVED ACCOUNT 3", type: "string", size: 14, description: "See INTEREST RECEIVED ACCOUNT1" },
    { name: "intReceivedAccNo4", label: "INTEREST RECEIVED ACCOUNT 4", type: "string", size: 14, description: "See INTEREST RECEIVED ACCOUNT1" },
    { name: "intReceivedAccNo5", label: "INTEREST RECEIVED ACCOUNT 5", type: "string", size: 14, description: "See INTEREST RECEIVED ACCOUNT1" },
    { name: "intReceivedAccNo6", label: "INTEREST RECEIVED ACCOUNT 6", type: "string", size: 14, description: "See INTEREST RECEIVED ACCOUNT1" },
    { name: "intPaidAccNo1", label: "INTEREST PAID ACCOUNT 1", type: "string", size: 14, description: "This is one of six interest paid account numbers, These expense accounts are used to record the interest received by the branch\nwhen debit interest is being applied to a customer's account, The value in the \"IN RECD NO' field on the GLAMD parameter\nfile, for the account to which interest is being applied, will determine which of the Six Interest Received accounts is to be used." },
    { name: "intPaidAccNo2", label: "INTEREST PAID ACCOUNT 2", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT1" },
    { name: "intPaidAccNo3", label: "INTEREST PAID ACCOUNT 3", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT1" },
    { name: "intPaidAccNo4", label: "INTEREST PAID ACCOUNT 4", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT1" },
    { name: "intPaidAccNo5", label: "INTEREST PAID ACCOUNT 5", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT1" },
    { name: "intPaidAccNo6", label: "INTEREST PAID ACCOUNT 6", type: "string", size: 14, description: "See INTEREST PAID ACCOUNT1" },
    { name: "serviceFeeAccNo", label: "SERVICE FEE ACCOUNT NUMBER", type: "numeric", size: 14, description: "Used to record and manage fees account Number for banking services", note: "Field newly added on 29/07/2025" },
    { name: "stdOrdCmAccNo", label: "STANDARD ORDER COMMISSION ACCOUNT NUMBER", type: "string", size: 14, description: "Likely used to capture commissions earned from standard customer orders", note: "Field newly added on 29/07/2025" },
    { name: "stdChqChAccNo", label: "STANDARD CHEQUE CLEARING ACCOUNT NUMBER", type: "string", size: 14, description: "Used to track the account number designated for standard cheque clearing transactions. Helps in routing and settlement of cheque payments.", note: "Field newly added on 29/07/2025" },
    { name: "defaultSuspenseAccNo", label: "DEFAULT SUSPENSE ACCOUNT NUMBER", type: "string", size: 14, description: "Temporary holding account for transactions with missing or unclear details.", note: "Field newly added on 29/07/2025" },
    { name: "retEarn", label: "RETAINED EARNINGS", type: "string", size: 11, description: "Represents accumulated profits retained by the bank rather than distributed.", note: "Field newly added on 29/07/2025" },
    { name: "soNpAccNo", label: "STATUTORY OR NON-PERFORMING ACCOUNT NUMBER", type: "string", size: 14, description: "Likely refers to an account used for statutory provisioning or tracking non-performing assets", note: "Field newly added on 29/07/2025" },
    { name: "upfrontIntAccNo", label: "UPFRONT INTEREST ACCOUNT NUMBER", type: "string", size: 14, description: "Used to record interest income received in advance, especially in loan products where interest is deducted upfront.", note: "Field newly added on 29/07/2025" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
    { name: "recType", label: "ACCOUNT TYPE", type: "string", size: 2, description: "ankmaster allows up to 90 different\naccount types (10-99) for detail accounts.\nAs Bankmaster is a parameter driven\nsystem, the individual user may alter the\ndefinition of the account types using the\nATABLE parameter file.\nBelow is a list of fixed account types within\nBankmaster.\nACCOUNT TYPE DESCRIPTION\n12-Foreign Exchange\nposition account\n13- Nostro account", note: "Removed from Table on 22/07/2025" },
  ],
}

export default iad0data
