// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const mmd0data: SchemaTable = {
  name: "mmd0data",
  description: "Has Balance sheet code MEMO (ledgerCode)",
  status: "Table modified",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "memoCode", label: "MEMO CODE", type: "string", size: 3, keys: { k1: 2, k2: 1 }, description: "Ledger code" },
    { name: "arabicDescription", label: "MEMO DESCRIPTION IN ARABIC", type: "string", size: 30, description: "This field maintains the detailed Arabic description of the memo ." },
    { name: "englishDescription", label: "MEMO DESCRIPTION IN ENGLISH", type: "string", size: 30, description: "This field records the English version of the memo description ." },
    { name: "crBalCode", label: "CREDIT BALANCE CODE", type: "string", size: 5, description: "This field contains the code representing the credit balance sheet code" },
    { name: "drBalCode", label: "DEBIT BALANCE CODE", type: "string", size: 5, description: "This field stores the code identifying the debit balance sheet code." },
    { name: "productType", label: "PRODUCT TYPE ASSOCIATION", type: "string", size: 1, description: "This field maintains the classification of the financial product linked to the memo record. Valid values\n1-fixture multiMaturity\n2-single maturity\n3-variable account\n4-Internal account\n5-FixedAssetAccount\n6-Maturities." },
    { name: "variableRateFlag", label: "VARIABLE RATE INDICATOR FLAG", type: "string", size: 1, description: "This field defines whether the memo is associated with a variable interest rate adjustment.\n0-No, 1-Yes" },
    { name: "processFlag", label: "PROCESSING STATUS FLAG", type: "string", size: 1, description: "This field maintain process flag." },
    { name: "transFlag", label: "TRANS FLAG", type: "string", size: 1, note: "Field newly added on 14/08/2025" },
    { name: "postFlag", label: "POST FLAG", type: "string", size: 1, note: "Field newly added on 14/08/2025" },
    { name: "refFlag", label: "REF FLAG", type: "string", size: 1, note: "Field newly added on 14/08/2025" },
    { name: "feeInFlag", label: "FEEINF LAG", type: "string", size: 1, note: "Field newly added on 14/08/2025" },
    { name: "tranCode1", label: "TRAN CODE1", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode2", label: "TRAN CODE2", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode3", label: "TRAN CODE3", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode4", label: "TRAN CODE4", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode5", label: "TRAN CODE5", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode6", label: "TRAN CODE6", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode7", label: "TRAN CODE7", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode8", label: "TRAN CODE8", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode9", label: "TRAN CODE9", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "tranCode10", label: "TRAN CODE10", type: "string", size: 4, note: "Field newly added on 14/08/2025" },
    { name: "incomeMemo", label: "INCO MEMEMO", type: "string", size: 3, note: "Field newly added on 14/08/2025" },
    { name: "expPerformingMemo", label: "EXP PERFORMING MEMO", type: "string", size: 3, note: "Field newly added on 14/08/2025" },
    { name: "expNonPerformingMemo", label: "EXP NON PERFORMING M EMO", type: "string", size: 3, note: "Field newly added on 14/08/2025" },
    { name: "treasuryMemo", label: "TREASURY MEMO", type: "string", size: 3, note: "Field newly added on 14/08/2025" },
    { name: "nonPerformingMemo", label: "NON PERFORMING MEMO", type: "string", size: 3, note: "Field newly added on 14/08/2025" },
    { name: "consumerLoanFlag", label: "CONSUMER LOAN ASSOCIATION FLAG", type: "string", size: 1, description: "This field stores whether the memo record pertains to consumer loan related accounts.\n1- Consumer Loans" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default mmd0data
