// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const omnitrnhist: SchemaTable = {
  name: "omnitrnhist",
  description: "This table captures the configuration and tracking of fund transfers directed to Tradenet accounts since 2008.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1, k2: 2 }, description: "Data Restored date" },
    { name: "dateTime", label: "DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field holds the date and time of transaction" },
    { name: "uniqNo", label: "UNIQUE Number", type: "string", size: 8, keys: { k1: 2 }, description: "This field holds uniques number assigned to the current transactions" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k2: 1 }, description: "This field holds the unique Omnibus number assigned to the customer’s account." },
    { name: "tdlAccNo", label: "TRADENET ACCOUNT NUMBER", type: "string", size: 20, description: "This field holds the TRADE NET account number." },
    { name: "bmRef", label: "BANKMASTER REFERENCE", type: "string", size: 20, description: "This field holds the BANKMASTER REFERENCE." },
    { name: "transAmt", label: "TRANSACTION AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field contains the total amount involved in transaction" },
    { name: "valueDate", label: "VALUE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date on which the\nransaction took effect" },
    { name: "postDate", label: "POSTING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the posting date as\nentered with the transaction at time of\nposting." },
    { name: "bmDate", label: "BANKMASTER DATE", type: "string", size: 8, format: "YYYYMMDD", description: "This field records the date on which the Transaaction happend in the bank account." },
    { name: "transType", label: "TRANSACTION TYPE", type: "string", size: 1, keys: { k1: 3 }, description: "1 - Debit; 2 - Credit" },
    { name: "status", label: "STATUS", type: "string", size: 1, description: "1 - Success 2 - Assumed Success" },
    { name: "narrative1", label: "NARRATIVE - LINE 1", type: "string", size: 25, description: "This field contains the first line of\nnarrative input at time of posting." },
    { name: "narrative2", label: "NARRATIVE - LINE 2", type: "string", size: 25, description: "This field contains the second line of\nnarrative input at time of posting." },
    { name: "narrative3", label: "NARRATIVE - LINE 3", type: "string", size: 25, description: "This field contains the third line of narrative\ninput at time of posting." },
    { name: "narrative4", label: "NARRATIVE - LINE 4", type: "string", size: 25, description: "This field contains the fourth line of\nnarrative input at time of posting." },
    { name: "narrative5", label: "NARRATIVE - LINE 5", type: "string", size: 25, description: "This field contains the fifth line of\nnarrative input at time of posting." },
    { name: "narrative6", label: "NARRATIVE - LINE 6", type: "string", size: 25, description: "This field contains the sixth line of narrative\ninput at time of posting." },
    { name: "forceFlag", label: "FORCE FLAG", type: "string", size: 1, description: "Always 'Y' default value" },
    { name: "errCode", label: "ERROR CODE", type: "string", size: 2, description: "This field contains the error code due to which current transactions is failed" },
    { name: "errMsg", label: "ERROR MESSAGE", type: "string", size: 200, description: "This field contains the description of the above error code" },
    { name: "userId", label: "USER ID.", type: "string", size: 3, description: "This field maintains the ID. of the teller\nwho posted the transaction." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default omnitrnhist
