// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stabclist: SchemaTable = {
  name: "stabclist",
  description: "Maintain the details about blocked customers at ANB and the banks in the Kingdom level.",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2, k2: 2 }, description: "Data Restored date" },
    { name: "ipNumber", label: "IP NUMBER", type: "string", size: 10, description: "This field stores the EDW Involved Party number" },
    { name: "abcListType", label: "ABC LIST TYPE", type: "string", size: 1, description: "This field categorizes the customer based on predefined classifications under the ABC list." },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 8, keys: { k1: 1 }, description: "This field maintains the unique identification number assigned to the customer." },
    { name: "custName", label: "CUSTOMER NAME", type: "string", size: 60, description: "This field stores the full name of the customer for identification and record" },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, description: "This field specifies the type of identification used (e.g., passport, national ID, business registration)." },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, keys: { k2: 1 }, description: "This field holds the unique identification number assigned to the customer based on the selected identification type." },
    { name: "reportedBank", label: "REPORTED BANK NAME", type: "string", size: 20, description: "This field records the name of the bank where the customer’s account or financial transactions were reported." },
    { name: "reportedDate", label: "REPORTED DATE", type: "string", size: 8, description: "This field stores the date when the customer details or transactions were reported.", note: "Date is stored Always 4 Digit converted from Date to String on 23/07/2025" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stabclist
