// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stacclog: SchemaTable = {
  name: "stacclog",
  description: "This table captures a chronological log of changes made to customer account details for audit and compliance purposes. Each entry includes the account number, type of update , old and new values, date and time of the change, and the user or system initiating the modification.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch where the account is created/modified." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user who created/updated the account." },
    { name: "dateTime", label: "DATE AND TIME", type: "string", size: 14, keys: { k1: 4 }, description: "This field records the date and time when creation or upate initiated." },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k2: 1 }, description: "This field holds the unique number assigned to the customer’s account." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the account record is newly created or modified. N - New ; U - Update" },
    { name: "supervisorId", label: "SUPERVISOR ID", type: "string", size: 10, description: "This field stores the ID of the supervisor employee iD who approved the creation / update." },
    { name: "accStatus", label: "ACCOUNT STATUS", type: "string", size: 2, description: "This field indicates the current status of the account during creation /update" },
    { name: "statementFreq", label: "STATEMENT FREQUENCY", type: "string", size: 2, description: "This is the frequency with which statements\nwill be printed by the Statement program\nValid values are:\n02 Daily.\n03 Weekly.\n04 Monthy.\n05 Quarterly.\n06 Half yearly.\n07 Yearly.\n01 Non-automatic (statement will be\n‘produced manually)." },
    { name: "checkBook", label: "CHECKBOOK REQUEST STATUS", type: "string", size: 1, description: "This field tracks whether a checkbook is issued or requested for the account." },
    { name: "droppedAcc", label: "DROPPED ACCOUNT STATUS", type: "string", size: 1, description: "This field indicates if the account has been dropped .\n0 - Not Dropped , 1 - Dropped" },
    { name: "accOpenDate", label: "ACCOUNT OPEN DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date when the account was first opened." },
    { name: "lastUpdateBmDate", label: "LAST UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date of the last update made to the account details." },
    { name: "bmUpdateStatus", label: "BANKMASTER UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered;\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "supervisorComments", label: "SUPERVISOR COMMENTS", type: "string", size: 200, description: "This field holds any remarks or feedback provided by the supervisor regarding account maintenance." },
    { name: "intApplication", label: "INTEREST APPLICATION STATUS", type: "string", size: 1, description: "Valid values are:\n0 Capitalise (i.e. credit/debit the amount\ntoffrom the account which accrued the\ninterest).\n1 Pay to another account.\n2 Payby cheque.\n3 Memorandum interest only. (This value\nis calculated for reporting purposes\nonly. Itis not applied to any account).\n4 Capitalise and leave resulting balances\non the account.\n5 Principal to Pay Account. Interest to\nNostro.\n6 Principal to Matching Account. Interest\nto Pay Account." },
    { name: "crIntRate", label: "CREDIT INTEREST RATE", type: "numeric", size: 9, format: "9,5", description: "For accounts accruing interest via the\nNormal or Savings methods, ths field holds\nthe credit interest rate on the account,\nFor accounts accruing interest via the\nDiscount, Security or Certificates of\nDeposit methods, this field is the yield rate\non the account, The yield rate is\nmemorandum for the Discount or Security\nmethod, but is part of the interest\ncalculation formula for the Certificates of\nDeposit method.\nValid values are: 0- 999.999999" },
    { name: "drIntRate", label: "DEBIT INTEREST RATE", type: "numeric", size: 9, format: "9,5", description: "For accounts accruing interest via the\nNormal or Savings methods, this field holds\nthe debit interest rate on the account.\nFor accounts accruing interest via the\nSecurity or Certificates of Deposit methods,\nthis field holds the coupon rate on the\naccount.\nFor accounts accruing interest via the\nDiscount method, this field holds the\ndiscount rate on the account.\nValid values are: 0 -999.999999" },
    { name: "payAccNo", label: "PAYMENT ACCOUNT NUMBER", type: "string", size: 14, description: "This field maintains the account number\nthat the interest will be paid to, or received\nfrom, when the \"INTEREST\nAPPLICATION METHOD\" field is set fo\nBry\nItis the number of the asset on the asset\nregister for lease accounts." },
    { name: "uniqueNo", label: "UNIQUE IDENTIFIER NUMBER", type: "string", size: 5, description: "This field holds a distinct number assigned to the account for tracking purposes." },
    { name: "uniqueSub", label: "UNIQUE SUB IDENTIFIER", type: "string", size: 2, description: "This field stores a secondary unique identifier related to the account." },
    { name: "statementDay", label: "STATEMENT GENERATION DAY", type: "string", size: 1, description: "This field determines the specific day of the month when account statements are generated. 0-Branch Statement Day ; 1 - Month End" },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field maintains the branch code associated with the customer’s account." },
    { name: "statusChanged", label: "ACCOUNT STATUS CHANGE INDICATOR", type: "string", size: 1, description: "This field tracks whether the status of the account has been modified. 0-Not Changed ; 1-Changed" },
    { name: "fromStatus", label: "PREVIOUS ACCOUNT STATUS", type: "string", size: 2, description: "This field stores the original status of the account before any changes were made." },
    { name: "toStatus", label: "UPDATED ACCOUNT STATUS", type: "string", size: 2, description: "This field indicates the new status of the account after modifications." },
    { name: "acctDesc", label: "ACCOUNT DESCRIPTION", type: "string", size: 30, description: "This field provides additional descriptive information about the account." },
    { name: "initialStatus", label: "INITIAL ACCOUNT STATUS", type: "string", size: 2, description: "This field records the initial status assigned to the account upon creation." },
    { name: "samaAccStatus", label: "SAMA ACCOUNT STATUS", type: "string", size: 2, description: "This field maintains the account status as per regulatory requirements defined by SAMA (Saudi Arabian Monetary Authority).00-Open;01-Inactive;02-Dormant;03-Unclaimed" },
    { name: "samaAccStatusChanged", label: "SAMA ACCOUNT STATUS CHANGE INDICATOR", type: "string", size: 1, description: "This field tracks whether the SAMA account status has been modified. 0-Not Changed ; 1-Changed" },
    { name: "fromSamaAccStatus", label: "PREVIOUS SAMA ACCOUNT STATUS", type: "string", size: 2, description: "This field stores the original regulatory status of the account." },
    { name: "toSamaAccStatus", label: "UPDATED SAMA ACCOUNT STATUS", type: "string", size: 2, description: "This field indicates the new regulatory status after modifications." },
    { name: "initialSamaStatus", label: "INITIAL SAMA ACCOUNT STATUS", type: "string", size: 2, description: "This field records the initial SAMA status assigned to the account upon creation." },
    { name: "accStatusChangeReason", label: "ACCOUNT STATUS CHANGE REASON", type: "string", size: 30, description: "This field provides the reason for the modification in account status." },
    { name: "dormantActivationUpd", label: "DORMANT ACCOUNT ACTIVATION UPDATE", type: "string", size: 1, description: "This field tracks whether a dormant account has been reactivated.0-No(Normal Update) ; 1-Yes(Updated to remove dormant restriction)" },
    { name: "creditLimit", label: "ACCOUNT CREDIT LIMIT", type: "string", size: 12, description: "This field maintains the maximum credit limit available on the account." },
    { name: "intLastRun", label: "LAST INTEREST CALCULATED", type: "string", size: 14, description: "This field stores the interest was last calculated for the Last execution." },
    { name: "intFreqCode", label: "INTEREST FREQUENCY CODE", type: "string", size: 3, description: "This field specifies how often interest is applied to the account." },
    { name: "intApplDay", label: "INTEREST APPLICATION DAY", type: "string", size: 2, description: "This field indicates the specific day of the month when interest is applied." },
    { name: "inactiveAccFlag", label: "INACTIVE ACCOUNT FLAG", type: "string", size: 1, description: "This field marks whether the account is inactive in the system. 0-Not dormant ; 1-dormant" },
    { name: "samaBlockAccStatusChanged", label: "SAMA BLOCKED ACCOUNT STATUS CHANGE INDICATOR", type: "string", size: 1, description: "This field tracks modifications in the SAMA.\nValid Values are: 01-YES;0-NO .\nThis is set as \"1\" when Branch admin lift the a/c status for a sama blocked account" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the account details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "string", size: 14, description: "This field maintains the timestamp for the last modification of the account record" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stacclog
