// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const staccopencard: SchemaTable = {
  name: "staccopencard",
  description: "This table contains the essential data elements required for printing the Account Open Card at the time of account initiation. Each entry includes customer identification details, account number, account type, branch code, account opening date, and associated product information.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique identifier code assigned to the customer’s bank branch." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user managing customer account details." },
    { name: "dateTime", label: "DATE AND TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the date and time of the latest update or transaction related to the customer’s account." },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 5, k2: 1 }, description: "This field stores the unique identification number assigned to the customer in the banking system." },
    { name: "printStatus", label: "PRINT STATUS", type: "string", size: 1, description: "This field tracks whether Term and coniditons doument or Form is printed or not . 1-Succesfully printed" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, description: "This field holds the unique number assigned to the customer’s bank account." },
    { name: "iban", label: "INTERNATIONAL BANK ACCOUNT NUMBER (IBAN)", type: "string", size: 24, description: "This field maintains the IBAN associated with the customer’s bank account for international transactions." },
    { name: "custName", label: "CUSTOMER NAME", type: "string", size: 30, description: "This field stores the full name of the customer for identification and record keeping purposes." },
    { name: "customerLang", label: "CUSTOMER PREFERRED LANGUAGE", type: "string", size: 1, description: "This field specifies the customer's chosen language for communication and account statements.0-Arabic ; 1-English" },
    { name: "custOpenDate", label: "CUSTOMER ACCOUNT OPEN DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date when the customer's bank account was first opened." },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field tracks the branch code linked to the customer’s account." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the customer account details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp for the latest modification of the customer record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default staccopencard
