// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stchqdel: SchemaTable = {
  name: "stchqdel",
  description: "Requested cheque books cancelled by branch.\nThis table logs cheque book issuance requests that were subsequently cancelled at the branch level. Each entry includes details such as customer ID, account number, request reference, cheque book type, date of original request, cancellation date, branch ID, reason for cancellation, and user ID of the staff who performed the action.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 2, k2: 1 }, description: "This field stores the unique account number associated with the cheque request." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field maintains the identifier for the branch handling the cheque deletion request." },
    { name: "chequeType", label: "CHEQUE TYPE", type: "string", size: 1, description: "This field specifies the type of cheque requested for deletion (e.g. 1- personal; 2- corporate)." },
    { name: "booksRequested", label: "CHEQUE BOOKS REQUESTED", type: "string", size: 2, description: "This field tracks the number of cheque books that were requested before deletion." },
    { name: "requestUserId", label: "REQUESTING USER ID", type: "string", size: 10, description: "This field stores the ID of the user who initiated the cheque deletion request." },
    { name: "requestDateTime", label: "REQUEST DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the date and time when the cheque deletion request was made." },
    { name: "requestStatus", label: "CHEQUE DELETE REQUEST STATUS", type: "string", size: 1, description: "This field indicates the current status of the deletion request 1 - Requested\n2 - Produced\n3 - Received by Branch\n4 - Issued to customer\n9 - Rejected by branch" },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field maintains the branch code associated with the customer’s account linked to the cheque deletion request." },
    { name: "deletedDateTime", label: "CHEQUE DELETION DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the exact date and time when the cheque was deleted from the system." },
    { name: "deletedUserId", label: "DELETING USER ID", type: "string", size: 10, description: "This field stores the ID of the user who processed the cheque deletion." },
    { name: "deletedReason", label: "REASON FOR CHEQUE DELETION", type: "string", size: 20, description: "This field tracks the reason for deleting the cheque (e.g., lost cheque, cancellation request, fraud prevention)." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the cheque deletion request details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp for the latest modification of the cheque deletion record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stchqdel
