// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stchqtab: SchemaTable = {
  name: "stchqtab",
  description: "This table serves as the central registry of all cheque book requests initiated by customers across channels . Each entry includes customer ID, account number, cheque book type , request date and time, status (e.g., pending, processed, cancelled), delivery method.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 2 }, description: "This field stores the unique account number associated with the cheque book request." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k2: 1 }, description: "This field maintains the identifier for the branch processing the cheque book request." },
    { name: "chequeType", label: "CHEQUE TYPE", type: "string", size: 1, description: "This field specifies the type of cheque requested for deletion (e.g. 1- personal; 2- corporate)." },
    { name: "booksRequested", label: "NUMBER OF CHEQUE BOOKS REQUESTED", type: "string", size: 2, description: "This field records the quantity of cheque books requested by the customer." },
    { name: "requestUserId", label: "REQUESTING USER ID", type: "string", size: 10, description: "This field stores the ID of the user who initiated the cheque book request." },
    { name: "requestDateTime", label: "REQUEST DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k2: 2 }, description: "This field records the timestamp when the cheque book request was made." },
    { name: "requestStatus", label: "CHEQUE BOOK REQUEST STATUS", type: "string", size: 1, description: "This field indicates the current status of the cheque book request\n1 - Requested\n2 - Produced\n3 - Received by Branch\n4 - Issued to customer\n9 - Rejected by branch" },
    { name: "producedDate", label: "CHEQUE BOOK PRODUCTION DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date when the cheque book was produced and prepared for issuance." },
    { name: "producedUserId", label: "USER ID OF CHEQUE BOOK PRODUCER", type: "string", size: 10, description: "This field identifies the user responsible for processing and generating the cheque book." },
    { name: "recdByBranchDate", label: "RECEIVED BY BRANCH DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field tracks the date when the cheque book was received at the customer’s branch for collection." },
    { name: "recdByBranchUserId", label: "USER ID OF BRANCH RECEIPT PROCESSOR", type: "string", size: 10, description: "This field maintains the identifier of the user who processed the cheque book receipt at the branch." },
    { name: "issuedToCustDate", label: "ISSUED TO CUSTOMER DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the cheque book was handed over to the customer." },
    { name: "issuedToCustUserId", label: "USER ID OF CHEQUE BOOK ISSUANCE PROCESSOR", type: "string", size: 10, description: "This field identifies the user who issued the cheque book to the customer." },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field maintains the branch code associated with the customer’s account linked to the cheque book request." },
    { name: "chequeNoFrom", label: "CHEQUE NUMBER RANGE (FROM)", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the starting cheque number in the issued cheque book." },
    { name: "chequeNoTo", label: "CHEQUE NUMBER RANGE (TO)", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the last cheque number in the issued cheque book." },
    { name: "reqDate", label: "CHEQUE REQUEST DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the customer formally requested a cheque book." },
    { name: "rejectedDate", label: "CHEQUE BOOK REJECTION DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field tracks the date when the cheque book request was rejected." },
    { name: "rejectedUserId", label: "USER ID OF REJECTOR", type: "string", size: 10, description: "This field maintains the identifier of the user who processed the rejection of the cheque book request." },
    { name: "rejectedReason", label: "REASON FOR CHEQUE BOOK REJECTION", type: "string", size: 20, description: "This field specifies the reason why the cheque book request was denied." },
    { name: "producedTime", label: "CHEQUE BOOK PRODUCTION TIME", type: "string", size: 6, description: "This field records the time when the cheque book was generated and finalized." },
    { name: "recdByBranchTime", label: "RECEIVED BY BRANCH TIME", type: "string", size: 6, description: "This field stores the exact time when the cheque book was received by the branch." },
    { name: "issuedToCustTime", label: "ISSUED TO CUSTOMER TIME", type: "string", size: 6, description: "This field tracks the precise time when the cheque book was handed over to the customer." },
    { name: "rejectedTime", label: "CHEQUE BOOK REJECTION TIME", type: "string", size: 6, description: "This field records the exact time when the cheque book request was rejected." },
    { name: "deliveryBranchCode", label: "DELIVERY BRANCH CODE", type: "string", size: 4, description: "This field maintains the identifier for the branch responsible for delivering the cheque book." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the cheque book details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp for the latest modification of the cheque book record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stchqtab
