// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stcreflog: SchemaTable = {
  name: "stcreflog",
  description: "This table captures all changes made to customer representatives used for identifying or linking customers across systems. Each entry logs the customer ID, reference type old and new values, timestamp of the change, and the user or system responsible for the update.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique identifier for the branch handling the reference record." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user managing the reference details." },
    { name: "dateTime", label: "DATE AND TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the timestamp when the reference record was created or updated." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the reference record is newly created or modified." },
    { name: "bmUpdateStatus", label: "BANK MANAGEMENT UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 5, k2: 1 }, description: "This field stores the unique identification number assigned to the customer in the reference system." },
    { name: "referenceNo", label: "REFERENCE NUMBER", type: "string", size: 4, keys: { k1: 6, k2: 2 }, description: "This field maintains the unique reference number assigned to the customer for verification purposes." },
    { name: "referenceReqdFor", label: "REFERENCE REQUIRED FOR", type: "string", size: 10, description: "This field specifies the purpose of the reference request.Reference for\n1 - Blind person\n2 - Veiled woman\n3 - Incompetent person\n4 - Minor\n5 - Minor with special circumstances\n6 - Mentally disabled" },
    { name: "referenceType", label: "REFERENCE TYPE", type: "string", size: 1, description: "This field categorizes the reference For 0-Personal Reference\n1-Legal reporesentative\n2-Foster parents\n3-Guardian" },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field stores the ID of the supervisor reviewing the reference request." },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field maintains the branch code linked to the customer’s reference record." },
    { name: "aFirstName", label: "ARABIC FIRST NAME", type: "string", size: 15, description: "This field holds the customer's first name in Arabic." },
    { name: "a2ndName", label: "ARABIC SECOND NAME", type: "string", size: 15, description: "This field maintains the customer's second name in Arabic." },
    { name: "a3rdName", label: "ARABIC THIRD NAME", type: "string", size: 15, description: "This field stores the customer's third name in Arabic." },
    { name: "aLastName", label: "ARABIC LAST NAME", type: "string", size: 15, description: "This field holds the customer's last name in Arabic." },
    { name: "aShortName", label: "ARABIC SHORT NAME", type: "string", size: 30, description: "This field stores a short form version of the customer's Arabic name." },
    { name: "eFirstName", label: "ENGLISH FIRST NAME", type: "string", size: 15, description: "This field maintains the customer's first name in English." },
    { name: "e2ndName", label: "ENGLISH SECOND NAME", type: "string", size: 15, description: "This field stores the customer's second name in English." },
    { name: "e3rdName", label: "ENGLISH THIRD NAME", type: "string", size: 15, description: "This field holds the customer's third name in English." },
    { name: "eLastName", label: "ENGLISH LAST NAME", type: "string", size: 15, description: "This field records the customer's last name in English." },
    { name: "eShortName", label: "ENGLISH SHORT NAME", type: "string", size: 30, description: "This field maintains the customer's short form English name." },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, description: "This field specifies the type of identification used\n(e.g., I - Saudi ID ; Q - Iqama ; P - passport)." },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, description: "This field stores the unique identification number associated with the reference record." },
    { name: "referenceStatus", label: "REFERENCE STATUS", type: "string", size: 1, description: "This field tracks whether the reference is active, pending, or expired." },
    { name: "referenceDisableDate", label: "REFERENCE DISABLE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the reference record was deactivated." },
    { name: "lastUpdateBmDate", label: "LAST UPDATED DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date when the reference record was last updated in the banking system." },
    { name: "recordChanged", label: "RECORD CHANGE STATUS", type: "string", size: 1, description: "This field indicates whether modifications were made to the reference record.Y-changed ; N-Not changed" },
    { name: "custOpenSource", label: "CUSTOMER OPEN SOURCE", type: "string", size: 1, description: "This field stores the origin of the customer record creation (e.g., online, branch, referral)." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field holds the identifier of the user who last modified the reference record.P-customer created through phone; otherValue-created through branc" },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the timestamp of the last modification to the reference record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stcreflog
