// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabPK: SchemaTable = {
  name: "stctltabPK",
  description: "Record Type :PK\nThis table maintains metadata for all package Code and name in English and Arabic",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "packageAccCode", label: "PACKAGE ACCOUNT CODE", type: "string", size: 2, keys: { k1: 2 }, description: "This field maintains a unique identifier representing the specific account package type." },
    { name: "arabicName", label: "PACKAGE NAME IN ARABIC", type: "string", size: 30, description: "This field stores the name of the package account in Arabic ." },
    { name: "englishName", label: "PACKAGE NAME IN ENGLISH", type: "string", size: 30, description: "This field records the name of the package account in English." },
    { name: "arbShortName", label: "SHORT PACKAGE NAME IN ARABIC", type: "string", size: 15, description: "This field holds a brief version of the package account name in Arabic." },
    { name: "engShortName", label: "SHORT PACKAGE NAME IN ENGLISH", type: "string", size: 15, description: "This field maintains a condensed form of the package account name in English." },
    { name: "splChqBkReqd", label: "SPECIAL CHEQUE BOOK REQUIRED STATUS", type: "string", size: 1, description: "This field indicates whether a specialized cheque book is required for accounts under this package.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "splAtmReqd", label: "SPECIAL ATM CARD REQUIRED STATUS", type: "string", size: 1, description: "This field specifies whether a unique ATM card is issued for package accounts.\nValid Values are :\n0 - No\n1 - Yes" },
    { name: "pinMailerHeading", label: "PIN MAILER HEADING DESCRIPTION", type: "string", size: 20, description: "This field records the heading or title used for PIN mailers associated with accounts in this package." },
    { name: "statementFrequency", label: "ACCOUNT STATEMENT FREQUENCY", type: "string", size: 1, description: "This field tracks how frequently account statements are generated for this package type\nValid Values are :\nQ - Quater\nH - half year" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the package account details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp of the most recent modification made to the package account record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabPK
