// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabRN: SchemaTable = {
  name: "stctltabRN",
  description: "Record Type :RN\nThis table maintains metadata for all Range Details",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "rangeNo", label: "RANGE NUMBER", type: "numeric", size: 4, keys: { k1: 2 }, description: "This field maintains the unique identifier assigned to a customer number range set." },
    { name: "startingNo", label: "STARTING NUMBER", type: "numeric", size: 7, description: "This field stores the initial number of the defined range." },
    { name: "endingNo", label: "ENDING NUMBER", type: "numeric", size: 7, description: "This field holds the final number of the range, marking its limit." },
    { name: "currentNo", label: "CURRENT NUMBER", type: "numeric", size: 7, description: "This field tracks the most recent number used within the range." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field records the identifier of the user who last modified the range details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp of the most recent update made to the range record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabRN
