// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabDC: SchemaTable = {
  name: "stctltabDC",
  description: "Record Type :DC\nThis table details sub-classifications under the broader SAMA category taxonomy, providing additional granularity for regulatory reporting and operational mapping.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "samaMainCategory", label: "SAMA MAIN DOCUMENT CATEGORY", type: "string", size: 2, keys: { k1: 2 }, description: "This field stores the primary classification of the document under SAMA (Saudi Arabian Monetary Authority) regulations." },
    { name: "samaSubCategory", label: "SAMA SUB DOCUMENT CATEGORY", type: "string", size: 2, description: "This field records the secondary classification of the document under SAMA guidelines." },
    { name: "documnetNo1", label: "DOCUMENT NUMBER 1", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo2", label: "DOCUMENT NUMBER 2", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo3", label: "DOCUMENT NUMBER 3", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo4", label: "DOCUMENT NUMBER 4", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo5", label: "DOCUMENT NUMBER 5", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo6", label: "DOCUMENT NUMBER 6", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo7", label: "DOCUMENT NUMBER 7", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo8", label: "DOCUMENT NUMBER 8", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo9", label: "DOCUMENT NUMBER 9", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo10", label: "DOCUMENT NUMBER 10", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo11", label: "DOCUMENT NUMBER 11", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo12", label: "DOCUMENT NUMBER 12", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo13", label: "DOCUMENT NUMBER 13", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo14", label: "DOCUMENT NUMBER 14", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo15", label: "DOCUMENT NUMBER 15", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo16", label: "DOCUMENT NUMBER 16", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo17", label: "DOCUMENT NUMBER 17", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo18", label: "DOCUMENT NUMBER 18", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo19", label: "DOCUMENT NUMBER 19", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "documnetNo20", label: "DOCUMENT NUMBER 20", type: "string", size: 3, description: "This field maintains the document identifier for this main/sub category", note: "Field newly added on 16/07/2025" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field stores the identifier of the user who last modified the document category details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the latest modification made to the document category record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabDC
