// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabSC: SchemaTable = {
  name: "stctltabSC",
  description: "Record Type :SC\nThis table maintains metadata for Sadad Configuration",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "systemCode", label: "SYSTEM CODE", type: "string", size: 4, keys: { k1: 2 }, description: "SAR - SAMA regulations." },
    { name: "arabicShortDesc", label: "SHORT DESCRIPTION IN ARABIC", type: "string", size: 30, description: "Provides a brief description of the system configuration in Arabic ." },
    { name: "englishShortDesc", label: "SHORT DESCRIPTION IN ENGLISH", type: "string", size: 30, description: "Records a brief description of the system configuration in English ." },
    { name: "ageMinorBecomesMajor", label: "AGE WHEN MINOR BECOMES MAJOR", type: "string", size: 2, description: "Specifies the legal age at which a minor is recognized as an adult in financial transactions." },
    { name: "acctFreezingYearForSpecialChild", label: "ACCOUNT FREEZING YEAR FOR SPECIAL CHILD", type: "string", size: 2, description: "Defines the number of years before freezing accounts related to special child classifications." },
    { name: "endOfSafarDate", label: "END OF SAFAR DATE", type: "string", size: 8, description: "Tracks the designated date marking the end of the Safar financial period or regulatory cycle." },
    { name: "noOfDaysForInactive", label: "NUMBER OF DAYS FOR INACTIVITY", type: "numeric", size: 3, description: "Specifies the timeframe before an account is marked inactive due to lack of transactions.", note: "Data Type change String to number on 06/08/2025" },
    { name: "noOfDaysForDormant", label: "NUMBER OF DAYS FOR DORMANCY", type: "numeric", size: 3, description: "Tracks the duration before an account transitions from inactive to dormant status.", note: "Data Type change String to number on 06/08/2025" },
    { name: "noOfMonthsForUnclaimed", label: "NUMBER OF MONTHS FOR UNCLAIMED ACCOUNTS", type: "numeric", size: 2, description: "Maintains the duration before an account is classified as unclaimed.", note: "Data Type change String to number on 06/08/2025" },
    { name: "roleCodeForSupervisor", label: "SUPERVISOR ROLE CODE", type: "string", size: 3, description: "Holds the identifier for the designated supervisor responsible for overseeing the system configuration." },
    { name: "unclaimedAccNoForMovingFundForId", label: "UNCLAIMED ACCOUNT FOR FUND MOVEMENT BASED ON ID", type: "string", size: 14, description: "Specifies the account number used for handling funds from unclaimed accounts associated with an ID." },
    { name: "accNoForMovingFundFromUnclaimedAcc", label: "ACCOUNT NUMBER FOR MOVING FUNDS FROM UNCLAIMED ACCOUNTS", type: "string", size: 14, description: "Identifies the target account for transferring funds from unclaimed accounts." },
    { name: "fundMovementSequenceNo", label: "FUND MOVEMENT SEQUENCE NUMBER", type: "string", size: 10, description: "Maintains the sequence identifier for tracking fund movements in compliance with regulations." },
    { name: "lastBackendProcessDate", label: "LAST BACKEND PROCESS DATE", type: "string", size: 8, description: "Stores the most recent date when backend processing actions were executed for system configuration." },
    { name: "startGroupHeadCustNo", label: "STARTING GROUP HEAD CUSTOMER NUMBER", type: "string", size: 7, description: "Holds the initial customer number for Group Head Accounts within the system." },
    { name: "endGroupHeadCustNo", label: "ENDING GROUP HEAD CUSTOMER NUMBER", type: "string", size: 7, description: "Maintains the final customer number for Group Head Accounts within the system." },
    { name: "startPensionCustNo", label: "STARTING PENSION CUSTOMER NUMBER", type: "string", size: 7, description: "Stores the first customer number assigned to pension" },
    { name: "endPensionCustNo", label: "ENDING PENSION CUSTOMER NUMBER", type: "string", size: 7, description: "Records the last customer number allocated to pension" },
    { name: "startOnlineCustNo", label: "STARTING ONLINE CUSTOMER NUMBER", type: "string", size: 7, description: "Tracks the initial customer number for online banking accounts." },
    { name: "endOnlineCustNo", label: "ENDING ONLINE CUSTOMER NUMBER", type: "string", size: 7, description: "Stores the final customer number for online banking accounts." },
    { name: "currentOnlineCustNo", label: "CURRENT ONLINE CUSTOMER NUMBER", type: "string", size: 7, description: "Identifies the latest customer number registered within the online banking system." },
    { name: "custActionPeriod", label: "CUSTOMER ACTION PERIOD", type: "string", size: 4, description: "Defines the regulatory timeframe during which customers must take action on their accounts to remain active." },
    { name: "stdOrdLimit", label: "STANDARD ORDER TRANSACTION LIMIT", type: "string", size: 5, description: "Specifies the transaction limit for standard orders processed under system regulations." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "Stores the identifier of the user who last modified the system configuration details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "Maintains the timestamp of the most recent update made to the system configuration record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabSC
