// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltab: SchemaTable = {
  name: "stctltab",
  description: "Record Type :AP->Application Module\nAS->Account status type info\nBS->Business type info\nDT->Deocument type info\nED->education code type info\nIA->Interest Application info\nID->ID type info\nLT->Mail type info\nMI->Income Code type info\nPF->Payment frequency info\nPM->payment mode info\nPO->Position type info\nPR->Profession Code type info\nPT->payment type info\nRC->Account status change reason\nRS->Returned Reason info\nSG->segmention info\nSN->SWIFT country info\nSP->SADAD payment type\nST->SOD type info\nSF->Satement Frequency Code info\nSM->Sama Main Category Code info\nSS->Sama Sub Category Code info\nSV-> Sadad Service code\nTR->Teller transaction type\nTP->Customer type info\nTT->Title Code type info\nname in English and Arabic name or description.",
  status: "stctltabSV modified to stctltab",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "RecordType", label: "RECORD TYPE", type: "string", size: 2, keys: { k1: 2 }, description: "Record Type :AP->\nAS->Account status type info\nBS->Business type info\nDT->Deocument type info\nED->education code type info\nIA->Interest Application info\nID->ID type info\nLT->Mail type info\nMI->Income Code type info\nPF->Payment frequency info\nPM->payment mode info\nPO->Position type info\nPR->Profession Code type info\nPT->payment type info\nRC->Account status change reason\nRS->Returned Reason info\nSG->segmention info\nSN->SWIFT country info\nSP->SADAD payment type\nST->SOD type info\nSF->Satement Frequency Code info\nSM->Sama Main Category Code info\nSS->Sama Sub Category Code info\nSY->Sama Sub Category Code info\nTP->Customer type info\nTT->Title Code type info", note: "Name changed from" },
    { name: "ctlCode", label: "CONTROL TYPE CODE", type: "string", size: 4, keys: { k1: 3 }, description: "This field maintains a unique identifier representing the specific type of record" },
    { name: "arabicName", label: "NAME IN ARABIC", type: "string", size: 30, description: "Stores Arebic Name for Perticular record and Control Tpe combination" },
    { name: "englishName", label: "NAME IN ENGLISH", type: "string", size: 30, description: "Stores English Name for Perticular record and Control Tpe combination" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field holds the identifier of the user who last modified the reference record" },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the timestamp of the last modification to the reference record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltab
