// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabCT: SchemaTable = {
  name: "stctltabCT",
  description: "Record Type :CT\nThis table captures master data related to cities as used in customer address records, branch assignments, and geo-location-based services. Each entry includes city code, city name in English and Arabic",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "cityCode", label: "CITY CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field maintains the unique identifier assigned to the city ." },
    { name: "arabicName", label: "CITY NAME IN ARABIC", type: "string", size: 30, description: "This field stores the name of the city in Arabic ." },
    { name: "englishName", label: "CITY NAME IN ENGLISH", type: "string", size: 30, description: "This field holds the name of the city in English ." },
    { name: "telAreaCode", label: "TELEPHONE AREA CODE", type: "string", size: 4, description: "This field records the standard area code used for telephone communications within the city." },
    { name: "idIssued", label: "IDENTIFICATION ISSUANCE LOCATION", type: "string", size: 1, description: "This field tracks whether identifications, such as national IDs, are issued for the city." },
    { name: "crIssued", label: "COMMERCIAL REGISTRATION ISSUANCE LOCATION", type: "string", size: 1, description: "This field maintains whether commercial registrations are processed for the city." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field stores the identifier of the user who last modified the city information." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field maintains the timestamp of the most recent modification to the city record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabCT
