// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stctltabCB: SchemaTable = {
  name: "stctltabCB",
  description: "Record Type :CB\nThis table maintains information about covering banks used for international or correspondent banking transactions.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "bankCode", label: "BANK CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field holds the coverying Bank code" },
    { name: "arabicName", label: "BANK NAME IN ARABIC", type: "string", size: 30, description: "This field stores the covering bank name in Arabic" },
    { name: "englishName", label: "BANK NAME IN ENGLISH", type: "string", size: 30, description: "This field records the covering bank details in English" },
    { name: "arabicAddress", label: "BANK ADDRESS IN ARABIC", type: "string", size: 30, description: "This field maintains the complete address of the CVR bank in Arabic." },
    { name: "englishAddress", label: "BANK ADDRESS IN ENGLISH", type: "string", size: 30, description: "This field holds the complete address of the CVR bank in English ." },
    { name: "cvrBankCode", label: "CVR BANK CODE", type: "string", size: 14, description: "ANB account number for covering bank" },
    { name: "bankAccNo", label: "BANK ACCOUNT NUMBER", type: "string", size: 20, description: "Covering Bank account for ANB" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field maintains the identifier of the user who last modified the CVR bank details." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the timestamp of the most recent modification to the CVR bank record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stctltabCB
