// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stfundtab: SchemaTable = {
  name: "stfundtab",
  description: "Movement of fund from Account to Unclaimed Accout from 2004\nThis table documents the transfer of idle or dormant balances from active customer accounts to designated unclaimed accounts in accordance with regulatory and internal policy timelines. Each entry includes customer ID, original account number, amount transferred, date of last activity, transfer date, unclaimed account reference, initiating system or user, and applicable reason code. Optional fields may include notification history, reversal handling parameters, and statutory holding period flags.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "fundMovementDate", label: "FUND MOVEMENT DATE", type: "string", size: 6, keys: { k1: 2 }, description: "Tracks the specific date on which funds were transferred to Unclaimed account" },
    { name: "unclaimedAccNo", label: "UNCLAIMED ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 3, k2: 1 }, description: "Stores the unique identifier of the unclaimed account to which the funds transferred" },
    { name: "customerAccNo", label: "CUSTOMER ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 4, k3: 1 }, description: "Records the destination customer account number where the funds were originated" },
    { name: "fundMovementAmount", label: "FUND MOVEMENT AMOUNT", type: "numeric", size: 14, description: "Stores the total monetary value transferred between accounts during the fund movement process." },
    { name: "fundMovementRef", label: "FUND MOVEMENT REFERENCE", type: "string", size: 10, description: "Stores the Reference Number for fund movement process.", note: "Field newly added on 06/08/2025" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stfundtab
