// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stheirtab: SchemaTable = {
  name: "stheirtab",
  description: "Maser file for Heir or Proxy details\nThis table serves as the authoritative source for managing heir or proxy relationships linked to customer accounts or profiles. Each entry includes customer ID, heir/proxy ID, full name, relationship type , identification details contact information, effective and expiry dates, supporting document references, and status It may also capture legal capacity, allocation percentages and digital cons",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 6, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 2 }, description: "This field stores the unique identifier of the customer associated with the heir." },
    { name: "heirNo", label: "HEIR NUMBER", type: "string", size: 4, keys: { k1: 3 }, description: "This field maintains the unique identifier assigned to the heir within the system." },
    { name: "heirType", label: "HEIR TYPE", type: "string", size: 1, description: "This field contains the classification of the heir (Valid Values are :\n0 - Heir\n1 - Proxy)" },
    { name: "aFirstName", label: "ARABIC FIRST NAME", type: "string", size: 15, description: "This field stores the heir’s first name in Arabic ." },
    { name: "aSecondName", label: "ARABIC SECOND NAME", type: "string", size: 15, description: "This field maintains the heir’s second name in Arabic." },
    { name: "aThirdName", label: "ARABIC THIRD NAME", type: "string", size: 15, description: "This field contains the heir’s third name in Arabic." },
    { name: "aLastName", label: "ARABIC LAST NAME", type: "string", size: 15, description: "This field records the heir’s last name in Arabic for documentation." },
    { name: "aShortName", label: "ARABIC SHORT NAME", type: "string", size: 30, description: "This field stores the abbreviated version of the heir’s name in Arabic." },
    { name: "eFirstName", label: "ENGLISH FIRST NAME", type: "string", size: 15, description: "This field maintains the heir’s first name in English." },
    { name: "eSecondName", label: "ENGLISH SECOND NAME", type: "string", size: 15, description: "This field contains the heir’s second name in English." },
    { name: "eThirdName", label: "ENGLISH THIRD NAME", type: "string", size: 15, description: "This field records the heir’s third name in English." },
    { name: "eLastName", label: "ENGLISH LAST NAME", type: "string", size: 15, description: "This field stores the heir’s last name in English for documentation." },
    { name: "eShortName", label: "ENGLISH SHORT NAME", type: "string", size: 30, description: "This field maintains the heir’s short name for identification purposes." },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, description: "This field contains the type of ID associated with the heir (I - Saudi Id H - Hafiza P - Passport F-Family registration)." },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, description: "This field records the unique identification number assigned to the heir." },
    { name: "activeStatus", label: "HEIR STATUS", type: "string", size: 1, description: "This field stores the current status of the heir (e.g., 0-Invalid ; 1-Valid)." },
    { name: "disabledDate", label: "HEIR DISABLE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date when the heir status was disabled or marked inactive." },
    { name: "lastUpdateBmDate", label: "LAST BANK MASTER UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the latest date the BANK MASTER updated the heir information." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field stores the unique code identifying the branch associated with the heir record." },
    { name: "custOpenSource", label: "CUSTOMER RECORD CREATION SOURCE", type: "string", size: 1, description: "This field stores the source through which the heir information was recorded( Valid values P-customer created through phone; OtherVialue-created through branch)" },
    { name: "proxyNo", label: "PROXY NUMBER", type: "string", size: 15, description: "This field maintains the unique identifier for any proxy assigned to the heir." },
    { name: "proxyDateType", label: "PROXY DATE FORMAT TYPE", type: "string", size: 1, description: "This field contains whether the proxy related dates are stored in Hijri or Gregorian format. (0-Hijri ; 1-Gregorian)" },
    { name: "proxyIssueDateH", label: "PROXY ISSUE DATE (HIJRI)", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the issuance date of the proxy in the Hijri calendar." },
    { name: "proxyIssueDateG", label: "PROXY ISSUE DATE (GREGORIAN)", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the issuance date of the proxy in the Gregorian calendar." },
    { name: "createdUserId", label: "CREATED USER IDENTIFIER", type: "string", size: 10, description: "This field maintains the ID of the user responsible for creating the heir record." },
    { name: "createdDateTime", label: "CREATED DATE & TIME OF ACTION", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp marking the heir information entry" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field maintains the identifier of the user who last modified the heir record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the most recent update to the heir information." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stheirtab
