// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stidtab: SchemaTable = {
  name: "stidtab",
  description: "Master file for ID mainenance\nThis table serves as the centralized repository for all customer identification documents maintained within the institution’s systems. Each entry includes customer ID, ID type (e.g., national ID, passport, residency permit), document number, country of issuance, issuing authority, issuance and expiry dates, and verification status. Additional attributes may include ID image reference, OCR capture status, linked biometric data, and activation state.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 2 }, description: "This field stores the unique identification number assigned to the customer." },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, keys: { k1: 3, k2: 1 }, description: "This field specifies the type of identification used .Valid Values are :-- I - Saudi ID\nQ - Iqama\nP - Passport\nH - Hafiza\nF - Family Registration\nC - CR NO\nS - Sama Authorization No\nV - Visa No\nT - Contract\nD - Diplomatic passport no\nL - License number\nM - Home country Id\nA - Approval Document Reference number\nE - Succession deed number" },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, keys: { k1: 4, k2: 2 }, description: "This field holds the unique number assigned to the customer based on the selected identification type." },
    { name: "idCategory", label: "IDENTIFICATION CATEGORY", type: "string", size: 1, keys: { k1: 5 }, description: "This field indicates the classification of the identification Valid Values are\nS-Signatory\nC-Customer\nW-oWner\nR-Reference\nJ-Joint\nH-Heirs" },
    { name: "idDateType", label: "IDENTIFICATION DATE TYPE", type: "string", size: 1, description: "This field specifies whether the identification dates are in Hijri or Gregorian format. 0 - Hijri ; 1 - Gregorian" },
    { name: "idIssuedAt", label: "ISSUING AUTHORITY", type: "string", size: 20, description: "This field stores the location or organization that issued the customer’s identification." },
    { name: "idIssueDateH", label: "ISSUE DATE (HIJRI)", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the issuance date of the customer’s identification in Hijri format." },
    { name: "idIssueDateG", label: "ISSUE DATE (GREGORIAN)", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the issuance date of the customer’s identification in Gregorian format." },
    { name: "idExpiryDateH", label: "EXPIRY DATE (HIJRI)", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the expiration date of the customer's identification in Hijri format." },
    { name: "idExpiryDateG", label: "EXPIRY DATE (GREGORIAN)", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the expiration date of the customer's identification in Gregorian format." },
    { name: "lastUpdateBmDate", label: "LAST UPDATED DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the last update made to the customer’s identification information." },
    { name: "idExpiryActionNotReqd", label: "EXPIRY ACTION NOT REQUIRED", type: "string", size: 1, description: "This field indicates whether an action upon expiry is necessary. 0-No ; 1-Yes" },
    { name: "grace1ActionTaken", label: "FIRST GRACE PERIOD ACTION", type: "string", size: 1, description: "This field tracks the action taken during the first grace period after identification expiry.0-Not Taken ; 1 - Taken" },
    { name: "grace1ActionDate", label: "FIRST GRACE PERIOD ACTION DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the first grace period action was taken.Blank when the above flag is 0" },
    { name: "grace2ActionTaken", label: "SECOND GRACE PERIOD ACTION", type: "string", size: 1, description: "This field tracks the action taken during the second grace period after identification expiry.0-Not Taken ; 1 - Taken" },
    { name: "grace2ActionDate", label: "SECOND GRACE PERIOD ACTION DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when the second grace period action was taken.Blank when the above flag is 0" },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the identification record is newly added or modified." },
    { name: "idRefNo", label: "IDENTIFICATION REFERENCE NUMBER", type: "string", size: 4, description: "This field holds a reference number associated with the customer's identification. N - New ; U - Update" },
    { name: "idRefName", label: "IDENTIFICATION REFERENCE NAME", type: "string", size: 30, description: "This field stores the name associated with the identification reference number." },
    { name: "iqamaType", label: "IQAMA TYPE", type: "string", size: 1, description: "This field specifies the type of residency permit (Iqama) issued to the customer. 0-Book ; 1-Plastic" },
    { name: "createdUserId", label: "CREATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who created the customer’s identification record." },
    { name: "createdDateTime", label: "CREATION DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHHH24MISS", description: "This field maintains the timestamp for when the identification record was created." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field holds the identifier of the user who last modified the identification record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHHH24MISS", description: "This field maintains the timestamp for the last modification of the identification record" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stidtab
