// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stsadctlER: SchemaTable = {
  name: "stsadctlER",
  description: "Internal to sadad payment module of CSD./RecordType of ER having sadad Error code and and there Englisha and Arebic names",
  status: "New Table",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "ctlCode", label: "CONTROL CODE", type: "string", size: 10, keys: { k1: 2 }, description: "This field maintains the unique identifier assigned to the control entity for regulatory or operational purposes." },
    { name: "arabicName", label: "CONTROL NAME IN ARABIC", type: "string", size: 50, description: "This field contains the Arabic description of the control entity for localization and reference." },
    { name: "englishName", label: "CONTROL NAME IN ENGLISH", type: "string", size: 50, description: "This field records the English description of the control entity for global accessibility." },
    { name: "otherDetails", label: "ADDITIONAL CONTROL DETAILS", type: "string", size: 100, description: "This field stores any supplementary information associated with the control record." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field stores the ID of the user who last updated the record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATED DATE TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the DATE TIME of the last updated the record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stsadctlER
