// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stsadctlSC: SchemaTable = {
  name: "stsadctlSC",
  description: "Internal to sadad payment module of CSD./RecordType of SC having sadad bill type, internal to CSD\nThis table captures internal transaction messages and interface-level activity between the Customer Service Desk (CSD) system and the SADAD Payment Module. Each entry includes CSD terminal ID, customer ID, internal transaction ID, SADAD biller code, reference number, amount, timestamp of initiation, payment status (initiated, processed, failed), operator ID, and system response codes. It may also track communication logs, middleware routing details, and correlation IDs for troubleshooting purposes.",
  status: "File Name Changed",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "billerId", label: "BILLER IDENTIFIER", type: "string", size: 4, keys: { k1: 2 }, description: "This field maintains the unique ID assigned to the biller for processing transactions." },
    { name: "paymentType", label: "PAYMENT TYPE", type: "string", size: 4, keys: { k1: 3 }, description: "This field contains the classification of payments handled by the biller" },
    { name: "arabicName", label: "BILLER NAME IN ARABIC", type: "string", size: 50, description: "This field records the name of the biller in Arabic ." },
    { name: "englishName", label: "BILLER NAME IN ENGLISH", type: "string", size: 50, description: "This field stores the name of the biller in English ." },
    { name: "reversalAllowed", label: "TRANSACTION REVERSAL PERMISSION STATUS", type: "string", size: 1, description: "This field maintains whether transaction reversals are permitted for payments associated with the biller.* 0-NO;1-YES" },
    { name: "otherDetails", label: "ADDITIONAL BILLER DETAILS", type: "string", size: 99, description: "This field contains any supplementary information linked to the biller record." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 20, description: "This field stores the ID of the user who last updated the record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATED DATE TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the DATE TIME of the last updated the record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stsadctlSC
