// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stsadadlog: SchemaTable = {
  name: "stsadadlog",
  description: "Details about SADAD bills paid from CSD.\nThis table logs all SADAD bill payment transactions initiated from the Customer Service Desk (CSD) channel. Each entry includes the customer ID, biller code, bill reference number, bill type , payment amount, payment date/time, transaction reference, CSD terminal ID, and operator ID. Additional fields may capture the channel source (e.g., in-branch, IVR support), payment status, and reversal flags if applicable.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch where the Sadad is created/modified." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user who created/updated the account." },
    { name: "dateTime", label: "TRANSACTION DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the date and time when creation or upate initiated." },
    { name: "tellerId", label: "TELLER IDENTIFIER", type: "string", size: 3, description: "This field contains the ID of the teller handling the transaction at the branch." },
    { name: "postingStatus", label: "TRANSACTION POSTING STATUS", type: "string", size: 1, description: "This field stores whether the transaction has been successfully posted, pending, or failed." },
    { name: "langInd", label: "LANGUAGE INDICATOR", type: "string", size: 5, description: "This field maintains the preferred language setting for processing and displaying transaction details." },
    { name: "companyId", label: "COMPANY IDENTIFIER", type: "string", size: 4, keys: { k2: 1 }, description: "This field records the unique ID representing the company or service provider involved in the transaction." },
    { name: "subscriptionNo", label: "SUBSCRIPTION NUMBER", type: "string", size: 19, keys: { k2: 2 }, description: "This field contains the customer's subscription number related to SADAD bill payments." },
    { name: "subsOrBillNo", label: "SUBSCRIPTION OR BILL NUMBER", type: "string", size: 1, description: "This field stores the unique bill reference number or subscription identifier for the transaction." },
    { name: "billAmt", label: "BILL AMOUNT", type: "numeric", size: 19, description: "This field maintains the total monetary value associated with the SADAD transaction." },
    { name: "paymentType", label: "PAYMENT TYPE", type: "string", size: 4, description: "This field records the classification of the payment (e.g., full payment, installment, partial payment)." },
    { name: "cashOrAcc", label: "CASH OR ACCOUNT TRANSACTION TYPE", type: "string", size: 1, description: "This field defines whether the payment is made via cash or deducted from an account." },
    { name: "drAccNo", label: "DEBIT ACCOUNT NUMBER", type: "string", size: 14, keys: { k3: 1 }, description: "This field stores the originating account number from which funds are debited." },
    { name: "contraAccNo", label: "CONTRA ACCOUNT NUMBER", type: "string", size: 14, description: "This field maintains the corresponding account number for balancing the transaction." },
    { name: "transType", label: "TRANSACTION TYPE", type: "string", size: 2, description: "This field defines whether the transaction is a payment, refund, adjustment, or other financial action." },
    { name: "serviceType", label: "SERVICE TYPE", type: "string", size: 4, description: "This field records the category of service being paid for (e.g., utility bills, telecom, government fees)." },
    { name: "transRefNo", label: "TRANSACTION REFERENCE NUMBER", type: "string", size: 10, description: "This field stores the system generated reference number for tracking the SADAD transaction." },
    { name: "valueDate", label: "VALUE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the effective date for processing the financial transaction." },
    { name: "transDateTime", label: "TRANSACTION PROCESSING DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp when the transaction was executed." },
    { name: "preOrPostpaid", label: "PREPAID OR POSTPAID INDICATOR", type: "string", size: 1, description: "This field defines whether the transaction is related to a prepaid or postpaid billing cycle." },
    { name: "bankTransId", label: "BANK TRANSACTION IDENTIFIER", type: "string", size: 32, description: "This field stores the reference number assigned by the bank for tracking purposes." },
    { name: "sadadTransId", label: "SADAD TRANSACTION IDENTIFIER", type: "string", size: 32, description: "This field maintains the unique identifier assigned by SADAD for regulatory tracking." },
    { name: "reversalTime", label: "REVERSAL PROCESS TIME", type: "string", size: 6, description: "This field records the timestamp at which a reversal was requested or processed." },
    { name: "reversalStatus", label: "REVERSAL STATUS", type: "string", size: 1, description: "This field stores whether the transaction reversal was successful, failed, or pending." },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field maintains the ID of the supervisor overseeing the transaction approval or correction process." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the transaction record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the most recent modification made to the SADAD transaction." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stsadadlog
