// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stsignlog: SchemaTable = {
  name: "stsignlog",
  description: "Activities on Account signatories maintenance\nThis table logs all events related to the setup, modification, or removal of signatories associated with customer accounts. Each entry captures the account number, signatory ID, signatory name, nature of change, role assigned, signing mandate , timestamp of change, and user or system initiating the action. Optional fields may include linked documentation, reason code, and approval workflow metadata.",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch where the address is created/modified." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user who created/updated the account." },
    { name: "dateTime", label: "DATE AND TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the date and time when creation or upate initiated." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the record is new or has been updated. N - New ; U - Update" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 5, k2: 1 }, description: "This field stores the unique identifier of the account linked to the signatory record." },
    { name: "signatoryNo", label: "SIGNATORY NUMBER", type: "string", size: 4, keys: { k1: 6, k2: 2 }, description: "This field maintains the unique identifier assigned to the signatory within the account structure." },
    { name: "bmUpdateStatus", label: "BANK MASTER UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered;\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "custBranchCode", label: "CUSTOMER BRANCH CODE", type: "string", size: 4, description: "This field contains the code identifying the branch associated with the customer's account." },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field stores the unique identifier of the supervisor overseeing the signatory process." },
    { name: "idType", label: "IDENTIFICATION TYPE", type: "string", size: 1, description: "This field maintains the category of ID associated with the signatory" },
    { name: "idNo", label: "IDENTIFICATION NUMBER", type: "string", size: 15, description: "This field records the unique identification number assigned to the signatory." },
    { name: "aFirstName", label: "ARABIC FIRST NAME", type: "string", size: 15, description: "This field stores the signatory’s first name in Arabic ." },
    { name: "a2ndName", label: "ARABIC SECOND NAME", type: "string", size: 15, description: "This field maintains the signatory’s second name in Arabic." },
    { name: "a3rdName", label: "ARABIC THIRD NAME", type: "string", size: 15, description: "This field contains the signatory’s third name in Arabic." },
    { name: "aLastName", label: "ARABIC LAST NAME", type: "string", size: 15, description: "This field records the signatory’s last name in Arabic for documentation." },
    { name: "aShortName", label: "ARABIC SHORT NAME", type: "string", size: 30, description: "This field stores the abbreviated version of the signatory’s name in Arabic." },
    { name: "eFirstName", label: "ENGLISH FIRST NAME", type: "string", size: 15, description: "This field maintains the signatory’s first name in English." },
    { name: "e2ndName", label: "ENGLISH SECOND NAME", type: "string", size: 15, description: "This field contains the signatory’s second name in English." },
    { name: "e3rdName", label: "ENGLISH THIRD NAME", type: "string", size: 15, description: "This field records the signatory’s third name in English." },
    { name: "eLastName", label: "ENGLISH LAST NAME", type: "string", size: 15, description: "This field stores the signatory’s last name in English for documentation." },
    { name: "eShortName", label: "ENGLISH SHORT NAME", type: "string", size: 30, description: "This field maintains the abbreviated version of the signatory’s English name." },
    { name: "diplomaticPpNo", label: "DIPLOMATIC PASSPORT NUMBER", type: "string", size: 15, description: "This field stores the diplomatic passport number associated with the signatory, if applicable." },
    { name: "reason", label: "REASON FOR SIGNATORY DESIGNATION", type: "string", size: 25, description: "This field maintains the justification or purpose for assigning the signatory role." },
    { name: "activeStatus", label: "SIGNATORY ACTIVE STATUS", type: "string", size: 1, description: "This field records whether the signatory is currently active or inactive in the account. 0-Inactive ; 1-Active" },
    { name: "signatureActionDate", label: "SIGNATORY ACTION DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date on which the signatory action was confirmed or modified.", note: "Data type changed from Timestamp to Date on 15/9/2025" },
    { name: "lastUpdateBmDate", label: "LAST BANK MASTER UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the latest date the BANK MASTER updated the signatory information." },
    { name: "recordChanged", label: "RECORD CHANGE STATUS", type: "string", size: 1, description: "This field contains whether modifications have been made to the signatory record. Y - Changed ; N - Not changed" },
    { name: "signatoryForOthers", label: "SIGNATORY FOR OTHER ACCOUNTS", type: "string", size: 1, description: "This field stores whether the signatory is authorized for multiple accounts. 1-YES ; 0-NO" },
    { name: "overrideOtherExpatSign", label: "OVERRIDE FOR OTHER EXPAT SIGNATORY STATUS", type: "string", size: 1, description: "This field maintains whether an override permission has been granted for expatriate signatories. 1-YES ; 0-NO" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field records the identifier of the user who last modified the signatory record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the most recent modification made to the SIGN transaction." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stsignlog
