// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const ststchqlog: SchemaTable = {
  name: "ststchqlog",
  description: "This table captures requests and processing details related to stop cheque instructions issued by account holders. Each entry includes account number, cheque number or range, request date and time, stop reason, request channel and customer ID. Additional fields may include the identity of the staff or system processing the request, status of the stop instruction (pending, executed, rejected), override approval reference (if applicable), and expiry or validity period of the instruction. These records ensure secure cheque handling, support fraud mitigation, and comply with both customer service protocols and regulatory reporting requirements.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch where the address is created/modified." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user who created/updated the account." },
    { name: "dateTime", label: "DATE AND TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the date and time when creation or upate initiated." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the record is new or has been updated. N - New ; U - Update" },
    { name: "bmUpdateStatus", label: "BANK MASTER UPDATE STATUS", type: "string", size: 1, description: "This field tracks whether updates have been processed in the banking system.\nValid Values are :\n0-entered;\n1-pending with supervisor\n2-pending with teller\n3-rejected\n9-completed" },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field holds the ID of the supervisor responsible for reviewing customer updates." },
    { name: "recType", label: "RECORD TYPE", type: "string", size: 2, keys: { k2: 1 }, description: "This field stores the classification of the stop cheque record maintained in the system." },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k2: 2 }, description: "This field maintains the unique identifier of the account associated with the stopped cheque." },
    { name: "chequeNo", label: "CHEQUE NUMBER", type: "string", size: 8, keys: { k2: 3 }, description: "This field contains the unique cheque number that has been requested for stoppage." },
    { name: "amount", label: "CHEQUE AMOUNT", type: "numeric", size: 14, description: "This field records the monetary value of the stopped cheque." },
    { name: "dateStop", label: "STOP REQUEST DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the date on which the cheque stoppage was requested." },
    { name: "payeeName", label: "PAYEE NAME", type: "string", size: 25, description: "This field maintains the name of the intended recipient of the stopped cheque." },
    { name: "chequeFrom", label: "CHEQUE NUMBER FROM", type: "string", size: 8, description: "This field contains the unique cheque number that has been requested for stoppage." },
    { name: "supervisorComments", label: "SUPERVISOR COMMENTS", type: "string", size: 200, description: "This field records any remarks or observations provided by the supervisor related to the cheque stoppage request." },
    { name: "lastUpdateBmDate", label: "LAST BRANCH MASTER UPDATE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the timestamp of the most recent modification made by the bank." },
    { name: "destroyFlag", label: "CHEQUE DESTRUCTION STATUS", type: "string", size: 1, description: "This field maintains whether the stopped cheque has been physically destroyed or retained." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the transaction record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the most recent modification made to the SIGN transaction." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default ststchqlog
