// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const sttdlog: SchemaTable = {
  name: "sttdlog",
  description: "This table captures all events and transactions related to the lifecycle of time deposit accounts. Each entry includes customer ID, time deposit account number, deposit amount, tenure , interest rate, interest type value date, maturity date, and maturity instructions.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k1: 2 }, description: "This field stores the unique code identifying the branch where the address is created/modified." },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3 }, description: "This field maintains the ID of the user who created/updated the account." },
    { name: "dateTime", label: "DATE AND TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 4 }, description: "This field records the date and time when creation or upate initiated." },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k3: 1 }, description: "This field stores the unique identifier assigned to the customer holding the term deposit." },
    { name: "tdAccNo", label: "TERM DEPOSIT ACCOUNT NUMBER", type: "string", size: 14, keys: { k2: 1 }, description: "This field maintains the unique number assigned to the term deposit account." },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the record is new or has been updated. N - New ; U - Update" },
    { name: "supervisorId", label: "SUPERVISOR IDENTIFIER", type: "string", size: 10, description: "This field contains the ID of the supervisor overseeing the term deposit transaction." },
    { name: "bmUpdateStatus", label: "BANK MASTER UPDATE STATUS", type: "string", size: 1, description: "This field stores whether the BANK MASTER has reviewed or updated the term deposit record." },
    { name: "tdCurrency", label: "TERM DEPOSIT CURRENCY", type: "string", size: 2, description: "This field maintains the currency type associated with the term deposit." },
    { name: "tdLedger", label: "TERM DEPOSIT LEDGER ACCOUNT", type: "string", size: 3, description: "This field records the ledger details for financial tracking of the deposit." },
    { name: "debitAccNo", label: "DEBIT ACCOUNT NUMBER", type: "string", size: 14, description: "This field stores the originating account number from which funds are debited for the deposit." },
    { name: "depositAmt", label: "DEPOSIT AMOUNT", type: "numeric", size: 14, description: "This field maintains the monetary value deposited in the term deposit account." },
    { name: "tenorType", label: "TENOR TYPE", type: "string", size: 1, description: "This field records the classification of the deposit tenure (e.g., fixed, flexible)." },
    { name: "tenorPeriod", label: "TENOR PERIOD", type: "string", size: 3, description: "This field stores the duration of the deposit in months, years, or days." },
    { name: "fundIntRate", label: "FUNDED INTEREST RATE", type: "numeric", size: 9, description: "This field maintains the initial agreed interest rate applied to the deposit." },
    { name: "exRate", label: "EXCHANGE RATE", type: "numeric", size: 14, description: "This field contains the applicable exchange rate if the deposit involves foreign currency." },
    { name: "maturityAmt", label: "MATURITY AMOUNT", type: "numeric", size: 14, description: "This field records the projected amount receivable at maturity, including interest." },
    { name: "maturityDate", label: "MATURITY DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field stores the expected date on which the term deposit matures." },
    { name: "overrideExRate", label: "OVERRIDE EXCHANGE RATE", type: "string", size: 1, description: "This field maintains flag for any manually adjusted exchange rate for the deposit. 0-No ; 1-Yes" },
    { name: "overrideIntRate", label: "OVERRIDE INTEREST RATE", type: "string", size: 1, description: "This field records flag any overridden interest rate applied to the deposit. 0-No ; 1-Yes" },
    { name: "orgFundIntRate", label: "ORIGINAL FUNDED INTEREST RATE", type: "numeric", size: 9, description: "This field stores the initial system set interest rate before any overrides." },
    { name: "orgExRate", label: "ORIGINAL EXCHANGE RATE", type: "numeric", size: 14, description: "This field maintains the original exchange rate before any adjustments." },
    { name: "autoRenewFlag", label: "AUTORENEWAL STATUS", type: "string", size: 1, description: "This field defines flag whether the term deposit is set to automatically renew at maturity." },
    { name: "supervisorComments", label: "SUPERVISOR COMMENTS", type: "string", size: 200, description: "This field records any remarks provided by the supervisor regarding the deposit details." },
    { name: "diffDays", label: "DIFFERENCE IN DAYS", type: "numeric", size: 3, description: "This field maintains the number of days between the term deposit start date and maturity date." },
    { name: "intAppln", label: "INTEREST APPLICATION METHOD", type: "string", size: 1, description: "This field stores the method used to apply interest (e.g., simple interest, compound interest)." },
    { name: "payAccNo", label: "PAYEE ACCOUNT NUMBER", type: "string", size: 14, description: "This field records the designated account for maturity payout or interest distribution." },
    { name: "valueDate", label: "VALUE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date on which the deposit transaction value is applied." },
    { name: "overrideValueDate", label: "OVERRIDE VALUE DATE FLAG", type: "string", size: 1, description: "This field stores any manually adjusted value date Flag for financial processing." },
    { name: "debitAmt", label: "DEBIT AMOUNT", type: "numeric", size: 14, description: "This field records the amount debited for funding the term deposit." },
    { name: "bookingDate", label: "BOOKING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the registration date of the term deposit in the system." },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the transaction record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the most recent modification made to the SIGN transaction." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default sttdlog
