// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stuser: SchemaTable = {
  name: "stuser",
  description: "All CSD users with their role\nA complete list of all Customer Service Desk (CSD) users and their roles is typically not publicly available",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 2 }, description: "This field stores the unique ID assigned to the user for system authentication and tracking." },
    { name: "liveStatus", label: "USER LIVE STATUS", type: "string", size: 1, description: "This field maintains whether the user is currently active or inactive within the system.Valid Values are :\n0 - Open/Reset\n1 - Active\n2 - Locked\n3 - Closed" },
    { name: "employeeNo", label: "EMPLOYEE NUMBER", type: "string", size: 8, description: "This field contains the unique employee number associated with the user." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, keys: { k2: 1 }, description: "This field records the branch where the user is registered." },
    { name: "firstName", label: "USER FIRST NAME", type: "string", size: 15, description: "This field stores the first name of the user for identification purposes." },
    { name: "secondName", label: "USER SECOND NAME", type: "string", size: 15, description: "This field maintains the middle name of the user if applicable." },
    { name: "thirdName", label: "USER THIRD NAME", type: "string", size: 15, description: "This field contains the third name of the user if recorded." },
    { name: "lastName", label: "USER LAST NAME", type: "string", size: 15, description: "This field records the last name of the user for use." },
    { name: "authorityLevel", label: "PRIMARY AUTHORITY LEVEL", type: "string", size: 20, description: "This field stores the user's primary system access level or role\n00 - CSO enquiry\n01 - CSO update\n02 - supervisor approvals\n31 - Teller\n32 - Chief Teller\n40 - card Enquiry\n41 - card request/update\n42 - card supervisor\n43 - card production user\n60 - Account enquiry\n61 - Account update\n62 - Account supervisor\n63 - SAMA STATUS UPDATE\n51 - table enquiry\n52 - table update\n90 - security enquiry\n91 - security update\n92 - HELP DESK user\n81 - Merchant statement\n82 - Manual CC blocking - CSO\n83 - Manual CC blocking - supervisor\n84 - Manual A/c blocking - CSO\n85 - Manual A/c blocking - supervisor\n86 - Allow restricted branch balance enquiry\n87 - Historical statement for deleted accounts\n93 - Cheque Processing\n94 - FTP historical statements to branches\n99 - USER to check the connectivity" },
    { name: "loginStatus", label: "LOGIN STATUS", type: "string", size: 1, description: "This field maintainsstaus of user logged in or not.\n1-Login Success" },
    { name: "lastLoginDateTime", label: "LAST LOGIN DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the user's most recent login activity." },
    { name: "langPreferred", label: "PREFERRED LANGUAGE", type: "string", size: 1, description: "This field contains the user's preferred language for system interactions." },
    { name: "globalUpdatePriv", label: "GLOBAL UPDATE PRIVILEGE STATUS", type: "string", size: 1, description: "This field stores whether the user has permission to perform system\n0 - Local\n1 - Global\n2 - Restricted Global" },
    { name: "loginIpAddress", label: "LOGIN IP ADDRESS", type: "string", size: 15, description: "This field maintains the IP address used by the user for logging into the system." },
    { name: "authorityLevel2", label: "SECONDARY AUTHORITY LEVEL", type: "string", size: 60, description: "This field records any secondary access level granted to the user for system operations." },
    { name: "bpUserId", label: "BUSINESS PROCESS USER IDENTIFIER", type: "string", size: 3, description: "This field contains the unique ID assigned to the user for business process" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the ID of the user who last updated the record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATED DATE TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field stores the DATE TIME of the last updated the record." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stuser
