// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stusrbrn: SchemaTable = {
  name: "stusrbrn",
  description: "Users who have inquiry on other branch accounts\nTo track user IDs who have performed inquiries on accounts belonging to other branches, you would typically rely on an audit or access log maintained by your core banking or customer service system",
  status: "Table modified",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 2 }, description: "This field stores the unique ID assigned to the user for system authentication and tracking." },
    { name: "noOfBranchesDefined", label: "NUMBER OF BRANCH SUPPORTED", type: "numeric", size: 3, description: "Number of branches supported/allowed for a user to work on a certain functionality.", note: "Data Type changed String to number on 06/08/2025" },
    { name: "Branchcode1", label: "BRANCH CODE 1", type: "string", size: 4, description: "User allowed Branch code 1" },
    { name: "Branchcode2", label: "BRANCH CODE 2", type: "string", size: 4, description: "User allowed in Branch code 2" },
    { name: "Branchcode3", label: "BRANCH CODE 3", type: "string", size: 4, description: "User allowed in Branch code 3" },
    { name: "Branchcode4", label: "BRANCH CODE 4", type: "string", size: 4, description: "User allowed in Branch code 4" },
    { name: "Branchcode5", label: "BRANCH CODE 5", type: "string", size: 4, description: "User allowed in Branch code 5" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default stusrbrn
