// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const stuserlog: SchemaTable = {
  name: "stuserlog",
  description: "Activities on userProfile\nThis table tracks changes and administrative actions performed on user profiles within the system. Each entry includes user ID, type of activity (e.g., creation, update, role reassignment, deactivation), modified fields (such as contact details, role assignment, access level), old and new values, timestamp of the change, initiating user or system process, and source channel (e.g., admin console, workflow automation). Optional fields may capture reason codes, approval reference (for privileged updates), and linked access control policy. These records provide full traceability of identity and access adjustments, ensuring compliance with information security frameworks and audit requirements.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "userId", label: "USER IDENTIFIER", type: "string", size: 10, keys: { k1: 3, k2: 1 }, description: "This field stores the unique ID assigned to the user for system authentication and tracking." },
    { name: "lastChangeDate", label: "LAST CHANGED DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field records the date when creation or upate initiated." },
    { name: "liveStatus", label: "USER LIVE STATUS", type: "string", size: 1, description: "This field maintains whether the user is currently active or inactive within the system." },
    { name: "employeeNo", label: "EMPLOYEE NUMBER", type: "string", size: 8, description: "This field contains the unique employee number associated with the user." },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field records the branch where the user is registered." },
    { name: "firstName", label: "USER FIRST NAME", type: "string", size: 15, description: "This field stores the first name of the user for identification purposes." },
    { name: "secondName", label: "USER SECOND NAME", type: "string", size: 15, description: "This field maintains the middle name of the user if applicable." },
    { name: "thirdName", label: "USER THIRD NAME", type: "string", size: 15, description: "This field contains the third name of the user if recorded." },
    { name: "lastName", label: "USER LAST NAME", type: "string", size: 15, description: "This field records the last name of the user for use." },
    { name: "authorityLevel", label: "PRIMARY AUTHORITY LEVEL", type: "string", size: 20, description: "This field stores the user's primary system access level or role\n00 - teller enquiry\n01 - teller update\n02 - supervisor approvals\n50 - table enquiry\n51 - table update\n90 - security enquiry\n91 - security update\n99 - SUPER_USER" },
    { name: "loginStatus", label: "LOGIN STATUS", type: "string", size: 1, description: "This field maintains whether the user is currently logged in or logged out of the system." },
    { name: "lastLoginDateTime", label: "LAST LOGIN DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", description: "This field records the timestamp of the user's most recent login activity." },
    { name: "langPreferred", label: "PREFERRED LANGUAGE", type: "string", size: 1, description: "This field contains the user's preferred language for system interactions." },
    { name: "globalUpdatePriv", label: "GLOBAL UPDATE PRIVILEGE STATUS", type: "string", size: 1, description: "This field stores whether the user has permission to perform system" },
    { name: "newOrUpdate", label: "NEW OR UPDATED RECORD", type: "string", size: 1, description: "This field indicates whether the record is new or has been updated. N - New ; U - Update" },
    { name: "authorityLevel2", type: "string", size: 60, note: "Format changed from date to string 07/09/2025" },
    { name: "bpUserId", label: "BUSINESS PROCESS USER IDENTIFIER", type: "string", size: 3, description: "This field contains the unique ID assigned to the user for business process", note: "Format changed from date to string 07/09/2025" },
    { name: "lastUpdateUser", label: "LAST UPDATED BY USER ID", type: "string", size: 10, description: "This field stores the identifier of the user who last modified the transaction record." },
    { name: "lastUpdateDateTime", label: "LAST UPDATE DATE & TIME", type: "timestamp", size: 14, format: "YYYYMMDDHH24MISS", keys: { k1: 2 }, description: "This field records the timestamp of the most recent modification made to the SIGN transaction." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
    { name: "password", label: "PASSWORD", type: "string", size: 20, description: "Current password of user", note: "Removed on 2/9/2025" },
    { name: "last10Password", label: "LAST PASSWORD 10", type: "string", size: 200, description: "Lat 10 Password are stored", note: "Removed on 2/9/2025" },
  ],
}

export default stuserlog
