// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const thd0data: SchemaTable = {
  name: "thd0data",
  description: "Transaction history - Record Type 1 and 2\nThe Transaction History file maintains a record of all transactions that have been entered since installation of Bank master.. At least one record is held for each posting which occurs - in the case of postings containing narrative to hold the information.",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "Data Restored date" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 1 }, description: "This field contains the account number to which this record relates." },
    { name: "transCounter", label: "TRANSACTION COUNTER", type: "string", size: 5, keys: { k1: 3 }, description: "The transaction counter is used to locate the\nrecord within the file.", note: "Field newly added on 28/05/2025" },
    { name: "postDate", label: "POSTING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 2 }, description: "This field maintains the posting date as\nentered with the transaction at time of\nposting." },
    { name: "valueDate", label: "VALUE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field maintains the date on which the\nransaction took effect" },
    { name: "transType", label: "TRANSACTION TYPE", type: "string", size: 2, description: "This field maintains the type of transaction,\nas defined on the TTABLE parameter file" },
    { name: "statmentFlag", label: "STATEMENT FLAG", type: "string", size: 1, description: "This field indicates whether the transaction\nis to be included on statements.\nValid values are:\n0 Print on statement.\n1 Do not print on statement." },
    { name: "transAmt", label: "TRANSACTION AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field maintains the amount of the\ntransaction.\nDecimal places are currency dependent." },
    { name: "accruedInt", label: "ACCRUED INTEREST", type: "numeric", size: 16, format: "16,3", description: "This field maintains the interest accrued by\nthe transaction." },
    { name: "transRef", label: "TRANSACTION REFERENCE", type: "string", size: 10, description: "This field maintains the reference which\naccompanied the transaction on posting.\nFor Foreign Exchange records, ths field\nholds the \"BASE CURRENCY EQUIVALENT’ amount." },
    { name: "narrative1", label: "NARRATIVE - LINE 1", type: "string", size: 25, description: "This field maintains the first line of the\nnarrative input at time of posting.\nFor Foreign Exchange records, the position\noccupied on the record byThis field is\nredefined by the \"FOREIGN EXCHANGE\nDEAL REFERENCE’ field." },
    { name: "forExInd", label: "FOREIGN EXCHANGE INDICATOR", type: "string", size: 1, description: "This field indicates whether the transaction\n‘was a foreign exchange transaction. Valid\nvalues are:\n0 No.\n1 Yes Foreign Exchange transaction.\n2 Yes- Foreign Exchange Profit and\nLoss Revaluation transaction.\n3 Multi Currency from BNK0OI Auto\nForeign Exchange Position posting." },
    { name: "serviceFee", label: "SERVICE FEE THIS TRANSACTION", type: "numeric", size: 16, format: "16,3", description: "This field contains the service fee accrued.\nItis only used if the *SERVIS FEE field on\nthe TTABLE parameter file was set to \"1\".\nNote:This field holds the gross interest\napplication amount when the\n\"TRANSACTION INDICATOR’ field is\nsetto \"I\". Decimal places are currency\ndependent." },
    { name: "AIXFlag", label: "INCLUDE IN SECOND INDEX", type: "string", size: 1, description: "Indicates whether to include this record in\nthe THI1BB index. Valid values are:\n0 Reconciliation records generated by\nprograms other than the Posting\nprogram (BNKO0O1).\n1 Posting program (BNKOO) sets the\nflag to \"1\" to indicate that a\nsuccessful reconciliation has\noccurred.\n2 Posting program (BNKOOI) sets the.\nflag to \"2\" to indicate the presence.\nof an alternate index record that has\nyet to be reconciled." },
    { name: "userId", label: "A USER LD.", type: "string", size: 3, description: "This field maintains the ID. of the teller\nwho posted the transaction." },
    { name: "supervisorId", label: "SUPERVISOR ID.", type: "string", size: 3, description: "(IF ANY)\nIf a supervisor's password was required\nduring the transaction, the supervisor LD.\nwill be stamped here." },
    { name: "transInd", label: "TRANSACTION INDICATOR", type: "string", size: 1, description: "Valid values are:\nI Interest appliction,\nB Blocking transaction.\nS Special repayment (Leasing only).\nE Effective rate change (BNK151 stamps\nit at end of day for tiered rate changes)." },
    { name: "adjustmentAmt", label: "NOMINAL/ADJUSTMENT AMOUNT", type: "numeric", size: 16, format: "16,3", description: "This field maintains:\n1. The nominal transaction amount for\nBills, C.D.’s and Securities.\n2. The adjustment amount calculated by\nthe Interest Recalculation program" },
    { name: "interfaceFlag", label: "INTERFACE FLAG", type: "string", size: 1, description: "Valid values are:\nA Transaction originates from the ATM\nsystem.\nB Transaction originates from the\nBranchPower system." },
    { name: "baseCurrEqui", label: "BASE CURRENCY EQUIVALENT", type: "numeric", size: 16, format: "16,3", description: "This field contains the base equivalent if the\ntransaction is a foreign exchange or cross\ncurrency transaction." },
    { name: "oppositeCurrCode", label: "OPPOSITE CURRENCY CODE", type: "string", size: 2, description: "This field is only relevant to Foreign\nExchange currency records. It is the other\ncurrency in a Foreign Exchange deal." },
    { name: "contraAccNo", label: "ACCOUNT NUMBER", type: "string", size: 14, description: "This field contains the account number to which this record relates." },
    { name: "finnoneUserId", label: "FIN ONE USER ID", type: "string", size: 8 },
    { name: "narrative2", label: "NARRATIVE - LINE 2", type: "string", size: 25, description: "This field contains the second line of\nnarrative input at time of posting." },
    { name: "narrative3", label: "NARRATIVE - LINE 3", type: "string", size: 25, description: "This field contains the third line of narrative\ninput at time of posting." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default thd0data
