// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const tid0data: SchemaTable = {
  name: "tid0data",
  description: "Holds the Title code and description like Mr, Mrs, etc\nThis table maintains standardized title codes and their corresponding descriptions used across customer and user records. Each entry includes the title code , title description, and language.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "Data Restored date", note: "K1,1" },
    { name: "titleCode", label: "TITLE CODE", type: "string", size: 2, description: "Stores the unique identifier assigned to a specific title or designation (e.g., Mr., Mrs., Dr.).", note: "K1,2" },
    { name: "englishName", label: "TITLE NAME IN ARABIC", type: "string", size: 30, description: "Provides the title description in Arabic ." },
    { name: "arabicName", label: "TITLE NAME IN ENGLISH", type: "string", size: 30, description: "Records the title description in English ." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default tid0data
