// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const txd0data: SchemaTable = {
  name: "txd0data",
  description: "Daily file having all limits exceeded each day.\nThis table contains details of all limits exceeded eachday",
  fields: [
    { name: "BankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "accNo", label: "ACCOUNT NUMBER", type: "string", size: 14, keys: { k1: 2 }, description: "This field contains the account number on\nwhich the limit was exceeded." },
    { name: "exceptionCode", label: "EXCEPTION CODE", type: "string", size: 2, description: "This code identifies the type of limit excess\nwhich occurred. Valid values are:\n80 Account limit exceeded.\n81 Customer limit exceeded.\n82 Group limit exceeded.\n83 Line limit exceeded.\n85 Customer Foreign Exchange limit\nexceeded.\n86 Group Foreign Exchange limit\nexceeded.\n90 Invalid customer nmber.\n91 Invalid group number.\n92 Too many group leaders. (Maximum\nnesting=10).\n93 Line not found." },
    { name: "transNum", label: "TRANSACTION NUMBER", type: "numeric", size: 5, description: "TRANSACTION NUMBER" },
    { name: "exceededLimCustNum", label: "CUSTOMER/FACILITY/GROUP NUMBER", type: "string", size: 6, description: "This field contains the customer facility or\nline number on which the limit was" },
    { name: "postDate", label: "POSTING DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field contains the date on which the\ntransaction was posted." },
    { name: "valueDate", label: "VALUE DATE", type: "date", size: 8, format: "YYYYMMDD", description: "This field contains the value date of the\ntransaction" },
    { name: "transType", label: "TRANSACTION TYPE", type: "numeric", size: 2, description: "This field contains the transaction type used\nto post the transaction." },
    { name: "transAmt", label: "TRANSACTION AMOUNT", type: "numeric", size: 14, description: "This field contains the amount that was\nposted." },
    { name: "newBal", label: "NEW BALANCE", type: "numeric", size: 18, description: "This field contains the new balance as a\nresut of the tranaction." },
    { name: "facilityNum", label: "FACILITY NUMBER", type: "numeric", size: 6, description: "This field contains the number of the\nfacility, if a facility limit was exceeded." },
    { name: "valueOfLimitExceeded", label: "LIMIT", type: "numeric", size: 14, description: "This field contains the value of the limit\nexceeded." },
    { name: "limitName", label: "LIMIT NAME", type: "string", size: 35, description: "This field contains the name of the limit exceeded." },
    { name: "partitionNum", label: "PTN NUMBER", type: "string", size: 3, description: "This field contains the number of the\n‘partition from which the transaction was\nposted." },
    { name: "userId", label: "USER IDENTITY CODE", type: "string", size: 3, description: "This field contains the LD. of the user\nwhich posted the transaction." },
    { name: "refNum", label: "REFERENCE/DEAL NUMBER", type: "string", size: 10, description: "This field contains the reference number of\nthe transaction or deal." },
    { name: "limitCurrCode", label: "LIMIT CURRENCY CODE", type: "string", size: 2, description: "This field contains the currency code that\nthe limit is monitored against." },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default txd0data
