// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

import type { SchemaTable } from '../types'

const und0data: SchemaTable = {
  name: "und0data",
  description: "Customer risk class configuration and limit flag.\nThis table defines the configuration of customer risk levels and associated operational constraints, as mandated by regulatory frameworks and internal policies .Each entry includes customer ID, risk category , risk scoring methodology reference, date of classification, and classification authority . It also includes limit flags governing product or transaction thresholds, such as maximum transaction amount, international remittance eligibility, or investment access levels. Optional attributes may include review frequency, reassessment triggers, and linked risk exposure limits.",
  fields: [
    { name: "bankingDate", label: "BANKING DATE", type: "date", size: 8, format: "YYYYMMDD", keys: { k1: 1 }, description: "Data Restored date" },
    { name: "branchCode", label: "BRANCH CODE", type: "string", size: 4, description: "This field contain branch code" },
    { name: "custNo", label: "CUSTOMER NUMBER", type: "string", size: 7, keys: { k1: 2 }, description: "stores the unique identification number assigned to the customer." },
    { name: "riskClass", label: "RISK CLASS", type: "string", size: 2, description: "This field contain risk class" },
    { name: "limitFlag", label: "LIMIT FLAG", type: "string", size: 1, description: "This field contain limit flag" },
    { name: "FileCount", label: "File Count", type: "numeric", size: 12, format: "present in last record only", description: "This field contains Count required between Cludera and BM" },
    { name: "FileName", label: "File Name", type: "string", size: 30, format: "present in last record only", description: "This field contains Name of file required between Cludera and BM" },
  ],
}

export default und0data
