// Generated by bank-ui/scripts/extract-schema.py from
// docs/BM archival Version 9.xlsx
// Do not edit by hand — re-run the script after the workbook changes.

export { default as aad0data } from './tables/aad0data'
export { default as acaptrTL } from './tables/acaptrTL'
export { default as acaptrTR } from './tables/acaptrTR'
export { default as acrcal } from './tables/acrcal'
export { default as acd0data } from './tables/acd0data'
export { default as amd0data } from './tables/amd0data'
export { default as ank0dataBR } from './tables/ank0dataBR'
export { default as ank0dataGW } from './tables/ank0dataGW'
export { default as ank0dataMM } from './tables/ank0dataMM'
export { default as ank0dataXC } from './tables/ank0dataXC'
export { default as ard0data } from './tables/ard0data'
export { default as bcd0data } from './tables/bcd0data'
export { default as bmdft01 } from './tables/bmdft01'
export { default as bmglsum } from './tables/bmglsum'
export { default as brcode } from './tables/brcode'
export { default as bsf0data } from './tables/bsf0data'
export { default as ccblklog } from './tables/ccblklog'
export { default as ccpayhist } from './tables/ccpayhist'
export { default as cnd0dataAC } from './tables/cnd0dataAC'
export { default as cnd0dataBD } from './tables/cnd0dataBD'
export { default as cnd0dataBR } from './tables/cnd0dataBR'
export { default as cnd0dataC0 } from './tables/cnd0dataC0'
export { default as cnd0dataCL } from './tables/cnd0dataCL'
export { default as cnd0dataMR } from './tables/cnd0dataMR'
export { default as cnd0dataNR } from './tables/cnd0dataNR'
export { default as cnd0dataSP00 } from './tables/cnd0dataSP00'
export { default as cnd0dataSP01 } from './tables/cnd0dataSP01'
export { default as cnd0dataTR } from './tables/cnd0dataTR'
export { default as cnd0dataXC } from './tables/cnd0dataXC'
export { default as cpd0data } from './tables/cpd0data'
export { default as crd0data } from './tables/crd0data'
export { default as ctd0data } from './tables/ctd0data'
export { default as dcd0data } from './tables/dcd0data'
export { default as dzd0data } from './tables/dzd0data'
export { default as fud0data } from './tables/fud0data'
export { default as gld0data } from './tables/gld0data'
export { default as gld0data05 } from './tables/gld0data05'
export { default as iad0data } from './tables/iad0data'
export { default as isd0data } from './tables/isd0data'
export { default as letter } from './tables/letter'
export { default as mmd0data } from './tables/mmd0data'
export { default as omnitrnhist } from './tables/omnitrnhist'
export { default as pyd0data } from './tables/pyd0data'
export { default as rid0data } from './tables/rid0data'
export { default as shd0data } from './tables/shd0data'
export { default as sod0data } from './tables/sod0data'
export { default as srvfeelog } from './tables/srvfeelog'
export { default as srvfeectl } from './tables/srvfeectl'
export { default as stabclist } from './tables/stabclist'
export { default as staccblk } from './tables/staccblk'
export { default as stacclog } from './tables/stacclog'
export { default as staccopencard } from './tables/staccopencard'
export { default as staddrlog } from './tables/staddrlog'
export { default as staddrtab } from './tables/staddrtab'
export { default as stcaltab } from './tables/stcaltab'
export { default as stcardlog } from './tables/stcardlog'
export { default as stcardtab } from './tables/stcardtab'
export { default as stchqdel } from './tables/stchqdel'
export { default as stchqtab } from './tables/stchqtab'
export { default as stcreflog } from './tables/stcreflog'
export { default as stcreftab } from './tables/stcreftab'
export { default as stctltabBD } from './tables/stctltabBD'
export { default as stctltabBI } from './tables/stctltabBI'
export { default as stctltab } from './tables/stctltab'
export { default as stctltabCB } from './tables/stctltabCB'
export { default as stctltabCC } from './tables/stctltabCC'
export { default as stctltabCT } from './tables/stctltabCT'
export { default as stctltabDC } from './tables/stctltabDC'
export { default as stctltabMM } from './tables/stctltabMM'
export { default as stctltabNA } from './tables/stctltabNA'
export { default as stctltabPK } from './tables/stctltabPK'
export { default as stctltabRN } from './tables/stctltabRN'
export { default as stctltabSC } from './tables/stctltabSC'
export { default as stctltabSS } from './tables/stctltabSS'
export { default as stctltabSR } from './tables/stctltabSR'
export { default as stctltabXC } from './tables/stctltabXC'
export { default as stcustlog } from './tables/stcustlog'
export { default as stcusttab } from './tables/stcusttab'
export { default as stfundtab } from './tables/stfundtab'
export { default as stheirlog } from './tables/stheirlog'
export { default as stheirtab } from './tables/stheirtab'
export { default as stidlog } from './tables/stidlog'
export { default as stidtab } from './tables/stidtab'
export { default as stjointlog } from './tables/stjointlog'
export { default as stjointtab } from './tables/stjointtab'
export { default as stownlog } from './tables/stownlog'
export { default as stowntab } from './tables/stowntab'
export { default as stsadadlog } from './tables/stsadadlog'
export { default as stsadctlSC } from './tables/stsadctlSC'
export { default as stsadctlER } from './tables/stsadctlER'
export { default as stsamaacc } from './tables/stsamaacc'
export { default as stseclog } from './tables/stseclog'
export { default as stsignlog } from './tables/stsignlog'
export { default as stsigntab } from './tables/stsigntab'
export { default as stsodlog } from './tables/stsodlog'
export { default as ststchqlog } from './tables/ststchqlog'
export { default as sttdlog } from './tables/sttdlog'
export { default as stuser } from './tables/stuser'
export { default as stuserlog } from './tables/stuserlog'
export { default as stusrbrn } from './tables/stusrbrn'
export { default as thd0data } from './tables/thd0data'
export { default as thd0data1 } from './tables/thd0data1'
export { default as tid0data } from './tables/tid0data'
export { default as tr0data } from './tables/tr0data'
export { default as txd0data } from './tables/txd0data'
export { default as und0data } from './tables/und0data'

export const TABLE_NAMES: string[] = [
  "aad0data",
  "acaptrTL",
  "acaptrTR",
  "acrcal",
  "acd0data",
  "amd0data",
  "ank0dataBR",
  "ank0dataGW",
  "ank0dataMM",
  "ank0dataXC",
  "ard0data",
  "bcd0data",
  "bmdft01",
  "bmglsum",
  "brcode",
  "bsf0data",
  "ccblklog",
  "ccpayhist",
  "cnd0dataAC",
  "cnd0dataBD",
  "cnd0dataBR",
  "cnd0dataC0",
  "cnd0dataCL",
  "cnd0dataMR",
  "cnd0dataNR",
  "cnd0dataSP00",
  "cnd0dataSP01",
  "cnd0dataTR",
  "cnd0dataXC",
  "cpd0data",
  "crd0data",
  "ctd0data",
  "dcd0data",
  "dzd0data",
  "fud0data",
  "gld0data",
  "gld0data05",
  "iad0data",
  "isd0data",
  "letter",
  "mmd0data",
  "omnitrnhist",
  "pyd0data",
  "rid0data",
  "shd0data",
  "sod0data",
  "srvfeelog",
  "srvfeectl",
  "stabclist",
  "staccblk",
  "stacclog",
  "staccopencard",
  "staddrlog",
  "staddrtab",
  "stcaltab",
  "stcardlog",
  "stcardtab",
  "stchqdel",
  "stchqtab",
  "stcreflog",
  "stcreftab",
  "stctltabBD",
  "stctltabBI",
  "stctltab",
  "stctltabCB",
  "stctltabCC",
  "stctltabCT",
  "stctltabDC",
  "stctltabMM",
  "stctltabNA",
  "stctltabPK",
  "stctltabRN",
  "stctltabSC",
  "stctltabSS",
  "stctltabSR",
  "stctltabXC",
  "stcustlog",
  "stcusttab",
  "stfundtab",
  "stheirlog",
  "stheirtab",
  "stidlog",
  "stidtab",
  "stjointlog",
  "stjointtab",
  "stownlog",
  "stowntab",
  "stsadadlog",
  "stsadctlSC",
  "stsadctlER",
  "stsamaacc",
  "stseclog",
  "stsignlog",
  "stsigntab",
  "stsodlog",
  "ststchqlog",
  "sttdlog",
  "stuser",
  "stuserlog",
  "stusrbrn",
  "thd0data",
  "thd0data1",
  "tid0data",
  "tr0data",
  "txd0data",
  "und0data",
]
