// The bank's mark as a PNG, for the workbook the statement screens export.
//
// BankLogo.tsx draws the same artwork as inline SVG, which is right for the
// screen and for the browser's print. A spreadsheet cannot take it: OOXML
// drawings carry raster images, and Excel's SVG support arrived late and still
// wants a raster fallback alongside — so the mark is rasterised once, here,
// rather than at export time.
//
// It is the SAME path data, rendered at 171x72 and placed at 57x24, i.e. three
// times the size it is shown at so it stays crisp on a printed workbook. The
// background is transparent; the card header behind it supplies the fill.
//
// Regenerated by rasterising the path in BankLogo.tsx if the mark ever changes
// — the two must not drift apart, since a printed statement and an exported one
// are the same document.

const BANK_LOGO_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAKsAAABICAYAAACJOAU1AAAFOUlEQVR4nOydC1LbMBCGZU8vBByA9EaFCwAXKL0R6QEoN8L1' +
  'yjZxEsfRanf1MP8304HpJMGSfm3W2od/OLBdHv51wa/tmp/uz83eFUzrAKgEiBVUA8QKqgFiBdUAsYJqgFhBNUCsoBogVlAN' +
  'ECuoBogVVAPECqoBYgXVALGCaoBYQTVArKAafrgS+PWxc+3n7uz/f989uxxM19O1906L5vPv1++f7b703NESaVwuSBCNe3Ku' +
  '2119bdO9+J+W4uVcjxY0LkvhWiVf01xl2Gzpxfr4/txPzJOLhRZYW7TSa5JitRmtxDp9rsVarJDOZyVB0CCloqD3P3y8OS1y' +
  'C5Wgv0//6FpKh6zqhF+Lfk0TXbe9WGlwJC5VQXQ7FcGWINQ5iRc/iqV7i0TXbSfWSaRN92bjBwoFS9dXklDnlGxl1246jUWr' +
  'L1Zzkc7pPz92YvzNVMEUK9iANTUSrZ5Yk4p0Bk3M3I8KwU9iwmuMpTTBcudZWbRyseYS6ZzSraSEmM1oxZK/GoLSppOJlS4g' +
  'p0i/6P8+Z0E1D/tTQHNcgmAl86ZgZePEanKHL4RlXStwAU4p4ttDYd4EVpYfbvXHPZ3RxDX74WdJYuqvaR4qjcVbJcm4xm+P' +
  'XGFab9nDYwyrDFb2iRtUCBfrFI7stIXUi6FzL2eLwD4DDVxM7qTTtb3e7Z0WkrPdwbru3VYYAjz3i+u/QJgbYOKbkkj7EN/r' +
  'zXKYj3bcFIbcEjSu19smbmxM31wTWqPo616jHxNpK8A1WBeriW96RaRzuHHn2LvVHMRuxty+q2izrTCF0Vc242WxWlhTGmCI' +
  'SI/fxHhtZfjNWOn4TEQ7WtkLgl0Wq3bM3Iu0H5h1hk5tR1IEbV4WGV2BJaZvCE3RXhDsuVg1hZpKpLVDblHN0Ppq32MsCPZY' +
  'rGpCHf1SiDQM7nFUqb65tmtw4p8fxKqVhRTllwKW71q6u6NmZY8TlQ5iFd9lwpqCGVpWdpYbMYhVmoUEaypHI0pWIoq+7CDW' +
  '6K8VWFMQgNTKjt/67Rh+3DkusKaAS7SVHY7r2qg7S1hTEAvpJvKormW7ALQzYE2BBNIPV7C9UeXlsyauEwcbJsLgtVUmIoON' +
  'wDtb5iVfU6sbAHLQH+21LHVvuTAPZID3rc6swSos4wfUS0QdFr9gENYVSIlJmOpd0NbXv7AQdEEBIDazrz89aKPOTGtoIAbK' +
  'QlIiNUa9RjcgsrSiljaNIC9KJVJjIouLz4qBlQWX0Cg4nQWiBrF6V0BYuAYrC+ZoFZzOIqaH0wCJdf36DFjZb49m+f5JhtZB' +
  'rGRdtWpnYGW/J5rl+wt5KMfnrJoVirCy3wet50VMXEiYOg8KCPINF4Fot4tFx56VzL7lCJZFXyOINgNGeR8mDaSvl0ith1st' +
  'mqNBtIUSkPdh1eU8sETqem7Al1ug3JNJ+3lW4Bxuxeylbn5mrfh5Badh+ayD4vf6PbA2Wn5cCpR/3DAbP0+Nfo8aOys1EZ7j' +
  'fdPbZ85beFlX2lYWydy2iII9XqQ7p058+T4/RdDffPX+hYYvi8JDezSCPVoIy/fjn9YitrIb7rtaEkUYBJ1mKLJHC0msLPzV' +
  'dGRrd8/och6AzhMGrVp3Ax2Sd9jWFemE7rNbOaJF/4G0+A7bCQRr2FbK5qnYV0ULfzULloJN0OXc7hHuxCXRwl/Nh9ZJzkTC' +
  'Vvz8JwzGQAN5fB9+L+IRmgVadn+A78L6jkk3u8Z6ZGgl1bjUUBSMM0hunwKc3fKg+aVOkkGiHZ8GSWSY5/RiBeUyGYbTNqhT' +
  'pDGzIfgPAAD//22l0fgAAAAGSURBVAMAqEEqo29RgwkAAAAASUVORK5CYII='

/** Display size in pixels, and so the artwork's 50:21 aspect. */
export const BANK_LOGO_PNG_WIDTH = 57
export const BANK_LOGO_PNG_HEIGHT = 24

/** The mark's PNG bytes. */
export function bankLogoPng(): Uint8Array {
  const binary = atob(BANK_LOGO_PNG_BASE64)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i)
  return bytes
}
